### ISSUE TITLE
[Enhancement] Produce error messages from common-c that aren't useless

### ISSUE THREAD

**Issue by cgutman** [moonlight-stream/moonlight-ios#100]
Many (all?) of the error messages generated when common-c fails to connect for some reason display an error code of -1 which is useless for diagnosing anything. We should at least display the real socket error code or (preferably) text like "Connection Refused" or "Connection Timed Out". This is probably a task that will involve both common-c and iOS-specific code.

It will help diagnosed problems like #98

**Comment by duomi** [comment]
please can you remove me from the beta.

Many thanks.

**Comment by mrb113** [comment]
@cgutman I took a short look at RTSP and performRtspHandshake() returns only -1 on failure. Since I own(ed) most of RTSP, I dibs looking at that method in common-c and returning some more useful exit codes for each of the failures.

**Comment by dwaxemberg** [comment]
@cgutman @mrb113 any updates on this? Just going through the issues marked for v1 and getting them checked off.

**Comment by cgutman** [comment]
This is fixed in common.
