### ISSUE TITLE
Streaming over internet not working

### ISSUE THREAD

**Issue by Balkp** [moonlight-stream/moonlight-ios#101]
I see My computer paired and online but when i select it it just loads for a few seconds and then nothing happens. 
I have tried streaming to an android device from the same computer and it works.

**Comment by Greensauce** [comment]
I am able to stream over the local network to both my iPad Air 2 and iPhone 6. When I tried with my iPhone 6 over cellular the paired computer shows "Offline". Clicking on it does nothing. 

Do any ports need to be open for this to work over the internet?

**Comment by Kaeltis** [comment]
Maybe this helps (haven't tested it)
https://forums.geforce.com/default/topic/764435/tips-and-tricks/tnt-shield-gamestream-on-the-go-guide/

**Comment by Edgeros** [comment]
I found the solution for this. It's a bug in Moonlight. I already posted it in here: https://github.com/moonlight-stream/moonlight-ios/issues/140

**Comment by cgutman** [comment]
Duplicate of #140.
