### ISSUE TITLE
Video latency

### ISSUE THREAD

**Issue by capmalo** [moonlight-stream/moonlight-ios#106]
So hello everyone,

I use Moonlight on my jailbroken iPhone 6 and I experience some lag in video in wifi, no matter I use the Wifi G of my internet router or a direct Wifi N connexion with my gaming laptop. I tried to with a tweaked home made usb connexion it's better but not the best because it's wasn't made for (maybe someone will made a special package on cydia later, or a special moonlight ipa), input is ok but looks like 20fps on the phone it burn eyes with a vr headset on.

I stream in 768p according to the resolution of the iPhone, with no bluetooth or other things that can disturb the wifi connexion.

I tested yesterday with the Xiaomi mi4 of my friend and it worked well on wifi and far better on USB in 1080p.
I played with the bitrate slider, under 12mbps it's becoming worse and over 12 too.

If you can help me I'm listening to you, but I think more and more to take a LG G2 only for my Homido.

Capmalo

**Comment by mrb113** [comment]
This is likely a network issue - if you are still having problems, let us know.
