### ISSUE TITLE
Potential Beta Tester

### ISSUE THREAD

**Issue by Exoma** [moonlight-stream/moonlight-ios#107]
Hello, I own an iPhone 6+, iPhone 3G, iPad Air, and an iPad Mini (First Generation)

I am free to beta test your app if you'd like me to. :)

I also have several Windows Phones if you ever plan on putting out the app for Windows Phone, I can beta test with:

Nokia Lumia 1520
Nokia Lumia 920
Samsung Ativ S
Nokia Lumia 830

Please let me know and I'd love to begin. :)

Email: amir.moazzami@outlook.com

**Comment by dwaxemberg** [comment]
added
