### ISSUE TITLE
Remove the swipe to go back gesture in the streaming view

### ISSUE THREAD

**Issue by shusain93** [moonlight-stream/moonlight-ios#109]
I've been having this issue a bunch when playing with the on screen buttons. If you swipe from left to right, the steaming view dismisses and the connection exits. This turns out to be a huge issue when flying plans in GTA V if you switch for acceleration to rudders quickly. I understand this is the only way to go back to the stream menu in iOS, but could we maybe just stick a little button in a corner?

**Comment by dwaxemberg** [comment]
The new beta has a smaller edge detection. Please test this and comment on your experience.

**Comment by shusain93** [comment]
Good! Fixed my issue but the new version added a different issue.
