### ISSUE TITLE
Idea - Maybe Use Buildstore?

### ISSUE THREAD

**Issue by firestorm185** [moonlight-stream/moonlight-ios#111]
Hey guys! Can't wait until the next beta comes out! You guys have worked so hard on this, the final product's bound to be amazing!

For the meantime, I know we use Testflight, but there's another neat little site I found called the Build Store (www.builds.io) which, for a ten dollar fee, allows several non-appstore apps to be downloaded. It's how I am still using GBA4iOS after the IOS 8 update. No pressure, it would just be a great way to get the app out to more people. Here's the link to their publishing page - http://builds.io/publishing/

Good luck, and hope to see the app on the App Store soon!

**Comment by mrb113** [comment]
Hi, we've looked into BuildStore and we're opting to not use it at this time. Thanks for the suggestion and for using Moonlight!

**Comment by firestorm185** [comment]
Yeah, welcome! Thanks for letting me take part in the discussion! Looking forward to the next beta!
