### ISSUE TITLE
iPhone 4S support

### ISSUE THREAD

**Issue by cgutman** [moonlight-stream/moonlight-ios#117]
We need to figure out what to do about the 4S. It supports iOS 8 so Moonlight can technically run. The on-screen controls will need work if we're going to support 1.0 on the 4S. The other issue with the 4S is that it doesn't support 5 GHz WiFi, so the experience is likely to be bad anyway.

Anyone testing on a 4S please comment on your experiences.

**Comment by dwaxemberg** [comment]
As of a6a1929a43ec9918325ef955ca08063ac8565f75 and 4d55a6a7e98afe1a0b5e57a8cb7c28f209a9aa70 on-screen controls should be much easier to use on iPhone 4s. 
Testers: please provide feedback on your experiences with an iPhone 4s

**Comment by iHanatos** [comment]
I have iPhone 4 this is not fit?
Asus RT-N56U 5\2.4GHz Wi-Fi. 100 MB Download\Upload

**Comment by dwaxemberg** [comment]
Moonlight requires iOS 8 and up, unfortunately iPhone 4 does not support iOS 8.

**Comment by iHanatos** [comment]
Oh.. Yeah.. Not good.
