### ISSUE TITLE
Would love to be added for next Beta

### ISSUE THREAD

**Issue by M0BI0S** [moonlight-stream/moonlight-ios#120]
I would love to be added again for the next Beta round of moonlight. 

Iphone 5 / 6
Ipad Air 2 
ios 8.3

Evga 780 gtx ftw
2.4 / 5 ghz Wifi

Email: olio (at) highfire.de

**Comment by dwaxemberg** [comment]
If you're already in the list, you will automatically be included in the next beta -- no need to re-add.
