### ISSUE TITLE
Swipe from left edge behavior is confusing

### ISSUE THREAD

**Issue by surrealroad** [moonlight-stream/moonlight-ios#125]
I noted that with 0.9.1 there wasn't a way to change the control scheme once the game had started, at least until I happened to swipe across from the the left edge. However even after discovering this, I found I was doing it by accident anyway, which was disruptive. Can this instead just be a special button when using a virtual controller?

Also, whilst in this game running state, there was no indication in the app that the game was still in progress, or indeed which one was running. Be good to have some indication of this.

--
iPad Air (iOS 8.3) / Windows 8.1 64-bit / Nvidia GTX 970 / Airport Extreme (2013) / 802.11ac (5 GHz) / 1080p / 50 Mbps / 60 Hz

**Comment by Kaeltis** [comment]
Happened to me aswell, maybe make it harder to accidentally open the menu (like forcing a 2 finger swipe) and add a visual indication on where to swipe from to open the menu when starting a game.

Also displaying the currently running game from the main menu or a "return to game" button would be nice.

**Comment by dwaxemberg** [comment]
Fixed in 67a8b232b931eb97f8cd2eb5c39fffff60614288 and e3a42db0072e327f2da8358ecadba106890af4f3
