### ISSUE TITLE
Just a few questions, not sure if this is an issue.

### ISSUE THREAD

**Issue by nigerson** [moonlight-stream/moonlight-ios#127]
So, I've been part of the beta for the past two revisions in testflight. But a few days ago limelight/moonlight vanished from testflight. Is this because the app, "expired", or have I been kicked from the beta?

**Comment by branr** [comment]
I believe for TestFlight each build of the app (like, each version 0.8, 0.9 etc) have a life of 30 days. It's a security thing to keep Apple's garden walled.

**Comment by dwaxemberg** [comment]
@nigerson it's possible you were not merged to the new beta list. What is your email?

**Comment by mrb113** [comment]
Hi nigerson, 
Sorry for the disappointment, but the beta is full and we're not accepting more beta testers/re-adding expired beta testers at this time, but thanks for your interest in improving Moonlight! We understand that our users are anxious to start streaming games to their iOS devices, so join this email list if you want a notification the day it's available. (This is the only thing that email list will be used for) http://eepurl.com/btvkG9
