### ISSUE TITLE
Green charging indicator (battery symbol) shown when plugged in

### ISSUE THREAD

**Issue by Kaeltis** [moonlight-stream/moonlight-ios#128]
When the charger is plugged into the device (iPad 3) and moonlight is in a game, the green charging indicator is shown altough the iOS status bar is hidden.
I think this is happens because the status bar is not really hidden, but with a black text color over the black bars and the green charging indicator overrides this.

**Comment by cgutman** [comment]
This bug still affects master. I can repro with an iPad retina simulator when streaming native resolution.

**Comment by cgutman** [comment]
Fixed by 4ea8694
