### ISSUE TITLE
Host duplicates sometimes

### ISSUE THREAD

**Issue by Kaeltis** [moonlight-stream/moonlight-ios#132]
Sometimes when i'm using a bad WiFi connection and close moonlight, my Host PC is duplicated in the list of hosts.
Also, when trying to start a Game again after closing moonlight, it says there was already a Stream in progress, the only way to fix this is to close the game manually on the PC.

**Comment by Kaeltis** [comment]
I found out hosts can be removed by holding the icon, this didn't seem to work before.

**Comment by kaneface** [comment]
Yes this happens to me too but with a great connection as i am having an amazing no lag gaming to ipad

**Comment by cgutman** [comment]
Workaround added in 920cbad
