### ISSUE TITLE
iOS 9 moonlight performance decrease

### ISSUE THREAD

**Issue by Kaeltis** [moonlight-stream/moonlight-ios#135]
Since I installed iOS 9 on my iPhone 5s, the performance of moonlight (with 1080p, 60Hz, 10-30 Mbit) seems worse, the sound is crackling and everything feels laggy and sluggish.

I'm not 100% sure this was caused by the iOS 9 update, however nothing else of my configuration has changed.

**Comment by shusain93** [comment]
This is to be expected to some extent as you're running the first beta. If it's still an issue on the GM, it would be a thing of concern.

**Comment by Kaeltis** [comment]
Yes, but imho it's still an issue the devs should be aware of.

**Comment by cgutman** [comment]
Thanks for reporting. Well see if others report the same problem.

Something similar happened during the developer preview of Android 5.0. It had a bug causing lost packets every 10 or 15 seconds. It was fixed before the final release.
