### ISSUE TITLE
MFU Controller does not work on many games

### ISSUE THREAD

**Issue by agentwolf88** [moonlight-stream/moonlight-ios#136]
What can i do when my moga ace power does not work in game like Oddworld new n Tasty or Finding Teddy 2?

**Comment by agentwolf88** [comment]
The onscreen control doesnt work too.

**Comment by mdstraughan** [comment]
Having the same issues here. None of my games, except for Ori and steam itself, are working with an MFi controller. 

Using Gamevice on iPad Mini

**Comment by cgutman** [comment]
Make sure you have unplugged all controllers from the PC. They can interfere with GameStream's controller emulation.

**Comment by agentwolf88** [comment]
That is not the problem, there is no controller connected on PC. I have all controllers unpluged befor i play with moonlight but the control does not work on many games.
