### ISSUE TITLE
Ps4 Controller

### ISSUE THREAD

**Issue by kaneface** [moonlight-stream/moonlight-ios#137]
This is not an issue thought i should share that i have a dualshock 4 connected to the main pc and i changed the file names in nvidia folders as they were stopping the controllers from working and i am getting full controller dualshock 4 support. Bluetooth reaches around the house too. 

To summarise
Dualshock connected to pc to control the streamed games to the iphone/ipad

**Comment by Athanaetos** [comment]
Can you tell me what Bluetooth Adapter you are using? Since mines just gives out at any distance. I think its my adapter and wanted to know?

**Comment by kaneface** [comment]
yes i think its a belkin

**Comment by shusain93** [comment]
Not an issue, should be closed.

**Comment by mrb113** [comment]
Not an issue. Closing
