### ISSUE TITLE
Can't remote play via Internet 

### ISSUE THREAD

**Issue by tleung927** [moonlight-stream/moonlight-ios#140]
I can't play with pc Mac and android but not iPhone 6 
I can see the pc online but can't connect with it

**Comment by Edgeros** [comment]
I had this problem as well, but I found out it's a bug. Remove the host from your list and pair it again from another network with hosts IP address (with 4G like I did, for example). Now you can play your games via home network AND via Internet. ;)

**Comment by Greensauce** [comment]
When i try manually adding using my IP over my 4G connection I get "Could not connect to host".

Do any ports need to be open for this?

When I turn wifi back on I can see my PC as "Online" and "Not Paired".

**Comment by tleung927** [comment]
i found it in google play store there is link tell you what port to forward

**Comment by Greensauce** [comment]
I got this working. The specific ports are listed here:
https://github.com/moonlight-stream/moonlight-android/wiki/Setup-Guide#streaming-over-the-internet

**Comment by cgutman** [comment]
The issue reported by @Edgeros is actually a bug in the client. It is fixed by 935fb6ffe352fed1707c831d6e059ed105b59af6

**Comment by abattrick** [comment]
When is next release I can't connect to pc anymore?
