### ISSUE TITLE
Beta Tester?

### ISSUE THREAD

**Issue by caronter02** [moonlight-stream/moonlight-ios#16]
Hi, i've been waiting this for so long!  Already a limelight user on android, but I'd prefer it on my ipad by far. Is there a chance I help with the beta ? I'm on iphone 5s and iPad 3. Please let me know. Thanks!

My email is: caronter02 at gmail dot com

**Comment by Darth-R3V3N** [comment]
Hi guys,
I would love to join if I may in the beta testing for limelight iOS. I have been very excited ever since I saw the project advertised on the limelight website. I have the iPad Air and the strait iPhone 5. Please let me know if I can join the fun. My email is stewartdrums@hotmail.com

**Comment by beeding** [comment]
Can I become a beta tester? I have an iPhone 5s jailbroken.
Email: scarorgmc@gmail.com
