### ISSUE TITLE
New Build?

### ISSUE THREAD

**Issue by kaneface** [moonlight-stream/moonlight-ios#160]
Hello my beta has expired and it was a very good version with hardly and bugs. So wondering if you will add it the build lists so we can install it (on jailbroken device).

Thanks

**Comment by mrb113** [comment]
Hi kaneface, 
We're not accepting more beta testers at this time or adding expired beta testers back, but thanks for your interest in improving Moonlight! We understand that our users are anxious to start streaming games to their iOS devices, so join this email list if you want a notification the day it's available. (This is the only thing that email list will be used for) http://eepurl.com/btvkG9
