### ISSUE TITLE
Would also live tour join beta

### ISSUE THREAD

**Issue by ohgodthatsgreat** [moonlight-stream/moonlight-ios#162]
Email adress: nrundgren@gmail.com

**Comment by abattrick** [comment]
Reissue beta? Mines expired 4 days ago

**Comment by mrb113** [comment]
Hi ohgodthatsgreat and abattrick, 
We're not accepting more beta testers at this time, but thanks for your interest in improving Moonlight! We understand that our users are anxious to start streaming games to their iOS devices, so join this email list if you want a notification the day it's available. (This is the only thing that email list will be used for) http://eepurl.com/btvkG9
