### ISSUE TITLE
I would like to join the beta.

### ISSUE THREAD

**Issue by JayEffTree** [moonlight-stream/moonlight-ios#164]
I would love to test this out for IOS 8 my email is jfinelli1337@gmail.com for Apple ID

**Comment by mrb113** [comment]
Hi JayEffTree, 
We're not accepting more beta testers at this time, but thanks for your interest in improving Moonlight! We understand that our users are anxious to start streaming games to their iOS devices, so join this email list if you want a notification the day it's available. (This is the only thing that email list will be used for) http://eepurl.com/btvkG9
