### ISSUE TITLE
RTSP handshake failed with error 500 

### ISSUE THREAD

**Issue by WTForskin** [moonlight-stream/moonlight-ios#169]
My device (iPhone 6+ 16gb running iOS 8.1.2 Jailbroken) is able to connect to my PC but when attempting to remotely view the application or game i receive this error "RTSP handshake failed with error 500", the games and application launches fine on my PC but there is not remote viewing on my device

**Comment by aperiodic** [comment]
I experience this issue as well, on an iPhone 5S 64GB Running iOS 9.1

**Comment by aperiodic** [comment]
I also experience this on my iPad Mini, also running iOS 9.1. Is the `500` code referring to the HTTP status? If so, that would point to a problem with the nvidia game streaming on my PC, but my geforce experience thing is all up to date, and this is happening on my local network (so port-opening shouldn't be necessary).
