### ISSUE TITLE
Can I try the beta my email is norahabasto@yahoo.com

### ISSUE THREAD

**Issue by rickerson** [moonlight-stream/moonlight-ios#171]

**Comment by mrb113** [comment]
Hi rickerson, 
We're not accepting more beta testers at this time, but thanks for your interest in improving Moonlight! We understand that our users are anxious to start streaming games to their iOS devices, so join this email list if you want a notification the day it's available. (This is the only thing that email list will be used for) http://eepurl.com/btvkG9
