### ISSUE TITLE
if my pc is wired how do i connect?

### ISSUE THREAD

**Issue by freddyhh123** [moonlight-stream/moonlight-ios#175]
Please help me my pc dosent support wifi can i connect?

**Comment by ZeroT3K** [comment]
WiFi is just a means to connect to the network. Provided you have a wireless router for other devices, you can still access your PC if it's connected to it with a network cable. Same instructions apply, just need to make sure your client device and streaming device are on the same network.

**Comment by mrb113** [comment]
Please check out our setup guide. If you still have issues, let us know.
https://github.com/moonlight-stream/moonlight-android/wiki/Setup-Guide
