### ISSUE TITLE
tvOS application

### ISSUE THREAD

**Issue by slagod** [moonlight-stream/moonlight-ios#177]
Hi Guys,

I think that new AppleTV is perfect target for Moonlight.
As tvOS is based on iOS, it shouldn't be very hard to create version for tvOS from your current code.

Are you planning release on tvOS platform?

**Comment by BEEware** [comment]
+1

**Comment by mrb113** [comment]
We do need to release on iOS first (coming soon... need to ping our dev leading the iOS effort to see where he's at); however, we are investigating AppleTV. Thanks for the feedback!

**Comment by ceesco53** [comment]
I have an Apple TV and an apple dev license.  I can compile and test code if needed.  Beyond that, I'm useless.
