### ISSUE TITLE
Create launch screen

### ISSUE THREAD

**Issue by cgutman** [moonlight-stream/moonlight-ios#178]
We need to make a launch screen before we can submit to Apple. We will probably have to change the background from black to grey or some other color because a black launch screen looks like the device is off.

https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/LaunchImages.html

**Comment by phantom-playR** [comment]
![preview landscape](https://cloud.githubusercontent.com/assets/4344835/10159309/c2089ec0-6697-11e5-907f-8cb0f7e35c11.jpg)

![preview portrait](https://cloud.githubusercontent.com/assets/4344835/10159305/c1fe677a-6697-11e5-8071-ddc088d00b59.jpg)

**Comment by cgutman** [comment]
Thanks. This isn't really what Apple is looking for in a launch screen on modern iOS versions. Diego created launch screen last night but I'm not sure if he's finished yet. Assigning to him.

**Comment by phantom-playR** [comment]
But it's difficult to do something like Apple exemples, because the interface of the app is dark.

**Comment by dwaxemberg** [comment]
Fixed in 1da877fed707dd0b64b6879e7c831e7e8cf2d579
