### ISSUE TITLE
I would like to join the beta.

### ISSUE THREAD

**Issue by glitchninja2000** [moonlight-stream/moonlight-ios#180]
This is the only way I've seen people join the TestFlight Beta, so I'm trying it. I have 5 different iphones and 2 ipads I could test this on
glenntashworth@gmail.com

**Comment by jeaz** [comment]
They quite clearly state that they aren't accepting more into TestFlight at this time. I was in it, but got removed for some reason along the road. Guess I didn't post enough error logs :-)

Not sure of the status of the project in general, been a bit quiet.

**Comment by Kaeltis** [comment]
With Xcode 7 you can compile and run it yourself, without an apple developer account.
They seem to have removed me from TestFlight as well, so thats what I did.

**Comment by mrb113** [comment]
Moonlight iOS is on the store now - closing.
https://itunes.apple.com/us/app/moonlight-game-streaming/id1000551566
