### ISSUE TITLE
Click where I tap

### ISSUE THREAD

**Issue by jankazemier** [moonlight-stream/moonlight-ios#186]
I would like an option where in stead of a huge touch-pad, I'd rather click where I tap, like the tablet normally does (would be very nice for games like Civilization and adventure-games)

**Comment by cgutman** [comment]
Unfortunately this is not yet possible within Nvidia's GameStream protocol. Some Shield owners have also wanted this but so far Nvidia hasn't implemented it.

**Comment by mrb113** [comment]
Closing as won't fix
