### ISSUE TITLE
iPad Pro fails to pair

### ISSUE THREAD

**Issue by tfurlong** [moonlight-stream/moonlight-ios#187]
Pairing does not succeed on an iPad Pro.  I've got an iPad Air that pairs no problem, so it seems to be a problem specific to the Pro.

**Comment by ceesco53** [comment]
My iPad Pro works very well with the moonlight iOS client.  Host machine is running SLI GTX 780Ti with 359.06 driver release.

**Comment by tfurlong** [comment]
I just tried it again this morning, and it worked fine, no bug here.
