### ISSUE TITLE
Pairing Failed

### ISSUE THREAD

**Issue by TylerJaacks** [moonlight-stream/moonlight-ios#188]
I have Moonlight installed on my iPhone 6S Plus when attempt to pair to my pc after entering the PIN on my PC I get "Pairing Failed".

- Intel Core i7 4790K
- 16GB RAM
- NVIDIA GTX 970
- Windows 10 Pro x64
- GeForce Experience v2.8.0.80
- Driver Version v359.00
- iOS 9.1
- Moonlight v1.0.1

**Comment by rift1337** [comment]
Hi,
I have the same exact problem
Did you solve the issue?

**Comment by HeyGamingHD** [comment]
Hi! I also had this problem. But i just found the way for it to work. Go to settings, and at the buttom it should say like "Betaupdates" press "beta for geforce experience" and download. this should solve the issue.

**Comment by mrb113** [comment]
@HeyGamingHD your "can't launch" issue may be related to H265 - try going to settings and force H265 to never be used. A fix is in the pipeline

**Comment by Coolgyerek** [comment]
@HeyGamingHD It doesn't works for me. :(

**Comment by TylerJaacks** [comment]
It just seemed to fix itself.

**Comment by askep3** [comment]
I've been getting this issue ever since the app launched. Moonlight works great on my iPad 3, but seems to have some problem with iPhone 6s
