### ISSUE TITLE
Beta-Test

### ISSUE THREAD

**Issue by joevent** [moonlight-stream/moonlight-ios#19]
Hello guys, 

I kept an eye on your project for month and i think its a fascinating project.

So if you need more beta-tester, i would offer myself. I've got an iPhone 5s and an iPad air.

So tell me if you need more tester.

Thanks a lot!

Email: jonathanventur at googlemail dot com

**Comment by kaga1h** [comment]
Thx !kagai@me.com
iPhone6 plus ios8.12

**Comment by icanic** [comment]
Greetings! 
Can I join in for a test flight? 
My email is ivan.canic@gmail.com

**Comment by JoshRenoir** [comment]
thx!!! 
secretsigns@gmail.com
ipad air ios 8.3
