### ISSUE TITLE
Stuck at 'starting app'

### ISSUE THREAD

**Issue by LiKao15** [moonlight-stream/moonlight-ios#190]
Moonlight doesn't work for me. It worked fine for 5-10 minutes and now whenever I launch steam in the app it indeed launches it and gamestream on the desktop but I'm stuck with a "starting app" loading screen on the ipad end.

Any idea ?

**Comment by cgutman** [comment]
Tried rebooting your PC?

**Comment by LiKao15** [comment]
Tried
- rebooting
- checking for any GF experience update
- closing and opening the app
- uninstall / reinstall of the app
- canceling the pairing and making a new one
Still stuck at "starting app".

**Comment by cgutman** [comment]
Weird, I'd try uninstalling GeForce Experience and installing it again from Nvidia's website.

**Comment by LiKao15** [comment]
Still the same problem after a reinstall of GF Experience.

**Comment by cgutman** [comment]
Have any Razer, TeamViewer, or DisplayLink software installed?

**Comment by LiKao15** [comment]
Nope, nothing of the sort :-/

**Comment by pal64mc** [comment]
I dont have this problem, i can start the app, but i had razer stuff installed and i uninstalled it and i keep getting: connection to the pc is interrupted.

**Comment by mrb113** [comment]
Can anyone confirm if this is still happening?

**Comment by pal64mc** [comment]
Uh for me it was until i made the needed changes.

**Comment by jacklfjr** [comment]
Same issue for me : MonnLight worked perfectly on my Ipad, during 5  minutes. After a restart, I m now stucked with "Starting App" message, even if on the server side, everything seems to be ok (the game is starting / streaming). I tried also to reboot PC / IPAD, with no success.

**Comment by pal64mc** [comment]
ttry what i said earlier.
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by jacklfjr** [comment]
I ve already tried :
rebooting
checking for any GF experience update
closing and opening the app
uninstall / reinstall of the app
canceling the pairing and making a new one

**Comment by angrycrab** [comment]
Reinstalling Nvidia drivers with DDU In safe mode fixed It for me.

**Comment by pal64mc** [comment]
yeap
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by RaynLegends** [comment]
Bump, I have the same problem. I already tried:
- Rebooting (Both my PC and my iPhone)
- Reinstalling (Nvidia drivers, GFE and Moonlight, even with DDU)
- Disabling Windows Firewall

But I still get stuck at "Starting App"

**Comment by link123a** [comment]
Angrycrab's advise ( close remote desktop application ) worked for me!

Thank you

**Comment by ItsKipz** [comment]
Having the same issue, but never used Remote Desktop before. Already tried reinstalling drivers, GFE, even tried using DDU and clearing out everything.

**Comment by cgutman** [comment]
Closing this old issue.
