### ISSUE TITLE
Proposal of License changing

### ISSUE THREAD

**Issue by mzyy94** [moonlight-stream/moonlight-ios#194]
Hello.

I love this project and check the codes every week. 
One month ago, Moonlight Game Streaming iOS version was released on the AppStore.
It's good news but I have something to worry about.

In 2011, VLC for iOS was removed from AppStore because of licensing issues.
c.f. [VLC app removed from App Store - Engadget](http://www.engadget.com/2011/01/08/vlc-app-removed-from-app-store/)
c.f. [VLC Media Player Could Make A Return To The iOS App Store | Cult of Mac](http://www.cultofmac.com/201703/vlc-media-player-could-make-a-return-to-the-ios-app-store/)

Moonlight Stream is not huge project like VLC but we also have same issue.
I think, we should discuss license changing to LGPL or another one. :(

**Comment by mrb113** [comment]
Hi mzyy94, 

Thanks for bringing this up, as this is worth investigating. LGPL isn't what we want either as it is also incompatible with the App Store. We have several reasons for choosing the GPL. You're right that Apple could remove our app if someone reported it to be in violation of the licensing agreement. 

Relicensing can be complicated and have ramifications, so we need to consider our move here.

@cgutman can you look into this?

**Comment by mrb113** [comment]
We are not going to change the license at this time.
