### ISSUE TITLE
Audio stutter and delay

### ISSUE THREAD

**Issue by Russboy360** [moonlight-stream/moonlight-ios#196]
Hello

I have started using Moonlight and so far it is great, apart from one thing, the audio is stuttering and delayed but the video works perfectly. I have tried different bit-rates and nothing seems to sort this out.

Has anyone else had this happen or knows how to fix this.

Thanks
Russ

**Comment by flaxfoot** [comment]
Got the same thing. I'm going to try and see if it is a driver issue later
today on the hosting computer.

**Comment by Russboy360** [comment]
Awesome, thanks. Hopefully we can get to the bottom of this.

**Comment by Russboy360** [comment]
Flatfoot you were right, after uninstalling and reinstalling my audio drivers the streaming is now working fine.
Thanks
