### ISSUE TITLE
Update Touchscreen Controls to Match Wiki

### ISSUE THREAD

**Issue by jeffy777** [moonlight-stream/moonlight-ios#198]
The Touchscreen Controls section of the wiki states:

"Tap and hold in the same place to start a click and drag. After a short while, swipe the finger to drag in the direction of the swipe."

"Tap with three fingers to open the on-screen keyboard."

Neither of these currently work. Most games that use the mouse require you to be able to click and drag, which makes many games unplayable.

Also, having an on-screen keyboard would be ideal for games that require you to login, use the ESC key to access game options, etc...plus you would be able to chat.

**Comment by Mimiste** [comment]
Most point and click games are actually unplayable because you often have to drag and drop stuff... So yes that would be great to see that improved :)

**Comment by jeffy777** [comment]
Just wanted to say a big thank you for adding long press to drag in the latest version!
