### ISSUE TITLE
MFI controller no longer working.

### ISSUE THREAD

**Issue by Athanaetos** [moonlight-stream/moonlight-ios#200]
Recently my MFI controller is no longer working with Moonlight. I have made no hardware changes.

**Comment by jpecih** [comment]
I had the same issue, but I solved it resetting PC and GFE. For games not compatible with streamed MFI  gamepads I am using joytokey in the streaming PC.

**Comment by jpecih** [comment]
Another possibility as I experimented  is that your wifi is 2,4ghz that immensely collides with BT mfi controllers. The only possibility is to work in 5Ghz wifi band or use wired controller.

**Comment by dwaxemberg** [comment]
@Athanaetos Are you still experiencing issues with MFI controllers?
