### ISSUE TITLE
Connection terminated

### ISSUE THREAD

**Issue by nguyenbrian** [moonlight-stream/moonlight-ios#202]
I can get past the main menu of a game alright, in this case being Hotline Miami 2. But once I load the main level the game closes and I get a "Connection terminated" error.

I'm on the latest Nvidia drivers and reinstalled GeForce Experience.

**Comment by nguyenbrian** [comment]
Update: Civ 5 appears to work with no issues

**Comment by jeffy777** [comment]
I am now getting this issue every time I connect, whereas before everything was fine. It now says "Connection Terminated" after a few seconds no matter what game I play, and it cause Steam to crash afterwards. Maybe it's an issue with the latest Steam update?

**Comment by cgutman** [comment]
That's exactly what it is. Steam's last update broke GFE's integration in a way that causes the connection to disconnect when it times out.

https://forums.geforce.com/default/topic/909598/gamestream/gamestream-broken-with-steam-and-big-picture-mode/

**Comment by jeffy777** [comment]
Thanks for the confirmation. Yeah, it's losing connection for me even if I just sit in the Steam menu for 45 seconds or so without even launching a game. Hopefully the next Steam update takes care of it.

**Comment by jeffy777** [comment]
The steam beta update that was just released fixes this issue.
