### ISSUE TITLE
Error in connecting to host following GFE update

### ISSUE THREAD

**Issue by at45** [moonlight-stream/moonlight-ios#203]
An update for GFE was released yesterday (2.10.2.40) with the below release highlights.

GeForce Experience 2.10.2 Release Highlights
•Fixes an audio issue when a SHIELD Controller is connected to the PC.
•Improves GameStream stability and connectivity.
•Fixes an issue when GameStream ends after host PC monitor is off or disconnected.

Following this update, I am not able to connect to the paired host, same case in both iOS and tvOS.

Reverting back to the previous GFE version solved the issue.

Does anyone experience the same error following the update?

**Comment by cgutman** [comment]
Yes, the is a known issue. We will submit a Moonlight update for review in the next few days to address the issue.

**Comment by at45** [comment]
Great, thanks for letting know.

**Comment by djrockgt** [comment]
It works for me on all my moonlight devices but not with the latest GFE 2.11.x.x updates. Not sure why GFE 2.10.2.40 won't work for you. Once I rolled back, everytning was fine for me. Odd.
