### ISSUE TITLE
Recommended GFE versions? Error code list?

### ISSUE THREAD

**Issue by WishyWash** [moonlight-stream/moonlight-ios#204]
I'm trying to stream to the Moonlight iOS app using the latest GFE beta version (2.11.x). After connecting to the server and launching a Steam game from the Moonlight app, the RTSP handshake fails with error 35. I tried disabling the Windows 10 firewall, but that only changed the handshake error from 35 to 404.

Two questions:
Is there a recommended GFE version for use with Moonlight? Is the latest stable build (2.10.2.40) likely to work? Is there a list of Moonlight error codes to help narrow down the problem?

Thank you!

**Comment by cgutman** [comment]
GFE 2.10 will work. The beta isn't supported yet.

**Comment by WishyWash** [comment]
Thank you, Moonlight works perfectly with GFE 2.10.2.40. :-)

**Comment by Havebeard** [comment]
I've got 2.10.2.20 and I can't get it to work.
I can start apps, but then the iPad just says RTSP handshake failure error -1
