### ISSUE TITLE
Connection Terminated.

### ISSUE THREAD

**Issue by Baywey** [moonlight-stream/moonlight-ios#205]
I've read through literally dozens of forums, including a thread on this forum with a similar issue. Mine is a little different, though.

Here's the issue:  in the moonlight app, I can connect to my remote PC  and see the games in the list. When I click on one, it goes through the standard procedures of "Starting App", handshake, etc. Somewhere between audio and input, I receive a pop up indicating that connection was terminated. On my remote PC, the NVIDIA User Agent application, as well as the game, are playing. Upon reading through the logs, I see several lines toward the end indicating "Failed to start video pipeline," and "Received termination reason 0x8109," among other failure events.

I am playing (or attempting to) through the Internet. All ports have been forwarded appropriately. I do not use Steam. I have attempted to reinstall graphics drivers with a clean installation, GeForce Experience, and have attempted PC and router restart, all to no avail. Current drivers and software up to date.

I have had this issue numerous times, and have gone through the above steps numerous times. It has worked up until now. Interestingly, the issue only seems to occur after I have gotten home, resumed play on my PC directly, and then attempted to reconnect once I have left again. It could be coincidental, I don't know. 

Any thoughts?

**Comment by turbineseaplane** [comment]
I have the same problem - Can never get it to do any actual streaming..  Always "connection terminated"

**Comment by cgutman** [comment]
Can you verify that you're on GeForce Experience v2.10 and running Moonlight 1.0.3?

**Comment by Baywey** [comment]
GeForce Experience is 2.10.2.40, and Moonlight is the latest build from the App Store.

**Comment by Tdogb** [comment]
Figured out a solution (sorta) you have to reinstall GeForce experience. And it should work. However I connected fine the first time but then after disconnecting and reconnecting, it said connection terminated again. Hope this may help u or the devs (maybe you guys can patch it!)

**Comment by HotDog800** [comment]
Thanks Tdogb.  

I have a fix as well.  I tried clean installing GFE, but that wasn't working.  Completely removed it, then clean install, then reboot - same error.  

What I did to fix it:

1. Completely removed GFE.
2. Rebooted
3. Clean install of an OLDER version of GFE (I used 2.10.2.40)
4. Rebooted
5. Ran GFE - It took about 10 minutes, then crashed - But I believe this is due to another unrelated bug, as I have seen it before
6. Closed GFE
7. Ran again - It then auto-updated itself to latest GFE
8. Connect using Moonlight and dance for joy!

Not sure if all of those step are needed, but to be safe, try it step for step and let us know if it worked for you!

**Comment by Argon2000** [comment]
This is happening to me every day. Have tried serveral GFE versions and are currently on latest beta version.

For streaming to work, I have to reinstall GeForce drivers every day (sometimes several times per day).

In error log is same as OP (0x8109).
Though I also see this:
Failed to create FBC. Another Instance exists and concurrent capture is not supported.
Unloading FBC library
Initialization error
Farled to start: Failed to initialize video frame provider.

What other Instance can there be of FCB? I'm using remote desktop services like Splashtop, TeamViewer and LogMeIn. Can that be the cause?

**Comment by Argon2000** [comment]
Searching for this error I found this: https://plus.google.com/103771395491381994220/posts/D74Tc8TGbRB

And i too have KinoConsole server installed on my PC. Will remove it and report back with the results in case someone else stumbles upon this thread in the future.

**Comment by Argon2000** [comment]
Can confirm that i can stream today still. Over the internet even.

Will report back IF it stops working anytime soon.

**Comment by bczegeny** [comment]
@Argon2000 I CANNOT THANK YOU ENOUGH!!!!! Gamestream has not worked off and on at best or not at all over the last couple months. Could not figure out why, the second I uninstalled KinoConsole everything worked again!!!! Thank you so much!!
