### ISSUE TITLE
Handshake error -1 since lastest update 

### ISSUE THREAD

**Issue by tobiasdafirst** [moonlight-stream/moonlight-ios#206]
So since the latest update I have been unable stream any games when using a different network. It works fine on my home wifi, but at work or on 4g handshake fails every time. I have removed drivers and reinstalled with no change. I have checked my ports which are still open as always. I am completely out of ideas now. Thanks.

**Comment by cgutman** [comment]
Do you have UDP 47999 and UDP 48010 (not TCP) forwarded? The new Moonlight uses these ports now since GFE 2.11 and later require them.

**Comment by tobiasdafirst** [comment]
Oh I wasn't aware of this. I will look into it when I am home. Thanks for
the quick reply!

**Comment by tobiasdafirst** [comment]
Ok so I've tried this and no longer does it say hand shake failed. It gets
past that stage and goes to start and then says connection failed?

**Comment by ctpahhuk92** [comment]
I have sort of the same problem. When at home from one Wi-Fi PC and ipad, it works. But if, instead of Wi-Fi on the tablet I turn on lte (4g), writes: "could not connect to host". Can my router (airport extreme) to blame? 
Please, help me.

**Comment by Mimiste** [comment]
Do you have all the GFE ports correctly forwarded on your router ?
And you added a new host in Moonlight with your internet IP address ?

**Comment by ctpahhuk92** [comment]
Yes, all ports forwarding (which were in the instructions). IP has entered, but to no avail. Connect occurs only when both the computer and the tablet are on the same network Wi-Fi.

**Comment by cgutman** [comment]
The LTE streaming issue is fixed in v1.1
