### ISSUE TITLE
L3 & R3 Press and Hold using MFi

### ISSUE THREAD

**Issue by aieong19** [moonlight-stream/moonlight-ios#207]
The on-screen L3 & R3 are working fine beside one very specific instance and that is the press and hold action used for many FPS game for sprinting. 

With the MFi controller, if I press forward on the left stick and then tap and hold the on-screen L3 button, it seems like tapping the onscreen L3 cancels the left stick input, hence the game thinks I let go of the left stick before pressing the L3 button so any press and hold command of the left stick wouldn't work. 

I also can't tell if press and hold the on screen L3 even work to begin with. 

I donno if this is something that can be improve on the software end but if it can be improved it would vastly improve the streaming experience with MFi controller and make it near perfect. 

Thanks for the great app!

**Comment by dwaxemberg** [comment]
To press and hold the L3/R3 buttons you need to tap them and let go. The green highlight will stay lit indicating the button is pressed. You will have to tap the button again to unpress it.

**Comment by aieong19** [comment]
> To press and hold the L3/R3 buttons you need to tap them and let go. The green highlight will stay lit indicating the button is pressed. You will have to tap the button again to unpress it.

Thanks for the tip and sorry for the late reply.

That's what I thought how the screen button should work. However, I have tried it on a few games and I have yet to be able to use that to simulate the press and sprint function for many FPS or action games. The way I see it is that currently whenever I press the L3/LS button on screen it overrides my analog stick input so the client doesn't know I am still holding on the stick.

In other words, I think this is what the client is seeing in terms of input: 

1. Start walking in game => Analog stick forward, 
2. When I press L3 on screen => Analog stick released , L3 pressed and held
3. Right After I pressed L3 on screen => Analog Stick forward

For example, in Borderlands 2, I think I see my character shutter for a split second everytime I tap L3 on screen.

What further puzzles me is that if what you said is true and the green highlight on screen means the button is staying pressed, then I should still be able to sprint in say Borderlands 2. Reason being, I tried doing the same thing with a Xbox 360 controller running straight on PC. I started by only pressing LS and not moving the stick at all. And then with LS pressed I push on the stick and my character starts sprint right away.

Now if I try to do the same thing with the MFi by pressing the on screen L3 first and let it stay lit, then push on the left stick, my character only walk forward, not sprint, which led to believe the L3 is not truly pressed at all time.

**Comment by aieong19** [comment]
Quick update. 

The new app update, version 1.1.0, just released on iOS App Store seems to have fixed the click and hold on screen L3/R3 issue. 

So far, I only have a chance to try it on 1 game and it was Borderlands 2. I can now hold the left stick, press the screen L3,  and sprint!

Awesome guys!! Thanks so much.

**Comment by cgutman** [comment]
Fixed by https://github.com/moonlight-stream/moonlight-ios/commit/7b3d09944960b279e18b8395201d4e975f98a598
