### ISSUE TITLE
Support for non MFI controllers

### ISSUE THREAD

**Issue by sean256** [moonlight-stream/moonlight-ios#208]
MFI extended controllers are great but lack a few and sometimes critical buttons. Remapping locally doesn't always work either.

Some android controllers will pair with iOS and even work with some iOS games that implemented support for them, such as this one: http://www.amazon.com/Playpad-Android-Bluetooth-PC-Mac-Linux/dp/B0092ZEINO/

**Comment by dwaxemberg** [comment]
Although pairing a controller that has the extra buttons will work, it will not have the added functionality. The lack of buttons is a restriction imposed by the MFI gamepad specifications/protocol Apple created. There is no way to get the the input from buttons/axes not listed in the specification, even if the controller has it.
