### ISSUE TITLE
Cannot connect to host

### ISSUE THREAD

**Issue by Anon10W1z** [moonlight-stream/moonlight-ios#209]
First off, my PC doesn't show up automatically in Moonlight. Secondly, when I manually add its IP address, it says "Could not connect to host". I've tried this locally as well. I tried removing Chrome Remote Desktop to no avail. I'm running a GTX 750 Ti, an i3 3250, and GeForce Experience 2.5.14.5. I've also DMZ'ed my PC's IP address, so the ports should be open, I assume?

**Comment by cgutman** [comment]
I'd recommend updating to the latest version of GeForce Experience 2.5 is pretty old. See if a more recent one solves your problem.

**Comment by freds72** [comment]
Same here, tried GFE v2.9.1.35, 2.11.2.46 and 2.11.2.65 to no avail.
Over wireless home connection, firewall off (doesn't matter) the app is no longer working:
- not detecting hosts automatically
- unable to connect, report error: could not connect to host

**Comment by cgutman** [comment]
What firewall/AV software? Can you check if the NVIDIA Streamer Service is running on your PC? Some people are having issues where it crashes after a few minutes.
