### ISSUE TITLE
incorrect PIN

### ISSUE THREAD

**Issue by encor50** [moonlight-stream/moonlight-ios#210]
after update GFE to 2.11.2.49 pin is always incorrect i did try 10 times and im sure its right

**Comment by cgutman** [comment]
Moonlight will need to be updated to support the new GFE version.

**Comment by Sparcks** [comment]
I have the same problem. When can we expect the next update to come?

**Comment by Gustovier** [comment]
Same issue. Hope an update comes soon

**Comment by cgutman** [comment]
A build with support for the latest GFE update has been submitted to Apple for (expedited) review.

**Comment by cgutman** [comment]
Apple just approved the update. It's live now.
