### ISSUE TITLE
RTSP handshake failed with error 404

### ISSUE THREAD

**Issue by Dxy00** [moonlight-stream/moonlight-ios#211]
I got an error using ios Moonlight Game Streaming:
Connection Failed RSTP handshake failed with error 404

I'm using:
GeForce Game Ready Driver Version 364.72
GeForce Experience Version 2.11.2.55
iOS version 9.2.1(13D15)
Moonlight Version 1.0.3
All Firewall shutdown

anyone get solution or suggestion?

PS：No such problem while using android moonlight -stream version under the same circumstance

**Comment by Mimiste** [comment]
The same since today... Maybe it's related to the recent Geforce experience update ?

**Comment by cgutman** [comment]
It's related to the GeForce Experience update. It's fixed in the latest code. We're trying to get an expedited review from Apple.

**Comment by cgutman** [comment]
The update is now live on the App Store.
