### ISSUE TITLE
My Games Wont Show

### ISSUE THREAD

**Issue by thetypicalgeek** [moonlight-stream/moonlight-ios#212]
So i have two issues,
1.When i first got the app i paired my IPad (4th Gen.) it told me to punch in the code onto the computer but it kept saying invaild code,But I fixed it so :/ 
2.It wont show my games!!!!!!!,so after i fixed that glitch ^^^^ i was going to stream some games but they wont show up,almost the only game i have is gta v :/

**Comment by dwaxemberg** [comment]
Open GeForce Experience on your PC and go to the Games tab. Select "Scan for games". If that option isn't there, then there should be a game list on the left. In which case you should click the "Refresh game list" button. 

If your game is still not detected, then that means Nvidia does not consider it "GameStream Ready". To get around this, use Steam (http://steampowered.com) and add all your games to your Steam Library. GeForce experience will see Steam as a compatible game and after launching it though Moonlight, you will be able to launch any game you have added to your Steam Library.

Please reopen this ticket if you still have issues.

**Comment by intdel** [comment]
I have the same issue. I have to add every game manually. But if I use the official app on my Shield it detects all games. The moonlight app on the Shield only detects Steam as well.
