### ISSUE TITLE
Cannot Connect over Internet

### ISSUE THREAD

**Issue by patx5x5x4** [moonlight-stream/moonlight-ios#217]
So I've tried forwarding the ports (the one on gamestream forum and the setup guide on moonlight page) through my router and everything seems fine but once I try to connect through my phone, it says "could not connect to host". Is it my router? I also tried completely turning off the firewall on both the computer and the router but nothing works. It works completely fine locally so it's not that. Here is my port forward settings. 
![image](https://cloud.githubusercontent.com/assets/11155102/14547847/bbf8ae1a-027f-11e6-84ee-36aaded5bd75.png)

**Comment by Mimiste** [comment]
Did you forwarded all these ports ?

TCP 35043, 47984, 47989, 47995, 47996, 48010
UDP 47998, 47999, 48000, 48010

If i look at your screenshot, it seems to be missing some

**Comment by patx5x5x4** [comment]
Yeah I have all the ports. It's a range so I put ports like 47995 and 47996 together but I'll separate it and retake the screenshot.

**Comment by patx5x5x4** [comment]
So I separated everything but i still cant connect here is the screenshot.
![image](https://cloud.githubusercontent.com/assets/11155102/14578578/9b15c298-0359-11e6-9767-d4a2ccbb38dc.png)

**Comment by Mimiste** [comment]
well, if you forwarded all the ports, used your IP and be sure there is no firewall problems, i dont really know why it's not working. 
Did you tried with another version of moonlight ? The PC version for exemple

**Comment by drsgfire** [comment]
I know this is old but were you running Windows firewall by chance? I use WFC by binsoft and it shows all the connection required for streaming locally. I had problems with WF and I completely disabled it and it worked.

**Comment by patx5x5x4** [comment]
Yeah i have tried to completely turn of my windows firewall and it didn't work. Also, it worked fine locally with a local ipv4 but over the internet did not work.
