### ISSUE TITLE
Simple mode controller

### ISSUE THREAD

**Issue by Mimiste** [moonlight-stream/moonlight-ios#218]
What is actually the point of using the "simple" mode ?
It only display L2 R2, L3 R3, select and start... 
Is this a mistake or is there really games that only use theses buttons ?

**Comment by madwedge** [comment]
This is probably for certain controllers that only have one shoulder button each side, instead of two. You can't play a game just with the buttons you listed. You'd need a controller, and the on screen buttons give you the remaining options.

**Comment by Mimiste** [comment]
Probably.. But i dont think it's really usable. How can you play on a controller (with both hands) and sometime touch the screen ? That's weird

On my fork, i changed the button configuration on this mode. You can chose between a pad or a stick on the left and it displays ABXY buttons on the right.
But i dont think i'll do a pull request if this mode is intentionally done like this.

**Comment by apocolipse** [comment]
MFI controllers don't have L3/R3 Select/Start, some may not have L2/R2 either.  Simple mode fills that gap.

**Comment by ajmi982** [comment]
Hey Mimiste could you share your fork or share how you go about changing the button configuration?  I want to play emulators through GFE on Moonlight and just need a simple d-pad and ABXY (maybe add a L and R trigger) but would really like to see more customization of the on screen controls.

BTW, not jailbroken so i guess i would need this in the IOS submitted official build :(

**Comment by Mimiste** [comment]
I dont have it anymore on my fork, i focused on keyboard support. But if you want to change button configuration it's pretty simple, you just have to modify that file : 

[OnScreenControls.m](https://github.com/moonlight-stream/moonlight-ios/blob/master/Limelight/Input/OnScreenControls.m)

And modify the "updateControls" function by hiding or showing buttons as you like..

You dont need to be jailbroken to install an app from xcode. You just need to have a developer account.

With a free developer account, you can install an app for one week then you need to re install it.
If you have a paid developer account there is no limitations
