### ISSUE TITLE
Iphone pairing failed

### ISSUE THREAD

**Issue by g-invictus** [moonlight-stream/moonlight-ios#219]
I have Moonlight installed on my iPhone 6S when attempt to pair to my pc after entering the PIN on my PC I get "Pairing Failed". i just connected from iphone 5, but i can't connect my iphone 6s, why?

iOS 9.3

**Comment by BertTank** [comment]
I had something similar with my iPhone 6 Plus (which could be paired successfully) and [a moonlight port for AppleTV](https://github.com/kevsmithpublic/moonlight-ios) which could not be paired. I managed to solve it with an older version of the Geforce Experience, which you can [download from here](http://us.download.nvidia.com/GFE/GFEClient/2.4.5.57/GeForce_Experience_v2.4.5.57.exe). Might be worth a try.

**Comment by g-invictus** [comment]
iphone 6 work, 6s-doesn't

**Comment by cgutman** [comment]
That's strange. Have you tried uninstalling and reinstalling the Moonlight app from the App Store on your 6S?

**Comment by g-invictus** [comment]
Very strange. I can pair 6s to other Laptop but  can't pair 6s to my PC. I reinstalled Geforce Experiance and moonlight a lot of times, installed oldest version of GE, but still can't pair my 6s to my PC (only my, other phones pired successfully) i have no idea how decide this problem. I hope someone can help me

**Comment by jamesfmackenzie** [comment]
I have this same issue. Unsure what to do to get the pairing working.
