### ISSUE TITLE
iOS - Cannot start apps while on wifi, but can over carrier 

### ISSUE THREAD

**Issue by Brofesional** [moonlight-stream/moonlight-ios#223]
My home, work, and Xfinity Wifi networks do not allow me to start apps, but as soon as I disable Wifi and try it while on Verizon's network apps start up right away.

Strange thing is I can connect to my home computer and see all of my installed apps while on Wifi and the computer shows online.

Anyone else experience anything similar?

**Comment by madwedge** [comment]
Have you forward all the required ports in your router?
