### ISSUE TITLE
Not launching app

### ISSUE THREAD

**Issue by zekromroar** [moonlight-stream/moonlight-ios#225]
Ok, so when i put the PIN into GFE, it detects it and all is well, until I launch a game, when it pops up "Connection Failed Failed to launch app". I have the latest version of GFE and I have every port-forwarded, but it has ceased to work on WI-FI or Cellular Data. Any help is appreciated.

**Comment by zekromroar** [comment]
Just to clarify, it doesn't work on LAN

**Comment by cgutman** [comment]
Can you try reinstalling GeForce Experience?

**Comment by zekromroar** [comment]
I have, and I have rolled back to about three different versions without success.

**Comment by bhendo** [comment]
I am having the exact same issue. The only information I can find are the following entries in nssCurrent.log

```
#0(W)[2016-05-17 14:17:35,862]{000020DC} ClientRequestDispatcher message has no data.
#1(I)[2016-05-17 14:17:35,862]{00000E94} Turning on Proxy
#2(I)[2016-05-17 14:17:35,862]{00000E80} Roaming is ON. Enable port forwarding
#3(E)[2016-05-17 14:17:35,866]{000020DC} Request with id 5355 can't be found.
#4(E)[2016-05-17 14:17:35,866]{000020DC} Request with id 5356 can't be found.
#5(W)[2016-05-17 14:17:37,529]{000020DC} ClientRequestDispatcher message has no data.
#6(I)[2016-05-17 14:17:37,529]{00000E80} Roaming is ON. Enable port forwarding
#7(I)[2016-05-17 14:17:37,529]{00000E94} Turning on Proxy
#8(I)[2016-05-17 14:17:37,538]{00000E8C} NotificationReceived: (connectionId: 6eaacc50264ee023 , data:{
"CurrentClient" : "0",
"CurrentGame" : "78976",
"GameListId" : "d8631db16e6aa3ae100c069a45cdfc33",
"Notification" : "SERVER_STATE_CHANGED",
"ServerState" : "MJOLNIR_STATE_SERVER_LAUNCHING"
} , broadcastExceptForConnectionId:1)
#9(I)[2016-05-17 14:17:37,543]{00000E90} NotificationReceived: (connectionId: 6eaacc50264ee023 , data:{
"CurrentClient" : "1",
"CurrentGame" : "78976",
"GameListId" : "d8631db16e6aa3ae100c069a45cdfc33",
"Notification" : "SERVER_STATE_CHANGED",
"PairStatus" : "0",
"ServerState" : "MJOLNIR_STATE_SERVER_LAUNCHING"
} , broadcastExceptForConnectionId:0)
```

But I honestly cannot tell if they are relevant or not.

**Comment by cgutman** [comment]
Can you zip the contents of your 'C:\ProgramData\NVIDIA Corporation' folder and post a link to it?

Also please make sure you don't have any software known to be incompatible with GameStream: https://github.com/moonlight-stream/moonlight-android/wiki/Troubleshooting

**Comment by bhendo** [comment]
Edit: I reverted back to GFE 2.2.2 and game streaming works again. The issue seems to be with the latest version of GFE

**Comment by zekromroar** [comment]
I will post it zipped here when i get home, and i will try to roll back to 2.2.2, because i havent tried that version yet

**Comment by zekromroar** [comment]
I don't know if this is what you were looking for, but here it is. 
[NVIDIA Corporation.zip](https://github.com/moonlight-stream/moonlight-ios/files/269069/NVIDIA.Corporation.zip)

**Comment by zekromroar** [comment]
I tried going to 2.2.2, now it will give me the same error, but sometimes go to the handshake error with error code -1

**Comment by cgutman** [comment]
@zekromroar The issue is that GFE is unable to set your display resolution to match the stream resolution. Do you have a display connected to your PC? If so, does it support the 1280x720 resolution?

#9(E)[2016-05-17 16:47:33,153]{000024D8} Mode Selection: Failed to launch, server does not support requested mode (1280x720@60Hz)
#0(E)[2016-05-17 16:47:33,153]{00001454} Creating Resources for Launch Failed.
#1(E)[2016-05-17 16:47:33,153]{00001454} Failed to app launch (status: 536). Resetting server state to AVAILABLE

**Comment by zekromroar** [comment]
What should i set the display to? Its a freshly built pc, so i makeshift hooked it up to a smart tv.

**Comment by zekromroar** [comment]
@cgutman your a genius! it worked. seemed like such a minor detail lol :)
