### ISSUE TITLE
name resolution failed with error 8

### ISSUE THREAD

**Issue by madwedge** [moonlight-stream/moonlight-ios#228]
What does the above error mean. I'm trying to access my PC remotely without the need of my VPN so I've started again. I've added my DNS name and have forwarded the 6 required ports on my router. Am now getting this error. 

Is there a list of error codes somewhere? I did have an error -1 too but can't replicate it now.

**Comment by cgutman** [comment]
That's a weird one. In a terminal/command-prompt on your PC can you try: nslookup <your DNS name>

and tell me what that says.

**Comment by madwedge** [comment]
Hi, I've just used Teamviewer to access my PC at home (I'm at work) and run the command. It says the following:
Server: dlinkrouter
Address: 192.168.100.1

Non-authoritative answer:
Name:  [my DNS name here{
Address:  127.42.0.0

**Comment by madwedge** [comment]
Ignore the subject title as I have had this error 8 again. All I get remotely, without my VPN, is error -1. Know what this means? Thanks.

**Comment by cgutman** [comment]
What happens if you add your PC using the external IP address rather than the DNS name?

**Comment by madwedge** [comment]
I never thought to try that! Removed my connection. Re-added using my external IP and it works! Didn't think it would be the DNS causing the issue. 

Do you know why this is the case or any recommendations? Using a DNS name is handy, but not essential. Many thanks for the help.

**Comment by cgutman** [comment]
I was finally able to reproduce this by connecting by DNS name over an LTE tethering connection and fixed the issue.
