### ISSUE TITLE
[Request] Smart Keyboard Support

### ISSUE THREAD

**Issue by jeffy777** [moonlight-stream/moonlight-ios#229]
I know there's already a request for virtual touchscreen keyboards, but would it be possible to add support for hardware keyboards? I have the smart keyboard for the iPad Pro and it works with VNC for instance, so it'd be awesome for moonlight gaming too. Keep up the good work!

**Comment by cgutman** [comment]
Fixed by https://github.com/moonlight-stream/moonlight-ios/commit/76ab786e94b6949729b51043409660a102869543
