### ISSUE TITLE
iOS - Audio/Control Input works for Valkyria Chronicles, but does not display game on device

### ISSUE THREAD

**Issue by Jorel29** [moonlight-stream/moonlight-ios#230]
As said in the title, when I launch Valkyria Chronicles (Local Host) the game will launch, on the computer, and on the device I can control what happens on the computer, but the device will not display the game, only the controller overlay. Is there any way to fix this?

**Comment by cgutman** [comment]
The issue is only with this game or with all games?

**Comment by Jorel29** [comment]
So far it is only this game of the all I've tried (even games that don't support controller will show screen). In total I've attempted 7 games: Strike Suit Zero, World of Tanks, Hyperdimension Neptunia Re;Birth V3, Mirrors Edge, Sunriser: Mask of Arcadius, Valkyria Chronicles, One Thousand Lies

**Comment by M0rr1s0n** [comment]
I guess it is a general Gamestream issue with this game, because I experience the same only with Valkyria Chronicles while using Moonlight Android and official Gamestream with Nvidia Shield!
