### ISSUE TITLE
RTSP handshake failed with error -1

### ISSUE THREAD

**Issue by momostein** [moonlight-stream/moonlight-ios#231]
The game on my pc starts normally,
then it tries to do the handshake and then i get the error

Win 10 using nvidia Geforce 2.11.3.5

**Comment by drsgfire** [comment]
I got this issue today but under these parameters.

I was originally streaming at 720p with no problem. I closed the game and decided to try it in 1080p @ 60hz. Launched the game and I got this error. I tried adjusting the bandwidth down to 10mbps and it still did this.

**Comment by drsgfire** [comment]
So I think I figured out why I got this error. I had kinoVR server installed on my PC and it was running its service. As soon as I killed the server and tried to connect with moonlight it is working great. Even in 1080p.

**Comment by MacmanPo94** [comment]
Any other suggestions? I had this same problem and uninstalled KinoConsole. Still am getting the same error.

**Comment by melgu** [comment]
I have the same error. I never had KinoVR or anything like that installed.
