### ISSUE TITLE
[Feature Request] No audio routing to iOS device

### ISSUE THREAD

**Issue by drsgfire** [moonlight-stream/moonlight-ios#232]
For VR setups it would be nice to use my wireless headset at my pc instead of having the audio stream to my iPhone that is installed in the VR headset. This would shave off some data to the stream also.

**Comment by drsgfire** [comment]
You know what; After I just posted this I think this might be something that NVIDIA would have to add to GFE being that it's the server software. Unless you have magical powers and whatnot :)

**Comment by cgutman** [comment]
I must have magical powers then, because this is doable ;)

Actually, some other Moonlight clients (PC and Android) have this feature, though the audio plays from both devices. People seem to use it for VR and local co-op.

**Comment by drsgfire** [comment]
Hey that's awesome. Is that hard to implement? We talking about a few days, weeks... months?
