### ISSUE TITLE
Can't connect over Internet.

### ISSUE THREAD

**Issue by JCAUSER222** [moonlight-stream/moonlight-ios#235]
I've followed all the port forwarding instructions and connect guide yet I can't get it to work over my phones 4g but in home works like a dream

**Comment by patx5x5x4** [comment]
I have had the same problem and i finally fixed it. First if you have a modem and a router then make sure that the modem is in bridge mode and make sure when you port forward with the router you put both UDP and TCP. After this it worked very nicely. If this doesn't work try turning of windows firewall.
