### ISSUE TITLE
Control stream establishment failed with error -1

### ISSUE THREAD

**Issue by redwing646** [moonlight-stream/moonlight-ios#236]
Works fine when on the same network, but when on a different network it shows the status as online and allows me to see my games, however when starting one it starts the game up but can never connect the controller giving "Control stream establishment failed with error -1" as the error code(I have portforwarded all the ports). I have a gtx760 and have done a fresh install of GFE and the drivers with no luck.

**Comment by cgutman** [comment]
That error probably means your port forwarding for UDP 47999 is missing or not correct.

**Comment by redwing646** [comment]
That was the problem, but now I have ran into another one with that being the screen being black on the phone. The controls still work on the computer, but there is no display on the phone.

**Comment by redwing646** [comment]
Never mind I found the problem to that issue as well with UDP 47998 not being open. Now it is working perfectly thank you for the help

**Comment by roxasofthedark** [comment]
how did you get UDP 47999 to start working? I'm having that issue now. I have it in my portforwards and it is correct
![image](https://user-images.githubusercontent.com/68814106/88480179-68a98800-cf22-11ea-92ca-f2f0fff06179.png)

**Comment by roxasofthedark** [comment]
how did you fix the UDP 47999 im having that issue now and its in my list and is not working.
![image](https://user-images.githubusercontent.com/68814106/88480214-a1496180-cf22-11ea-9bd0-77eaafc68ed9.png)

**Comment by kristof47** [comment]
How did you solve it?
the 47999 udb port problem?

**Comment by kristof47** [comment]
How did you fix the 47999 UDP port problem?
