### ISSUE TITLE
Pairing Failed

### ISSUE THREAD

**Issue by killnine** [moonlight-stream/moonlight-ios#238]
Hey all,

I've rebuilt moonlight from @kevsmithpublic's fork so that it'll run on AppleTV. It shows up just fine and gets to the point of pairing but no matter what code I put in, it never pairs correctly. I've tried maybe a dozen times.

Perhaps this build has an older version of some binaries that deal with the pairing? 

Here's some details:

* Geforce Experience v2.11.4.0
* Windows 10 Build 10586
* TvOS 9.2.2
* Built on Xcode 7 (whatever latest is...)
* Works fine on my iPhone 6S with latest AppStore version...

Any ideas? Some people have said updating to beta version of GFE helps, but doesn't seem conclusive.

**Comment by bendodson** [comment]
@killnine I had the same issue. After a bit of hacking around, I've managed to rebuild the fork with the latest code from the main moonlight project so that it works correctly with the latest versions of GFE (I'm using the latest 3.0 beta). You can grab the code at https://github.com/bendodson/moonlight-tvos

**Comment by killnine** [comment]
@bendodson Got around to rebuilding and, yep, it works perfectly now! Very nice!

Pairing with a bluetooth keyboard didn't seem to do much besides open up games in steam. Are most games playable with a Mifi controller?

**Comment by bendodson** [comment]
@killnine not sure how well keyboards work with moonlight so not sure on that. Any game that supports controllers should work with MFI controller over moonlight - even when at my PC I tend to use an Xbox One controller for most games.
