### ISSUE TITLE
error

### ISSUE THREAD

**Issue by GeekYW** [moonlight-stream/moonlight-ios#242]
clang: error: no such file or directory: '/Users/yuw/Documents/gitHub项目/moonlight-ios/moonlight-common/moonlight-common-c/src/Connection.c'

**Comment by kgellci** [comment]
The moonlight repo is pointing to another repo for the moonlight-common-c files.  The moonlight-common-c repo also points to another repo for files it needs.  To clone all of the repos properly, do something like this:

`git clone --recursive https://github.com/moonlight-stream/moonlight-ios.git`

If you are downloading the source you will need to go to each repo, download the source from each one and then copy the files into the corresponding directories.  Here are the repos you need if downloading the source:

https://github.com/moonlight-stream/moonlight-common-c/tree/8d2dccf4ca5614814adcee49f68d87325036f3e2

https://github.com/cgutman/enet/tree/e33ca1dc47635882bfcadd192dbc54ea8584cbc5
