### ISSUE TITLE
tvOS Settings Gesture

### ISSUE THREAD

**Issue by killnine** [moonlight-stream/moonlight-ios#243]
I'm running @bendodson's release (https://github.com/bendodson/moonlight-tvos) and noticed that there's no way (with neither the AppleTV controller, nor a Steelseries Nimbus) that I can open the settings tab.

I understand that the tvOS fork isn't an official one because of the issues with the SDK hack.

However, from just a UX perspective, how would you suggest approaching support for the settings menu from within AppleTV? There don't appear to be the same swipe gestures that, say, an iPhone has. 

Thoughts?

**Comment by bendodson** [comment]
@killnine I've enabled issues on my fork now so probably best for you to recreate this issue there and I can look into it (as obviously unlikely to get any help on this project which is solely iOS based at the moment due to the restrictions in the tvOS AVFoundation frameworks)

**Comment by killnine** [comment]
Perfect, I've closed this issue and opened another on your fork. Thanks
