### ISSUE TITLE
Use wireless PC controllers while streaming to iOS device without disconnecting 

### ISSUE THREAD

**Issue by hk0i** [moonlight-stream/moonlight-ios#245]
My use case is that I want to use my xbox 360 controller for Windows or the new Xbox one s controller on Windows and simply stream audio video to the device. 

In my scenario the Windows wireless controller is in range of the computer and works fine but once moonlight connects to the pc I get a black screen flicker. Once the screen comes back the controller input is seized by moonlight app and I can no longer use the game pad to control. It's like the game pad is disconnected at that point and for my case the game I'm playing will not detect controllers that are turned on or plugged in after the game has already started.

**Comment by fschulze** [comment]
For the games I tried it works for me. Did you try this: https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#using-a-gamepad-connected-to-the-pc-instead-of-the-streaming-device

**Comment by hk0i** [comment]
I'll give that a shot next time I try it out. It also might have been the game I was playing, I know for that particular game (Final Fantasy III Steam Edition) if you disconnect the controller mid-game it won't reconnect until you restart the game. I'll let you know if that workaround solves the issue.

**Comment by bdhipps** [comment]
Workaround - try www.virtualhere.com. 
You can just plug a XBOX controller for windows adapter into a raspberry pi and it becomes a mobile extender for your controller.
