### ISSUE TITLE
Host settings

### ISSUE THREAD

**Issue by michaelgoodwin** [moonlight-stream/moonlight-ios#247]
As per those settings that are found in the android version.
- Optimise game settings
- Play audio on PC

In particular play audio on PC, gamestream no longer just mutes the host at system level it now must be routing the audio stream elsewhere. I have a use case for this and I haven't found a good alternative to live stream to an iPad.

**Comment by Argon2000** [comment]
I second this (keep sound on host). I mainly use Moonlight to be able to use my MFI controllers as X360 controllers for my PC. And it’s a real hassle every time to get sound.

I have to start the game from the computer, connect with moonlight, alt-tab out and mixture with sound settings (change standard device and disable NVIDIA output). Then hopefully it works, but sometimes I need to repeat the steps. 

Kinoni streamer has support for this but it does not support multiple controllers connected.

Also some other moonlight versions have this (think atleast android and PC versions?).
