### ISSUE TITLE
Hardware bluetooth keyboards and gamepads support

### ISSUE THREAD

**Issue by thealex626** [moonlight-stream/moonlight-ios#251]
Hi there! 
Nice app, really cool and promising. But gamepad-supported games are unplayable with current onscreen controls, and all games with keyboard/mouse support only are completely unplayable. The most surprising thing is that bluetooth keyboards are not recognized by this app. Same thing with Smart keyboard on iPad Pro and with all bluetooth controllers/gamepads. In my opinion, all onscreen controls are terrible, but the current version built into this app is the most terrible thing. It's non-customizable and there's no way to change layout, add more keys or hide unused keys. But the worst thing is virtual analog joysticks. Try to play Skyrim or some FPS for a couple of minutes and you will agree with me. 

That's why I'm seriously requesting a support for native keyboards\controllers in iOS.

**Comment by Mimiste** [comment]
Yes, keyboard support is a must have... A lot of games are unplayable because of this.

**Comment by Mimiste** [comment]
I'm actually working on implementing the keyboard support. At least, it will support the virtual ios keyboard for now.

**Comment by bdhipps** [comment]
Workaround - try www.virtualhere.com. 
You can just plug a bluetooth adapter into a raspberry pi and it becomes a mobile extender for any devices you want to connect to the host PC. If you do that though you have to delete/rename rxinputcontroller.dll so GFE will use the "locally" connected USB device.

**Comment by jeffy777** [comment]
Where is rxinputcontroller.dll located?
