### ISSUE TITLE
Cannot Pair with new GeForce 3.0

### ISSUE THREAD

**Issue by ezmatty** [moonlight-stream/moonlight-ios#252]
GeForce is in icon tray but doesn't generate a pin area to put in pin code to pair with Moonlight. I have read that GeForce has changed how to pair now by logging into your GeForce or Google account. Will this be something added at a later date for Moonlight and am I out of luck to pair now until it is implemented?

**Comment by cgutman** [comment]
PIN pairing is still available. You should follow this guide if you can't get the dialog to show up: https://github.com/moonlight-stream/moonlight-docs/wiki/Troubleshooting#pairing-dialog-wont-show-up-on-pc
