### ISSUE TITLE
[Feature Request] On-Screen Controls Customization

### ISSUE THREAD

**Issue by ajmi982** [moonlight-stream/moonlight-ios#256]
Hi,

I'm looking to use Moonlight combined with GFE for emulation.  Right now the on screen controller options (FULL) work fine but they take up the entire screen and half the buttons I would never use when playing NES or SNES game for example.

My request would be for more on screen control options or simple customization allowing your to remove buttons you dont need in order to free up screen real estate.

Thanks.

**Comment by sevansup** [comment]
PLEASE add this! Especially with the recent Steam updates that allow you to customize controls further, it would be REALLY nice to be able to turn off certain buttons and only have select or L3 for example on screen.
