### ISSUE TITLE
[Feature request] - Bluetooth keyboard support for streaming desktop

### ISSUE THREAD

**Issue by hayden-robins** [moonlight-stream/moonlight-ios#257]
Anyone interested in this feature:
Moonlight with Bluetooth keyboard support when streaming the desktop operating system to an iOS device. Eg mstsc. 

The low latency + BT keyboard support would make a compelling remote desktop solution when compared to any other alternatives. 

May not have the same requirements for keyboard input as games do?

**Comment by jeffy777** [comment]
Definitely interested in this too.

**Comment by Haans249** [comment]
Actually, consistent with Android devices where they have keyboard and mouse support, It would be amazing to have the same thing for an iOS device.

If you have your iPhone/iPad jailbroken you can download BT Mouse and Trackpad and have a mouse and keyboard on the iPad.  If we could use that for the moonlight (stream the keyboard/mouse movements) into the game that would be really great.

Thanks!

**Comment by AJBats** [comment]
I am **deeply** interested in keyboard support for IOS. I have an iPad Pro with the Pro keyboard, and it's frustrating to have to switch to my VNC client app just to type something in.

I will donate $100 dollars if you guys get this feature in. I'm dead serious.
