### ISSUE TITLE
Connection Failed Error [RTSP Handshake -1]

### ISSUE THREAD

**Issue by joefz2** [moonlight-stream/moonlight-ios#259]
I'm getting this error when using the iOS app on my iPhone 7 Plus using cellular data since I'm out of the house. GFE is fully updated and the ports are activated. What is causing the issue?

**Comment by jeffy777** [comment]
Does it work on wifi?

**Comment by joefz2** [comment]
It does not work on wifi either. 
It obviously work on the local wifi that's in my home but anywhere else it doesn't.

**Comment by cgutman** [comment]
An RTSP error usually means you've either forgotten to forward the UDP ports or accidentally forwarded them as TCP instead of UDP (a common mistake).

https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#streaming-over-the-internet

**Comment by joefz2** [comment]
You're a genius! I had the 48010 port as TCP instead of UDP. Works now!

**Comment by FlamingJampack** [comment]
I'm still having the same issue but i even put it as UDP and still have the problem

**Comment by Zeldon567** [comment]
Make sure you're using the right ipv6 address. Type in google "What is my ip" and you should be able to find it easily enough.

**Comment by everettkyle** [comment]
So I configured my ports correctly and my pc connects but I keep getting RTSP handshake error as well 
and its still not working

**Comment by everettkyle** [comment]
It works however whenever im directly on the network
