### ISSUE TITLE
RTSP Handshake failed with error -1

### ISSUE THREAD

**Issue by melgu** [moonlight-stream/moonlight-ios#260]
No matter which resolution I choose or if the firewall is active or not. I always get this error.
Tried on an iPhone 6s Plus and iPad 4. (Latest GeForce Experience)

**Comment by melgu** [comment]
Correction: The iPad is stuck at "Starting App" although the program has started already (it even shows the Play-Symbol inside Moonlight).

**Comment by smonkboi** [comment]
do you have all of these ports open? 
![image](https://cloud.githubusercontent.com/assets/26816871/24559564/2ef4cf2e-160d-11e7-9f9c-fb90bac8db2d.png)

**Comment by melgu** [comment]
I have non closed.

**Comment by FlamingJampack** [comment]
I have all the same ports as you @smonkboi but it still does not work.

**Comment by smonkboi** [comment]
@flamingjampack lol mine don't work anymore either n nothing changed
