### ISSUE TITLE
Black Display with Sound after GE 3.2.0.96

### ISSUE THREAD

**Issue by hippiesrlame** [moonlight-stream/moonlight-ios#261]
I just upgraded to the latest geforce experience client and am encountering an issue where no display is shown through the moonlight client. The controls and sound are working fine, just not the display. I tried all the suggestions listed in the troubleshooting FAQ for this issue without any luck. Did nvidia break the moonlight app with this latest version? It was working fine before I upgraded to iOS 10.2 and installed the latest nvidia software today.

Windows 10 64-bit Anniversary Edition
iOS 10.2

**Comment by cgutman** [comment]
The fix is already pushed. We just need to get another build to Apple for testing.

**Comment by hippiesrlame** [comment]
Awesome, appreciate the quick reply.

**Comment by hippiesrlame** [comment]
Confirmed latest build resolves this for me...closing issue.
