### ISSUE TITLE
Steam Update to make controllers customizable

### ISSUE THREAD

**Issue by RidleyDeckard** [moonlight-stream/moonlight-ios#264]
I've just downloaded the new Steam client Beta that allows you to fully customise controllers in the same way you can with PS4 and Steam Controllers. However, as Moonlight seems to simulate 4 controllers, whenever you try to move left or right in the interface once you've set it up and each movement comes through 4 times, making almost impossible to use. You have to go back in and turn the customization option off again.
I know the beta only rolled out at the end of last week, but is this something you are going to look at? As using the Moonlight IOS with a Gamevice on an iPad is awesome, but if I could customize the controllers it would be even better.

**Comment by cgutman** [comment]
I can't get this issue to happen on the Jan 10 Steam Beta update. Can you try again and see if it still happens after you update? 

If so, can you tell me which controller configuration checkboxes you have checked?

**Comment by RidleyDeckard** [comment]
![img_0012](https://cloud.githubusercontent.com/assets/10867732/21852173/f53c6116-d809-11e6-9d64-cb1e8695deb1.PNG)
It works fine until you go into settings and then controller settings and have the attached screen, you can see it thinks 4 are attached.  This isn't a problem until you select the Generic Gamepad Configuration Support so you can customise you controllers, when you restart it each input seems to be repeat four times. So if you use the touch screen to you to your library and then scroll down it jumps 4 rows at a time.

**Comment by nileplumb** [comment]
Yup having this issue with PS Vita moonlight also. https://github.com/xyzz/vita-moonlight/issues/81

**Comment by nileplumb** [comment]
I'm noticing latest geforce and latest steam beta appears to have fixed this currently

GeForce 3.4.0.70
Driver 378.66
Steam Beta Feb 22
