### ISSUE TITLE
Connection Failure

### ISSUE THREAD

**Issue by Fenrir426** [moonlight-stream/moonlight-ios#267]
I have the following ports opened.
TCP: 35043, 47991, 47995, 47996, 47989, 47984, 48010
UDP: 7, 9, 47999, 47992, 47998, 47989, 48000
In accordance with GeForce and the following other ports as instructed.
TCP 47894, 47989
UDP 47998, 47999, 48000, 48010
However, I receive the following Connection Failed message.
Connection Failed
RTSP handshake failed with error -1

I have a HDMI headless port in one of my HDMI ports and a HDMI cord in another HDMI port that is going into a splitter into my T.V. and a regular cord going into my computer screen.

I tried them as individuals and still some error message.

I am completely baffled on what to do besides restarting everything from scratch.

**Comment by smonkboi** [comment]
these are the ports i have and it works. i had to add 48010 to udp, which was my issue. 
![image](https://cloud.githubusercontent.com/assets/26816871/24559526/07ec3638-160d-11e7-97f1-b225be5396f0.png)
