### ISSUE TITLE
Moonlight not fullscreen on ipad mini

### ISSUE THREAD

**Issue by ghost** [moonlight-stream/moonlight-ios#269]
Big black bars on top and bottom of iPad mini.

![img_0038](https://cloud.githubusercontent.com/assets/26333760/23812051/d59c1804-05a6-11e7-89b7-ec7a6342cd59.JPG)

**Comment by game-player** [comment]
Current xcode issue

**Comment by momostein** [comment]
Isn't this because the aspect ratio of the pc's monitor (probably 16:9) is different than your ipad (probably 4:3)? i guess the only way to solve it is to change your pc's aspect ratio to your ipad's ratio, but then your monitor will have black bars on the left and right...

**Comment by dariokan82** [comment]
Any luck with that? I tried with changing the resolution but it still reverted to 16:9 ratio

**Comment by ajmi982** [comment]
Been a rewueat since the day moonlight came out. Don't see this ever being properly fixed :(

Seems the only solution would be to get a 4:3 monitor lol

**Comment by dariokan82** [comment]
Nope, tried that by changing aspect ratio - Moonlight defaults the request to 720 or 1080 which is 16:9. It would be nice to add the option for a 4:3 ratio :)

**Comment by momostein** [comment]
Have you tried changeing the ingame settings?

**Comment by dariokan82** [comment]
Yes. It will stretch the image as the computer will recognise the iPad Mini as a 16:9 monitor.

**Comment by ajmi982** [comment]
Makes no difference. The issue is moonlight. It forces 16:9

**Comment by jpecih** [comment]
Has anyone tested a no-monitor dongle or an EDID emulator and configured 4:3 resolution to check if fits?

**Comment by somnolentsurfer** [comment]
Anyone able to give any kind of idea whether this is something that would be fixable, or any timescale for getting it done? Adding support for native iPad 4:3 resolutions would make streamed games much more playable.
