### ISSUE TITLE
DualShock 4 or Xbox controller without jailbreak

### ISSUE THREAD

**Issue by thealex626** [moonlight-stream/moonlight-ios#270]
Hello. Is there any way to connect the bluetooth controllers such as DS4 and Xbox/XOne controllers to Moonlight on iOS without jailbreaking the device? Is there any possible way to make it work, or is there any possible workarounds for that?

**Comment by xjrodzx** [comment]
Without jailbreak it is not possible. I personally use a SteelSeries Nimbus which is an MFi controller. Works great on my iOS devices.

**Comment by thealex626** [comment]
How much this controller is different from the regular Xbox One and DS4 controllers? Can we emulate the iOS-compatible controller using the normal DS4 controller?

**Comment by ajmi982** [comment]
No L3 or R3 with the nimbus though. So slight trade off. 

Sent from my iPhone. Please pardon any spelling or grammar mistakes. 

On Oct 2, 2017, at 12:48 PM, xjrodzx <notifications@github.com> wrote:

Without jailbreak it is not possible. I personally use a SteelSeries Nimbus which is an MFi controller. Works great on my iOS devices.

**Comment by thealex626** [comment]
I'm talking about a hardware emulation. Maybe it's possible to convert signals from DS4 into signals from Nimbus?

**Comment by gt2416** [comment]
If your thinking about a solution like how a universal remote can capture IR signals and learn them, this is not possible. 
This is not how any digital software nowadays works. If this was the case anything would be easily hackable and security would be non existent.
