### ISSUE TITLE
How do I turn off the Moonlight built-in controller completely (even mouse functionality)?  It overtakes my DS4 controller

### ISSUE THREAD

**Issue by deskora** [moonlight-stream/moonlight-ios#271]
Hi,

I'm using Moonlight on iOS 10.3.1, an iPad Air 2.  My computer is Win10 i7-3770k + GTX 1070.  My use case is that my DS4 controller is directly connected via BT and takes advantage of Steam's built-in DS4 support to play videogames and the iPad will simply playback the audio/video.  I do not want to use Moonlight's ability to act as a mouse with the touchscreen because I think it's overtaking and disabling my DS4.

When I do not use Moonlight, I can play games just fine with my DS4.  An example is the new game Prey, see how the Playstation button prompts show up?

![20170506103807_1](https://cloud.githubusercontent.com/assets/27399080/25774695/64d0f700-3249-11e7-8353-73d8c7f1c4f1.jpg)

However... when I use Moonlight, I can no longer use my DS4 to play games.  Steam thinks that Moonlight is the primary controller and the DS4's inputs are ignored.    

Few things to notice in the following screen captures (I'm playing Prey if it helps):
1.  Xbox button prompts now replace Playstation button prompts
2.  Somehow playing in Moonlight mode disables "steam controller support".  

![20170506104913_1](https://cloud.githubusercontent.com/assets/27399080/25774716/f92f2958-3249-11e7-8cb1-10b0c07172f6.jpg)

![20170506104943_1](https://cloud.githubusercontent.com/assets/27399080/25774721/0a681f7c-324a-11e7-90e1-9c4092e3ad5a.jpg)

Any ideas? I LOVE the concept of Moonlight streaming, but I can't figure out a way to make this work well in any type of game.  I feel like the built-in mouse control feature breaks my DS4 Steam Controller.  This problem is on pretty much any game (from Prey, to the Witness, etc.).  The only thing I can really do with the Moonlight controls is move the mouse and do a left-click (so basically spinning my character in a circle and shooting my weapon).  Also - the only way for me to get DS4 functionality back is to turn off Moonlight, boot directly into the game, re-toggle the "steam controller support" and re-start the game.  Moonlight seems to overwrite the "steam controller support" function of Prey.  

I did try doing this, but no change in behavior:
On GeForce Experience 3.0 and later, rename rxgamepadinput.dll to rxgamepadinput.dll.old in C:\Program Files\NVIDIA Corporation\NvStreamSrv and C:\Program Files (x86)\NVIDIA Corporation\NvStreamSrv.

Thanks,
Sean

**Comment by almanzarj** [comment]
hey were you able to find a solution to turning off xinput?

**Comment by aaiezza** [comment]
This is a huge downfall to the Moonlight iOS app. In earlier version of the app, Moonlight DID NOT block the use of a controller connected directly to the PC.
I used to LOVE playing Dolphin and Half-Life 2 from anywhere in the house with a wireless Xbox 360 controller with next to no latency,
Please bring this back! No one wants to use your app’s controls… they are completely pointless. Honestly.
I want to use Moonlight as a glorified wireless graphics streamer. Nothing else. That should literally have always been it’s use case.
Maybe with some simple VNC controls for the PC, but that’s it. I strongly recommend ripping off an app called iTeleport for their controls. They are EXCELLENT for controlling a PC!
But STOP BLOCKING other controllers directly connected to the PC! PLEASE!

**Comment by cgutman** [comment]
This isn't something we control from the client side. GeForce Experience handles hooking the game controller API. If a previous version of GFE worked better, you could try downgrading to an older version of GeForce Experience or try the rxinput rename trick in the setup guide: https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#using-a-gamepad-connected-to-the-pc-instead-of-the-streaming-device
