### ISSUE TITLE
Extreme input lag no matter what setting over lte

### ISSUE THREAD

**Issue by yu42hit** [moonlight-stream/moonlight-ios#273]
Is there a way to fix this? I had this issue on the chrome version as well over the local network too. I can never seem to fix this issue no matter what I do and no matter what platform.

**Comment by cgutman** [comment]
Most LTE networks have high latency due to large buffers, radio scheduling, strict QoS, etc. so you can expect that to be unsolvable from our end. You can reduce bitrate and resolution/fps and see if that helps at all.

The Chrome latency problem is a separate issue.

**Comment by yu42hit** [comment]
Ok, thank you for responding. I greatly appreciate it.
