### ISSUE TITLE
No L3 or R3 button

### ISSUE THREAD

**Issue by TheSIlentLink** [moonlight-stream/moonlight-ios#275]
I have touch screen controls on full but the L3 and R3 buttons don't appear on my iPad running iOS 10.3.2. Is this a bug or is there another way to active it that I have missed?

**Comment by cgutman** [comment]
The gesture is a bit tricky, but it's a double tap and hold on the sticks to activate it.

**Comment by TheSIlentLink** [comment]
Thanks a lot! Works perfectly!
