### ISSUE TITLE
Connection Terminated

### ISSUE THREAD

**Issue by calvinbrown085** [moonlight-stream/moonlight-ios#279]
Hi i'm getting a connection terminated when trying to run games on my iPad and iPhone, both are on the latest iOS update and the latest build of moonlight from the app store. I'm on verson 3.8.0.89 of the GeForce Experience, is anyone else seeing this?

**Comment by cgutman** [comment]
Looks fine in my testing. Are you still experiencing this?

**Comment by calvinbrown085** [comment]
@cgutman I'll have to try again, haven't tried in a while

**Comment by calvinbrown085** [comment]
@cgutman Yeah i'm still seeing it.

**Comment by cgutman** [comment]
Can you upload your logs from C:\ProgramData\NVIDIA Corporation\NvStreamer? ProgramData is hidden so you may need to enable hidden files to see it.

**Comment by calvinbrown085** [comment]
[NvStream.zip](https://github.com/moonlight-stream/moonlight-ios/files/1239209/NvStream.zip)

**Comment by calvinbrown085** [comment]
@cgutman
