### ISSUE TITLE
Sound stuttering when game app is in foreground

### ISSUE THREAD

**Issue by corthreat** [moonlight-stream/moonlight-ios#280]
The audio on my iPad Air 2 is stuttering heavily when I keep any 3D application in the foreground on the computer. The audio issues completely disappear when I go to the computer, manually tab the game into the background and put any non-3D program over it. (Example: Chrome browser which I use right now to write this issue)

Here is what I did:
- Downloaded latest Nvidia drivers
- Downloaded the latest Moonlight version from the app store
- Updated iPad to latest iOS version
- Streaming Computer connected via 1Gbit LAN
- iPad connected to the same network via 130mbit WIFI

Computer Specs:
- Windows 10 / Latest Updates
- 16 GB Ram
- i7 3770k
- GeForce GTX 670

Here is what I tried that did not solve the sound issue
- Different 3D games (Dota 2, Overwatch, Abzu) on streaming computer
- Different video resolutions (720p/1080p) on iPad
- Different framerates or compression (30/60hz, 2-50mbit). 50mbit works fine without artifacts.
- Testing different overlays (Auto/Minimal/None) on iPad
- Disabled Bluetooth on iPad
- Closed all background apps on iPad

Here is what solved the audio issue
- Tabbing the 3d application in the background so a 2d application overlays it. The game sound continues to play but obviously, the game cannot be seen anymore. Tabbing back into the game immediately causes sound stuttering again.
- I tried the Moonlight extension for google chrome on my laptop, using the same WIFI network of my iPad. The laptop uses only 54mbit (iPad 130mbit) WIFI speed but does not produce any sound issues or artifacts.

This issue might be related with the iOS App.

**Comment by cgutman** [comment]
I think this is fixed by https://github.com/moonlight-stream/moonlight-ios/commit/0293df7748825d1a3560a10f989ed78701d57bc8
