### ISSUE TITLE
Lag with moonlight v1.3.0 on iPad Air 2 with iOS v10.3.3

### ISSUE THREAD

**Issue by maxferro** [moonlight-stream/moonlight-ios#281]
Server with Windows 10, latest version of GFE and gigabit ethernet, and iPad Air 2 on wifi 5G. Moonlight configured with the lowest bitrate settings. No matter the game (from Limbo to Witcher 3) it runs with intermittent lag every few seconds. I tried downgrade GFE on server, reinstalling Moonlight on iPad, disabling Bluetooth... everything with no result. The problem repeats on iPhone 7 with the same symptoms.

**Comment by maxferro** [comment]
I've just installed the Moonlight Android version on a Samsung Galaxy J3 and it runs flawlessly so it seems that the problem is related to the Moonlight version of the app.

**Comment by cgutman** [comment]
Does the audio glitch when the video lags?

**Comment by maxferro** [comment]
The audio glitches when the video lags.

Greetings.

**Comment by maxferro** [comment]
With the last GFE v3.9.0.61 the app continues with the same audio/video lag errors.

**Comment by Dentifreak** [comment]
Oh my,
I was going to write a new post then I saw yours. EXACT same problem.

Windows 10
Latest GFE
Ipad air 2 on 5ghz
Latest moonlight.

0.5 Mpbs to 50 Mbps = Video/audio glitch every 5-10 seconds.

**Comment by maxferro** [comment]
I've just installed Moonlight on an iPad Air 2 with the previous iOS v10.3.2 and it runs without errors. On my iPad with the last iOS v10.3.3  Moonlight runs with the reported errors. It appears that the problem can be related maybe with some issue between the latest versions of the app and iOS.

**Comment by Dentifreak** [comment]
Wow ok. I hope we get a fix soon....

**Comment by Dentifreak** [comment]
So how is it with IOS 11 on your side ? I did a very brief test yesterday and didn't had problem but I won't conclude anything since I tried it for like 1 minute.

**Comment by maxferro** [comment]
Moonlight on an iPad Air 2 with iOS 11 seems to work very well. I tested on my girlfriend's iPad with Witcher 3, Dark Souls 2, Limbo, Oxenfree... with very occasional video/audio errors, but better than the previous iOS version. I am going to update my iPad too ☺️

**Comment by bcinco** [comment]
Still having issues with the latest versions (iOS + app) regardless of settings.  It's extremely laggy and probably dropping packets along the way.

No issue with Moonlight + Android, nor with any of my other local streaming stuff (SteamLink, PS4 Remote Play).  Everything runs wirelessly at 5GHz.
