### ISSUE TITLE
PC appears offline when not on home network

### ISSUE THREAD

**Issue by chrislightsaber** [moonlight-stream/moonlight-ios#282]
ive deleted all the app that i have that might conflict with moonlight and port forwarded all the ports (yes there correct), yet whenever i leave my home wifi my PC appears offline. any help? ive already uninstalled and reinstalled gefore, i do have shield streaming enabled (and can even stream but only on my home wifi)
all help is appreciated
thanks in advance!

**Comment by chrislightsaber** [comment]
i found the answer in another section.

moonlight-stream/moonlight-ios#140

I had this problem as well, but I found out it's a bug. Remove the host from your list and pair it again from another network with hosts IP address (with 4G like I did, for example). Now you can play your games via home network AND via Internet. ;)

basically i have to logon from a different wifi, and cant logon to the wifi that my pc uses or else it resets to (offline) when i leave

**Comment by Nate726** [comment]
Oh my god man thank you alot! I've been trying to port forward my Wi-Fi and set up my own VPN for hours now because nothing worked. You helped me out :)
