### ISSUE TITLE
RTPS Handshake error - 1 (only on ios not on my android)

### ISSUE THREAD

**Issue by Ichigo07** [moonlight-stream/moonlight-ios#285]
I only get this error on my ipad air 2. on my android device sony xperia xz it works fine. But if i spam resume session on my ipad it sometimes works. Phone and tablet are connected to the same network as my pc which is wired to the router also are all ports open just dont know why it only happens to my i pad but on phone it works perfect.

**Comment by xjrodzx** [comment]
I have the same issue. Galaxy S5 working perfectly. iPad Air 2 and iPhone 7, I receive the RTSP Handshake error. Both running iOS 11.

**Comment by gt2416** [comment]
Are you guys still having this issue? Are you connecting using your external ip or a dns ?
