### ISSUE TITLE
Pairing failed, incorrect PIN on tvos fork

### ISSUE THREAD

**Issue by Batblib** [moonlight-stream/moonlight-ios#287]
Hi. Sorry, this is my first time ever on GitHub and trying to do any coding work, but I wanted to try moonlight on my new appletv. I got the fork from https://github.com/kevsmithpublic/moonlight-ios and got it running on my appletv, but I can't pair due to "incorrect pin". Im guessing this has something to do with it being an old fork and a new version of geforce experience thats not supported? Is there any way I can fix this? Or is there anywhere more appropriate to discuss this? I realize this is probably the wrong place to post this, but I can't find anywhere else to get help so specifically, sorry.

**Comment by ersan** [comment]
From what I understand the bendodson port fixes this problem: https://github.com/bendodson/moonlight-tvos
