### ISSUE TITLE
On-Screen Controls - Adjustable Overlay Opacity on iOS

### ISSUE THREAD

**Issue by Korongo** [moonlight-stream/moonlight-ios#290]
I have an iPhone 7+ and I use the Gamevice Controller with Moonlight.

Great controller but Apple doesn't allow R3, L3, Select, or the "Steam" Button or XBOX Center Button if you will. I know with Moonlight, L1+Start = Select. Is there a command for the "Steam" Button or XBOX Center Button?

The Moonlight overlay definitely helps bridge the gap but the Opacity is a bit intrusive and I would like to request the ability to change the Opacity Percentage so I can have the controls there but barely visible since I already know where they are.

**Comment by 4moonlight** [comment]
try r1+start，it work for me

**Comment by Korongo** [comment]
I just tried again and it doesn't do anything for me. L1+Start = Select for sure but no other combos do anything for me. Any idea's why or what I can do? A combo for L3 would be amazing too
