### ISSUE TITLE
No virtual keyboard support on iOS

### ISSUE THREAD

**Issue by mattmeier612** [moonlight-stream/moonlight-ios#292]
I've noticed there's no virtual keyboard support on iOS as opposed to the Android release.  It looks like there's a PR with basic support ready to go where you tap with three fingers on the screen and it brings up the keyboard.  Since there's already a PR, I'm hoping (hoping being the operative word from a novice like myself) it wouldn't be that difficult to incorporate.

**Comment by somnolentsurfer** [comment]
+1 to would really like to see this.
