### ISSUE TITLE
Wake on LAN stops working in certain conditions

### ISSUE THREAD

**Issue by Proaxel** [moonlight-stream/moonlight-ios#293]
I have yet to pinpoint the cause, but whenever a certain thing happens, the host no longer wakes up when it receives a Wake on LAN packet. If I put the host PC to sleep and use Moonlight to wake it up immediately afterward, it would work fine, but when I try to do it when the host has been asleep for a certain amount of time, it doesn't wake from the packet.

Initially, I thought it would only happen when the host goes to sleep on its own, as set in the settings. But it still happens when I put the host to sleep myself.  

I then theorized that if the iOS device connects to a WiFi network other than the one the host is on, then something involving the communication between the two gets messed up if the host is asleep. When the host is awake, the host reports the correct way to communicate and it works fine again. I still have to test a couple times to make sure.

**Comment by wstlxx** [comment]
well ,my WOL never works.
but splashtop works well,not sure what's the problem.
did you try other apps like splashtop when moonlight is not working?
