### ISSUE TITLE
How do you access things on a different monitor?

### ISSUE THREAD

**Issue by Proaxel** [moonlight-stream/moonlight-ios#295]
I have encountered many issues when using the remote desktop where I would open up an application, but I'm unable to access it because the window for it came up on a different monitor than the one the host is streaming. Is there some way to switch monitors you are viewing or at least move the window to the display being streamed using only remote controls?

**Comment by cgutman** [comment]
Unfortunately not. NVIDIA designed GameStream for games which generally appear on the primary display. As a result, its remote desktop functionality has some rough edges like this.
