### ISSUE TITLE
Unable to get past RTSP handshake error -1

### ISSUE THREAD

**Issue by iZetiX** [moonlight-stream/moonlight-ios#298]
I tried disabling firewall, reinstall, reboot, etc.. but still unable to get it to work.

Pairing works just fine but my devices are unable to get past RTSP handshake error.

This worked before on my computer so i'm not sure if its the new update that changed things or what.

**Comment by cgutman** [comment]
Are you running GeForce Experience 3.12?

**Comment by iZetiX** [comment]
Yes.

**Comment by cgutman** [comment]
That's not supported yet by Moonlight iOS. Right now, you can reinstall GFE 3.11 to use Moonlight or wait for us to get the iOS update out. It will hopefully be by the end of the week.

GFE 3.11 link if you need it: https://ota-downloads.nvidia.com/ota/GeForce_Experience_Update_v3.11.0.73_official_BF82FA.exe

**Comment by IcannotgetpassRTSP** [comment]
DOES GFE 3.12 WORK WITH WITH ANDROID MOONLIGHT CAUSE I HAVE BEEN HAVING TO SAME PROBLEM FROM THE PAST FEW DAYS I HAVE MY WHOLE FIREWALL DOWN AND EVERYTHING BUT IT STILL DOESN'T LET ME PAST THE RTSP HANDSHAKE

**Comment by iZetiX** [comment]
@cgutman Thanks a lot! Downgrading to GFE 3.11 managed to fix the issue.

**Comment by wstlxx** [comment]
I just updated the app and it is supporting 3.12 now
