### ISSUE TITLE
[Requst] customizing on screen controls, and having “touch” mode for the mouse.

### ISSUE THREAD

**Issue by relink2013** [moonlight-stream/moonlight-ios#305]
I have seen others asking this with little to no replies. 

Is the ability to customize the on screen controls in the works? If we could move, and resize the buttons that would be perfect, removing unneeded buttons would also be a plus, as well as adding keyboard commands as buttons too. 

Also, a fantastic feature to add would be to have the ability to switch between “mouse” and “touch” mode. I mostly play FFXIV and if you enabled a touch mode it would allow mmo players to just tap their action bars instead of having to map a bunch of keys. Also useful for navigating menus and such. 

A touch mode with at least, Left click, right click, and a way to Drag would be amazing. 

I can currently do all of this, including an onscreen keyboard, with another app called Remotr. However when it comes to streaming quality and latency moonlight beats Remotr hands down, and I’d much rather use moonlight. However without these features it is pretty much impossible to play FFXIV, along with most other MMOs.

**Comment by Manic020** [comment]
Was about to post the same request. This is a must-have feature.

**Comment by cranker** [comment]
I think a simple Touchscreen Emulation would be very great. Many games do not need a mouse pointer or even mouse clicks... just touch events. 

I think this would be very usefull!

**Comment by Thaurin** [comment]
Yes, +1. Most games are unplayable for me without an MFi controller. Specifically, I would love the ability to:

- Configure the transparency of the gamepad overlay
- Set a dead zone area for the sticks; at least they seem to get stick in the direction I pull them to

Again, this is all using the phone's touchscreen controls. The other suggestions are great, too. I feel that this would make playing without an MFi controller finally viable and enjoyable for a lost of (gamepad-controlled) games.

**Comment by Thaurin** [comment]
Will revamping the controls ever be considered for a future release?
