### ISSUE TITLE
[Bug] Unplayable stutter with video/audio (using same setup on android runs fine with slight controller input delay)

### ISSUE THREAD

**Issue by natebgamer** [moonlight-stream/moonlight-ios#31]
Just been and bought a ps4 controller today to test the app some more. The app runs fine and smooth right up until I connect the ps4 controller with controllers for all. It took me a while to track down why it was doing it because everything works fine on my Xperia with the pad connected. As soon as I get the controller connected notification on my iPhone 6 8.1 I laggs really bad no just video but audio too.

I'm not sure if this is an issue with c4a or the app but just wondered if anyone else has the same problem.

I'll do some more testing in around an hour or so to see if I say for definite what the exact issue is.

**Comment by dwaxemberg** [comment]
Can you provide an update to the situation? Do you still have this problem on the latest version? Make sure you try using the onscreen controls instead of a BT controller to make sure it's not what @cgutman mentioned.

**Comment by natebgamer** [comment]
it does seem my router is only 2.4ghz according to this http://www.cnet.com/products/belkin-f5d8233-wireless-n-router/specs/

But I do not get this problem with the android version of the app just the ios version?

**Comment by natebgamer** [comment]
I'm also not sure if the bitrate sliders ect are actually doing anything

**Comment by cgutman** [comment]
@natebgamer bitrate slider is fixed in v0.9.0. Can you try to repro again?
