### ISSUE TITLE
No video on iPad Pro 10.5 remotely but works locally (Android works remotely under the same mobile connection)

### ISSUE THREAD

**Issue by johnnylau34** [moonlight-stream/moonlight-ios#312]
Dear devs,

Thanks for the endeavor into making this possible. 

On my iPad Pro (ios 11.2.6), I was able to pair up with GFE server 3.13.1.30 via moonlight app v1.8.0 and played smoothly on local network. 

However, once I am on external network either via wifi or my 4G / LTE connection, the pairing was fine but no video or sound coming thru. The touchscreen control was able to move the cursor. And the game is actually running on the home pc with GFE. (I tried cemu and GTA V)

The strange thing is: when using my Galaxy S8 on Android via the same external network, the video streaming and audio streaming are just fine.

May I know what I could have overlooked?

**Comment by MDANDYW** [comment]
i have the same problem with my iphonex.  But the strange thing is that in fact i successfully had the video and audio for about 10 minutes. Than the app stuck and this problem occurred and i couldn't fix this
