### ISSUE TITLE
MFI Controller Mouse Support

### ISSUE THREAD

**Issue by syberdamon** [moonlight-stream/moonlight-ios#313]
Would it be possible to get mouse support for MFI controllers similar to the Android version (e.g. hold start for a few seconds). I know MFI controllers don’t support start buttons, but the main center menu button could be used similarly. 

Unless it’s already implemented and I’m doing something wrong?

Thanks!

**Comment by nadaso8** [comment]
it's already there I've used it with an ancient controller made by moga for the iPhone 5. it was called something like the mega ace power.

**Comment by nadaso8** [comment]
i've done mouse functionality through the steam bindings setting the joysticks to mouse joystick and the triggers to left and right click

**Comment by nadaso8** [comment]
you can set a button to switch bindings in the steam binding menu also
