### ISSUE TITLE
New to moonlight. my pc is plugged directly into router via ethernet but wont connect to my moonlight app on ios

### ISSUE THREAD

**Issue by Synematix** [moonlight-stream/moonlight-ios#316]
i just saw this app on youtube the other day thought it sounded amazing. been trying to set it up but for some reason it wont work over ethernet. i expected it to need wireless but my adapter isnt available rn so i assumed ethernet to the router might work as well. sadly i was wrong can anyone help?

**Comment by nadaso8** [comment]
it shouldn't matter how it's connected just that your computer has internet. What exactly is your issue Is pairing failing are you unable to do port forwarding or is streaming not working.
