### ISSUE TITLE
WASD issue with Ark

### ISSUE THREAD

**Issue by Piribo** [moonlight-stream/moonlight-ios#318]
Hi everyone ! First of all thanks for this project everything work just fine.

However I’ve had an issue with ARK survival evolved I wasn’t able to move with the WASD stick (iOS 11.3 iPhone 6S)

I’ve tried one other game (Independant game) and except for the lag issue (low bandwidht) the WASD stick was doing it’s job

I did my tests with on-screen game pad emulation 

In addition I’ve ben running the moonlight app over an Xperia z3 with exactly the same behavior 

Any clue ?

Thanks and keep up the good work !

**Comment by cgutman** [comment]
Seems like a game compatibility issue with GeForce Experience. Have you tried updating GFE to the latest version?
