### ISSUE TITLE
Feedback RTSP Handshake Failed

### ISSUE THREAD

**Issue by CyrisXD** [moonlight-stream/moonlight-ios#319]
I'm using the Chrome Alpha to Stream to my Macbook and noticed the RTSP Handshake will fail and happens whenever there is a driver update waiting on GeForce experience. As soon as I update Moonlight works flawlessly again.

**Comment by cgutman** [comment]
I think this may be related to the "Driver may get removed after PC has been left idle for an extended period of time." issue cited in the 397.55 hotfix release. I saw it on my test machine too.

http://nvidia.custhelp.com/app/answers/detail/a_id/4661/~/geforce-hotfix-driver-version-397.55
