### ISSUE TITLE
[Bug] ipega 9023/controllers for All wrong button recognition and L3/R3 not working

### ISSUE THREAD

**Issue by nielo360** [moonlight-stream/moonlight-ios#32]
Im testing limelights latest build with controllers for all and the ipega 9023 which is a standard hid controller that works perfectly as a MFI controller with that app. All keys work as intend with all MFI games (r2 r1 l1 l2  start select etc) L3/R3 however supposedly not supported by MFI

However with limelight:
R2/R1 are switched to opposites  L2/L1 are switched to opposites
L3 and R3 do not work
select button gives disconnect controller option instead

Note: ipega 9023 connects to controllers for all as ipega 9025.
exact same layout and standard hid keys so it works fine as a mfi controller

**Comment by gamblor420** [comment]
I'm seriously contemplating on buying the ipega 9023, other than the problem you just stated would you recommend it? Gonna use it on an iPad air 2

**Comment by el3c** [comment]
Same issue here. The Controller is ok and it is working Great with any other mfi game... But not moonlight
