### ISSUE TITLE
iPhone X Home Bar Blocking Game Toolbars

### ISSUE THREAD

**Issue by yoshi43** [moonlight-stream/moonlight-ios#320]
I do not believe there is a way to universally hide the home bar on the iPhone X, but is there a way we can get it removed from Moonlight in a future update? It can get in the way of somethings during gameplay (mainly game toolbars like to use that space as seen in the picture I attached).

Is anyone else experiencing this issue, or has anyone found a way around this without jailbreaking their iPhone?

Thank you.
![home bar on stardew valley](https://user-images.githubusercontent.com/35871765/39868465-5ea0d6cc-541f-11e8-922b-934b6050f5d4.jpeg)

**Comment by cgutman** [comment]
The only way to work around this would be to put a black bar underneath to move the video up just enough to escape the home bar. It is possible to hide in iOS 11, but it shows back up when the screen is touched, so it's useless for Moonlight's use case.
