### ISSUE TITLE
"Connection Terminated" After Launching Game

### ISSUE THREAD

**Issue by nicnacnic** [moonlight-stream/moonlight-ios#321]
Hello Everyone!

So, every time I try to connect through Moonlight, the game will launch on my PC but after a few seconds the connection will terminate with an error message. This is a bit frustrating because I have looked through the forums and tried solutions that did not work. And yes, I am trying to connect over the internet (The streamer did work fine on my local network).

I have looked at the troubleshooting tips and uninstalled all programs that could interfere, reinstalled GeForce Experience (Using latest version), Reinstalled my drivers, disabled firewall and tried to lower the stream settings to 720p 30Hz but none of these solutions.

I am using a VPN on the client side but I don't know if that should cause any issues. A VPN did cause issues on the server side because of port forwarding but I managed to fix that by just disabling it.

And BTW, every time this happens I have to pair my PC on my phone again.

Thanks for any help!

**Comment by nadaso8** [comment]
I Have this same problem periodically and with no warning. I don't use any vpn and have even experienced it on local network. More worrying is that it hasn't seemed to be limited to just my phone also effecting chrome version on my laptop also.

**Comment by Metal-joker** [comment]
same problem. is there any solution?

**Comment by ValeryDubrava** [comment]
I have the same issue

**Comment by xefsarita** [comment]
did you find any solution?
