### ISSUE TITLE
libmoonlight-common.a

### ISSUE THREAD

**Issue by Bob1117** [moonlight-stream/moonlight-ios#322]
clang: error: no such file or directory: '/Users/wubao/Library/Developer/Xcode/DerivedData/Moonlight-bapixzyeqvbaltfsjaeucbgnatnd/Build/Products/Debug-iphoneos/libmoonlight-common.a'

**Comment by cgutman** [comment]
That's weird. Did you remember to run `git submodule update --init --recursive` ?

**Comment by cgutman** [comment]
I'm assuming that was the issue. Re-open if not.
