### ISSUE TITLE
No steam link app (thanks apple). Moonlight is running like a dumposter fire. Please help.

### ISSUE THREAD

**Issue by Aesop112** [moonlight-stream/moonlight-ios#323]
5ghz. Sitting near router with iPad Pro.
Latest GeForce experience. 
I was hoping it would stream the iPad pro’s native 120fps but it is locked to 30 or 60, and also runs like nails across a chalkboard. The audio is crackly and Laos skips roughly 8 -10 times a second. 
Frame rate also seems about 10 fps. 
1080ti
2017 8 core i7 @ 4.8

Tried switching to gfe beta. No dice
Also noticing sometimes mooonlight won’t pick up my game library.

What’s going on?

**Comment by cgutman** [comment]
Sounds like your connection is dropping tons of packets.

How's your PC connected to your router?

Is your WiFi network on a channel that's also in use by other networks? I'm not sure if iOS supports WiFi analysis apps, but you could see if you can find one that will tell you which channel your network is using and help you find a clear one.

**Comment by Aesop112** [comment]
I ran speedtest it’s 85 up and down 9ms ping if that helps

**Comment by cgutman** [comment]
The speed of your internet connection doesn't matter for local streaming. The most important aspect is the reliability (packet loss rate) of the connection between your PC and your iPad.

Is your PC connected to your router via Ethernet?

**Comment by Aesop112** [comment]
Yeah the pc is on Ethernet. I have a steam link which runs fine btw, and google Remote Desktop also works normally with no issues. I’m totally stumped.

**Comment by cgutman** [comment]
Yeah, unfortunately game streaming can be quite fickle since we can't buffer anything due to the low latency requirements.

Is the Steam Link on Ethernet?

Do you have two different network names for 2.4 GHz and 5 GHz networks? If not, your iPad could connect on 2.4 GHz which is fine for normal usage but not good for game streaming.

**Comment by Aesop112** [comment]
Yeah steam link is on Ethernet. I’m def on 5ghz :)

**Comment by cgutman** [comment]
I'd try switching your WiFi network to a different channel.
