### ISSUE TITLE
Apps list not the same as in GFE

### ISSUE THREAD

**Issue by verybigfurrymonster** [moonlight-stream/moonlight-ios#339]
Hi,
I added some games on my host game PC in GFE but the list doesn t seem to be updated on the client side.

I tried rebooting my server, restarting the app on the client side but still the same.
I tried removing the account and adding it on the client side.

I m puzzled, it s as if the list of streamable apps on the client side is frozen forver.

**Comment by cgutman** [comment]
Only certain games that Nvidia tests as GameStream-compatible will show up automatically. Some games that GFE can optimize will show up in GFE but not for GameStream (typically if they're older or less popular games or don't have good gamepad support).

You can manually add any games that aren't in the list for GameStream/Moonlight using the guide here: https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#adding-custom-programs-that-are-not-automatically-found
