### ISSUE TITLE
[Bug] DualShock Controler input

### ISSUE THREAD

**Issue by ghost** [moonlight-stream/moonlight-ios#34]
I'm using an iPhone 6 plus, 8.1.1 jailbroken with Taig. The stream works, loads, pairs, and even recognizes my DualShock4 controller (used with the controllers for all tweak) but after that things start getting.. Weird...

The menu is navigated with the circle and square buttons, for Xbox that would be X and B, which is weird but manageable. Once I load up a save the controls continue to baffle me. The triggers seem to rotate the camera and the right analog stick has no function at all! The game is completely unplayable. Any idea why this is happening?

I tried running the DS4 tool on my computer, having it on/off has no affect. I can't figure it out. Is it the game? Or my phone?

**Comment by cgutman** [comment]
iOS 13 natively supports DS4.
