### ISSUE TITLE
[bug report]The r stick doesn't work.

### ISSUE THREAD

**Issue by Yeongsup** [moonlight-stream/moonlight-ios#344]
There is a freezing bug in the r stick.
Do not follow your finger.
The r stick does not work properly after a keyboard function update. 
Double tap the r stick to reveal the keyboard. 
If you continue to operate a non-operational r stick, it ends with a connection error.

Geforce Experience has been updated to the latest version, the ios12 version of iPhone 7+.

**Comment by cgutman** [comment]
I can't reproduce this issue on my iPhone SE running iOS 12. I've tried activating and deactivating the keyboard and the right stick works properly. In addition, double-tapping the right stick doesn't open the keyboard (as is expected).

@dwaxemberg maybe you can try on larger devices to reproduce this?

**Comment by cgutman** [comment]
Nevermind, I got repro by attempting to tap the Start button on my iPhone SE. Maybe it's related to where we're hiding the textbox.

**Comment by cgutman** [comment]
Ugh, we forgot to hide the textbox so a user could actually tap it, causing the keyboard to appear and obstructing parts of the on-screen controls (but which parts we obstructed differed by device).

**Comment by cgutman** [comment]
Fixed version is released on the App Store.
