### ISSUE TITLE
[Request] Ability to zoom in and out with usual two finger pinch.

### ISSUE THREAD

**Issue by HellfireLx** [moonlight-stream/moonlight-ios#346]
Hi,
I had the chance to use another stream client on android where one could zoom in an out, in order to be able to see read/stuff on a fairly small screen like a smartphone or a tablet. 
I play a lot of strategy games, which have a very simple mouse usage, so in my case the joystick emulation is usually not needed, but when it comes to read details of units, it would be helpful to have a zoom function in the app, which of course would be independent of a zoom function the native game would have. I understand this not trivial as you have to emulate the zoomed portion and scale the input accordingly.

**Comment by cgutman** [comment]
This has been implemented since v7.0.0
