### ISSUE TITLE
Is there any way to solve the inconvience about the keyboard when using ios devices?

### ISSUE THREAD

**Issue by MDANDYW** [moonlight-stream/moonlight-ios#348]
Since iOS only registers keys typed, not keys pressed/released, Is there any way to solve this problem? Such as recognize the specific frequency of type as holding then send as pressed or is there any plug-in after jailbroken?

**Comment by andrianooo** [comment]
👍

**Comment by andrianooo** [comment]
https://github.com/andrianoo/worker1/commit/ce00cc24ac7c0a36942bfcafbc8a30bb9226a0c1

**Comment by andrianooo** [comment]
https://github.com/andrianoo/worker1/commit/ce00cc24ac7c0a36942bfcafbc8a30bb9226a0c1
