### ISSUE TITLE
Apple TV Version: Multi-Controller Mode

### ISSUE THREAD

**Issue by Marsafaka** [moonlight-stream/moonlight-ios#349]
I have the problem that the Apple TV version overrides Xinput Controller 1 (for control via Apple TV remote), so there are some games that are not working with my Xbox controller (Connected to the host) which defeats the purpose of the app. Could someone add the option for Multi-Controller Mode, like in the iOS version. I would do it myself but this exceeds my knowledge.

Best regards,
Mars

**Comment by Marsafaka** [comment]
Got it to work, the old rename files in "NvStreamSrv" trick seems to work after all, I don't know why it didn't in the first place. This solution is fair enough, considering that the app is not official anyway

**Comment by Marsafaka** [comment]
Got it to work, the old rename files in "NvStreamSrv" trick seems to work after all, I don't know why it didn't in the first place. This solution is fair enough, considering that the app is not official anyway

**Comment by ersan** [comment]
I'm having this same problem on the Apple TV build - what did you rename?  I've tried renaming rxgamepadinput.dll, rxgamepadremapping.dll, and rxnvgamepad.dll in both Program Files and x86 and every time Moonlight connects the controller shows up on the PC again (as Xbox 360 Controller for Windows).  Are you running the latest version of GFE?
