### ISSUE TITLE
Trackpad / touchscreen iPad

### ISSUE THREAD

**Issue by rasweb** [moonlight-stream/moonlight-ios#350]
It would be very convenient for us to play strategy (Civilization, Heroes) on a tablet (ipad) using Pencil. Please add normal touch screen support instead of the current inconvenient half-mouse implementation

**Comment by cgutman** [comment]
This isn't possible until Nvidia adds absolute mouse support to the GameStream protocol. Only relative mouse controls are available now, hence the touchpad-style controls.
