### ISSUE TITLE
L3 & R3 Support

### ISSUE THREAD

**Issue by seansemperfi** [moonlight-stream/moonlight-ios#352]
With the release of IOS 12, Apple introduced support for L3 and R3. Rotor Riot makes a controller for IOS with joysticks that support L3/R3, which I purchased, but it seems moonlight has not introduced support for actually using the L3/R3 function straight from the controller yet - just buttons on the screen in place of the L3/R3 functions. It there a plan for this to be introduced down the road?

**Comment by cgutman** [comment]
I already did introduce support in v2.4 but the Rotor Riot gamepad doesn't seem to expose the L3 and R3 buttons at all in iOS 12.1. See my comments on https://github.com/moonlight-stream/moonlight-ios/issues/193

**Comment by Kiaos** [comment]
I sent Rotor Riot a E-mail when I get the details cgutman and this issue will be the first to get the email. 
If I get any details on why they aren't working I will post it here. Hopefully the Rotor Riot team will get back with a response.

**Comment by seansemperfi** [comment]
Awesome, thanks for your dedication and keeping us in the loop.

**Comment by codegangsta** [comment]
Thanks @Kiaos! Really excited to get an answer to this. If R3/L3 works on moonlight iOS it will be a game changer

**Comment by Kiaos** [comment]
From: Rotor Riot Support <support@rotorriotplay.com>
Date: Thursday, December 13, 2018 at 12:23 PM
Subject: Re: L3 and R3 with Rotor Riot in iOS

Hello,

We are working with Apple to expedite a solution. Our buttons do work but a firmware patch is needed. We expecting to be able to provide you with a TestFlight link for our companion app, Ludu Mapp, that will provide a firmware update to our controller, that will eventually be available to all customers. 

Is this email the correct one to send this link to when available?

Thanks,

**Comment by Kiaos** [comment]
When I get the TestFlight link that updates my Rotor Riot Firmware I will give this info to the devs so they can test it as well. It will be a while before customers can use R3 and L3 but for now I would like to let you know that it is being worked on and as soon as I do a firmware update of my controller I will update this issue with a reply.

**Comment by Kiaos** [comment]
I have updated my controller with the Ludu Mapp test flight app for the Rotor Riot and I have also updated my iOS to 12.1.1. But so far R3 and L3 does not work in Moonlight if you know of another app that has the implemented support for R3 and L3 I would like to test that app since I now have the updated firmware. I am in contact with Someone who can update us on the development from the Rotor Riot side of things and aside from me two others have been e-mailed the test flight link to download an updated Ludu Mapp App. If you open the new app you can update the firmware by clicking the settings gear in the top left then on the next screen you click on Rotor Riot controller settings. then the next screen should offer a firmware upgrade of the controller. I have tested mutiple games and computers from my phone if you have a sugesstion on what i should test please ask me.

**Comment by 0vrlrd** [comment]
LUDU MAPP has been updated on the App Store to include firmware update 1.02 for the Rotor Riot controller. 

I don’t know if this is the same firmware being tested but I figured that I would give it a shot. 

Unfortunately it is the same as before, the thumb stick buttons do not appear with GCExtendedGamepad at all. It is identical to my results reported earlier in the other issue, and this is also with all of the latest code on the master branch.

**Comment by Kiaos** [comment]
if you need me to ask a question to the dev about the controller give me the technical details here. So I can forward them to the dev who works on the controller.

**Comment by RotorRiotPlay** [comment]
You need to ensure you have updated the firmware via LUDU MAPP. The current firmware is version 1.03

**Comment by 0vrlrd** [comment]
It works! Thanks @RotorRiotPlay 

The new firmware 1.03 fixes the issue and the thumb stick buttons work perfectly.

Great job everyone involved in making this happen.

**Comment by Kiaos** [comment]
Sweet I'm glad that it works now. Thank for Fraser for getting the ball rolling. I guess our code commit that i linked helped them see how we implemented it. Well i'm glade that is fixed.

**Comment by RotorRiotPlay** [comment]
The goal was to have a controller with L3/R3 which has now been realized. Thank you to everyone for your dedication and patience.

**Comment by ajmi982** [comment]
We can now use L3 R3 in Moonlight? What controllers work?

Sent from my iPhone. Please pardon any spelling or grammar mistakes. 

On Dec 18, 2018, at 8:53 PM, RotorRiotPlay <notifications@github.com> wrote:

The goal was to have a controller with L3/R3 which has now been realized. Thank you to everyone for your dedication and patience.

**Comment by cgutman** [comment]
The controller we're discussing here is https://www.amazon.com/Rotor-Riot-Certified-Controller-Compatible/dp/B07J1J7D6Z

**Comment by Kiaos** [comment]
> We can now use L3 R3 in Moonlight? What controllers work? Sent from my iPhone. Please pardon any spelling or grammar mistakes. On Dec 18, 2018, at 8:53 PM, RotorRiotPlay <notifications@github.com> wrote: The goal was to have a controller with L3/R3 which has now been realized. Thank you to everyone for your dedication and patience. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

The Rotor Riot Controller now supports R3 and L3

**Comment by jscoys** [comment]
Hey guys, with support of PS4 and Xbox one controllers natively with iOS 13 (R.I.P ncontrol), does Moonlight supports L3 and R3 buttons? Someone tested?

**Comment by cgutman** [comment]
Yes it does
