### ISSUE TITLE
[request] The resolution and color of the streaming are weird

### ISSUE THREAD

**Issue by MuddyW** [moonlight-stream/moonlight-ios#355]
**Environment: 2018 iPad Pro 12.9 + 100Mbps+ WLAN
Streaming resolution (monitor resolution): 2881 * 2160
Moonlight Settings: 1080p + 120fps + direct stream desktop**

What I want to know is that the wash out of the color (it's more like a gaming mode?) and the worse quality in resolusion in Moonlight are caused by Geforece Streaming or Moonlight and will that be possible to improve ?

### Please check these:
**The output of Moonlight(below):**
![moonlight](https://user-images.githubusercontent.com/39870883/51215558-47101f00-18ef-11e9-86a4-4e08bb8342ef.png)
**The output of Teamviewer(below):**
![teamviewer](https://user-images.githubusercontent.com/39870883/51215596-68710b00-18ef-11e9-9955-f562fc15a234.png)

**Comment by clock145** [comment]
mark
