### ISSUE TITLE
Performance Overlay

### ISSUE THREAD

**Issue by zakarupon** [moonlight-stream/moonlight-ios#365]
It would be nice to include some sort of performance overlay to help users judge their streaming quality such as the level of input lag, FPS, ping and packet loss. This would aid in determining whether their wifi setup is sufficient for streaming.

**Comment by zakarupon** [comment]
Any chance this will be implemented soon? I keep getting stuttering on my iPad at 120fps and without any performance overlay it’s really hard to determine what exactly the issue is...

**Comment by cgutman** [comment]
This has been implemented for a while
