### ISSUE TITLE
"Select" not recognized on Dualshock 4.

### ISSUE THREAD

**Issue by klave7** [moonlight-stream/moonlight-ios#367]
On the iOS 13 beta with support for the Dualshock 4, select is not recognized with any of the 3 remaining buttons (share, touchpad, or the PS button).  Hopefully this is something that can be fixed with an app update and isn't something lacking in the MFi API.

**Comment by cgutman** [comment]
Yes, it's supported in iOS 13 - https://developer.apple.com/documentation/gamecontroller/gcextendedgamepad/3237239-buttonoptions?language=objc
