### ISSUE TITLE
Support mouse control with iPadOS

### ISSUE THREAD

**Issue by coryalbert** [moonlight-stream/moonlight-ios#369]
Investigate and see if Moonlight can support the mouse support added into iPadOS.

**Comment by cgutman** [comment]
This isn't possible in the iOS 13 APIs since mouse support basically works like emulated touch support, so closing in favor of https://github.com/moonlight-stream/moonlight-ios/issues/358

**Comment by dlohin** [comment]
Maybe this can be re-evaluated with 13.4.  Mouseovers and right clicking all now work!

**Comment by ross-a-campbell** [comment]
I second dlohin's comment.

**Comment by cgutman** [comment]
Duplicate of #399 

More information is available in my comment there.
