### ISSUE TITLE
[Feature Request] Add bluetooth keyboard support

### ISSUE THREAD

**Issue by silentverdict** [moonlight-stream/moonlight-ios#37]
App works great, and im not sure if this is just me, but my bluetooth keyboard isn't working. Is there a special tutorial for this, or this just not implemented yet?

**Comment by dwaxemberg** [comment]
Not implemented yet. Will get to it soon (hopefully)

**Comment by ZeroT3K** [comment]
On-screen keyboard support if anything would be awesome. Controller-supporting MMOs such as Tera and FFXIV all currently require getting logins started at the computer itself before playing, and after there's no ability to chat with friends. 

Of course, this is just a minority of games that require a full keyboard. :) But still would be nice. Keep up the good work!

**Comment by maddox** [comment]
Any plans to finally support keyboard input? At the least it would be nice to be able to map keys to allow things like icade and other non mFI controllers to work.

**Comment by cgutman** [comment]
So I actually took some time to look at this today, and unfortunately it doesn't look like it's going to work. The main problem is that we don't have real access to key up and key down events that the GameStream protocol demands.

There's 2 reasons we'd want to have keyboard input support:
1. Sending input to the PC from a physical keyboard
2. Being able to use the iCade-compatible controllers that expose joysticks and buttons as key presses

Scenario 1 is simply not going to work without accurate keyup/keydown events. We would not be able to accurately distinguish between a short tap on a key and a held down key. Key repeating would happen and could be a way to determine if a key is held down, but once I put some thought into it, it doesn't really seem likely to work well. For example, if I hold down W, Moonlight will see W ... W . W . W . W. What do we do on the first W? Keep it held down waiting for more? That will cause control lag. If we don't hold it down and instead wait until we see it repeat, the PC will see W...WWWWW which is not equivalent to WWWWWW. This is in addition to the other problems of not being able to directly capture non-printable characters like Alt, Shift, Ctrl, Arrow Keys, etc.

Scenario 2 has seemingly more hope. iCade controllers generate synthetic key press events to indicate movement direction and button presses. This can and has been supported on iOS. My concern here is that the resulting experience will not meet a reasonable user's expectation for functionality. iCade only supports a single joystick or d-pad and also lacks start, select, L3, and R3. More importantly, the joystick emulation results in the control behaving like a d-pad, without the possibility for fine analog movements. It's fine for arcade style games that iCade was made for, but really not suitable for PC games which expect a precise analog control with 2 analog sticks.

In addition, supporting both 1 and 2 has its own set of problems. We'd need to somehow tell an iCade controller apart from a real keyboard, which doesn't appear to be possible in iOS currently.

If anyone has other thoughts or ideas, I'd be open to discussing alternatives.

**Comment by maddox** [comment]
Most controllers that support icade also support a keyboard mode. This
passes normal key presse to the system (not the weird on/off stuff that
icade does).

So, if there was a way to map these key presses to shield controller
buttons then it shouldddd work.

For example, if I want to map my controller in keyboard mode, I would map
button 1, which sends the 'k' key, to the 'A' key for Moonlight. Then when
the 'k' key is pressed, Moonlight would send the 'A' key of the shield
controller back through the streaming stuff.

* I say this without knowing at all how the mFI controller mapping works
with this protocol 😬

**Comment by hayden-robins** [comment]
That's such a shame! I know moonlight's core purpose is for gaming - but it's actually great to use as a remote desktop using mstsc/RDP. Would the above issues be a problem for this application? It would be SO COOL for me to be able to use my windows pc from my iPad with such low latency. Please consider adding this as a baseline?

**Comment by steventroughtonsmith** [comment]
Apologies if this has already been brought up elsewhere, but keyboard keyup/keydown support is fairly easy on iOS with private API; while that wouldn't help your App Store build, it could relatively easily be implemented for anybody who compiles the project from source.

Just a thought!

Here's an example implementation from minivmac4ios: https://github.com/zydeco/minivmac4ios/blob/master/Mini%20vMac/MNVMApplication.m

**Comment by KinnetZero3** [comment]
You mean, if i compile what you linked there and put it on my phone, I could have keyboard support for moonlight?

**Comment by cgutman** [comment]
Fixed by https://github.com/moonlight-stream/moonlight-ios/commit/76ab786e94b6949729b51043409660a102869543
