### ISSUE TITLE
remove Jailbreak detection 

### ISSUE THREAD

**Issue by Destroyer4LP** [moonlight-stream/moonlight-ios#373]
Please remove jailbreak detection from moonlight. The Jailbreak detection is unnecessary if it were an online banking app I could understand. It is easily bypassed it just takes more time to launch it is a bit annoying. Many people jailbreak for just for a dark mode, small device appearance tweaks. It is about freedom for your device. Nobody wants to cause harm. 
The jailbreak devs are gods the always make jailbreak happen even on iOS 13. Look the source code of the uncover jailbreak up it is on Github.

**Comment by cgutman** [comment]
I don't know what you're talking about. We don't have any jailbreak detection code. Why would we?

**Comment by Destroyer4LP** [comment]
Sorry I that assumed it. I had only tested it on stock ios and in a jailbroken state apparently some of my modifications did cause conflict, even none of my tweak are modifying moonlight.
Keep your work up!
