### ISSUE TITLE
Native resolution support on iPad

### ISSUE THREAD

**Issue by susemeee** [moonlight-stream/moonlight-ios#376]
In conjunction with a custom [utility](https://www.monitortests.com/forum/Thread-Custom-Resolution-Utility-CRU), display resolution and refresh rate may be changed dynamically when a client is connected.

I made a custom build to support the native resolution of iPad and am personally using it. It feels pretty nice to use a native resolution.

I will submit a PR after making compatible with other iPad models(I am using iPad Pro 12.9-inch model) and cleaning up some detail.

**Comment by sachangregory** [comment]
I get build errors when I try building the app

**Comment by susemeee** [comment]
Technically 'changing' a streaming resolution from host needs some of a proxy server. What I did is to make and install it to my host (built with C# and Windows API) and it changes streaming resolution when a client is connected.

I wonder if it is possible with current moonlight architecture, as it completely depends on GFE, rather than having a separate proxy server.

**Comment by healdgar** [comment]
I would like to see native 2732x2048 supported as well.  When i set a custom resolution, this helps, but it pinches the screen somewhat, and if I change my desktop from which I’m streaming to match my iPad, it shrinks the whole playable window into a box within a box,
