### ISSUE TITLE
In the ipad air2 useless 4k options

### ISSUE THREAD

**Issue by lankatty** [moonlight-stream/moonlight-ios#377]
In the ipad air2 useless 4k options

**Comment by cgutman** [comment]
I don't understand what this issue is describing. Please reopen with more detail about the expected behavior and the actual behavior.

**Comment by lankatty** [comment]
Sorry, I have a problem with my statement.
Heve-enabled devices, such as the iPhone 7Plus, have 4K option.
Devices that do not support Heve, such as the iPad Air2, do not have 4K options.
Can you add 4K resolution options to devices that do not support hevc?

**Comment by lankatty** [comment]
50 000 Kbps can still maintain low latency under H.264.
So I hope I can achieve higher resolution in streaming without supporting hevc devices.
Upgraded to the latest version of the iPad air2, the highest resolution is still only 1080p, which makes it possible for me to use only 1440x 1080 desktop resolution.
I want to add the 4K option to let me use the desktop resolution of 2048 x 1536

**Comment by lankatty** [comment]
Are you making progress?Can you give old IOS devices add 4k?

**Comment by RealDyllon** [comment]
I doubt it, because of the lack of an h265 support on the Air2. H264 4K has too high a nitrate to stream it, because iirc the Air2 has pretty slow wifi. 

You’ll have to be satisfied with your 4 year old iPad, or buy a new one 😬
