### ISSUE TITLE
Change resolution on tvOS version?

### ISSUE THREAD

**Issue by Cloudore** [moonlight-stream/moonlight-ios#378]
I have been trying the tvOS version for a couple of days and it works reasonably well with an xbox one controller. only problem is since I am on my local network and fully wired at 1gbps I wold like the resolution to be much better but I'm seeing quite a pixelated image on my tv, and can't seem to find controls to force it into any other resolution/fps.

I'll add, with the xbox controller at least, the "press option twice to disconnect" does not work, forcing me to close and open the application when i want to change games or disconnect

**Comment by cgutman** [comment]
You can currently find the settings in Settings app under App settings.

**Comment by Cloudore** [comment]
Thank you! @cgutman
