### ISSUE TITLE
Add Rumble Support

### ISSUE THREAD

**Issue by sachangregory** [moonlight-stream/moonlight-ios#379]

**Comment by cgutman** [comment]
I assume you mean for PS4 and Xbox controllers. Controller rumble is not supported on iOS/tvOS.

**Comment by sachangregory** [comment]
Might as well start sending feedback to Apple. Any ETA on the new version of Moonlight? Or am I able to build the in Xcode? (I can hackintosh to sideload it) If you can make an IPA you'll make my day. I would love to help test it! I have a Pro 10.5 and a iPhone X both on iOS 13.1 developer beta 3
