### ISSUE TITLE
tvOS Release in AppStore 

### ISSUE THREAD

**Issue by PabloZaiden** [moonlight-stream/moonlight-ios#380]
Will there be a tvOS release in the AppStore, or should we compile and side load?

**Comment by cgutman** [comment]
For now the tvOS version must be sideloaded, but we're working on getting into the App Store.

**Comment by PabloZaiden** [comment]
Any restrictions from the AppStore side to workaround, or just maturing the product?

**Comment by cgutman** [comment]
Nope, just needs some final polish before submitting for review.

**Comment by PabloZaiden** [comment]
Awesome!

**Comment by Kung-Foo-Kamel** [comment]
Have been waiting since the ATV4 came out for this, as soon as it happens, I'll spread the word.

**Comment by jmddn** [comment]
Great news!

**Comment by Trashpants** [comment]
@cgutman are there any specific bugs we can look at fixing to help get this out sooner?

**Comment by cgutman** [comment]
We're just waiting for Apple's approval now. We submitted it for review on October 9th.

**Comment by Kung-Foo-Kamel** [comment]
Cant wait, the Steam Link app is completely useless, Moonlight works much better.

If they let the Steam Link app through, then they "should" let this one through now, fingers crossed.

**Comment by dMopp** [comment]
Is there a HowTo for Sideload on AppleTV ?

**Comment by PabloZaiden** [comment]
Download it, build it, install it on your Apple TV. You’ll need a Mac with the latest Xcode and a developer account.

**Comment by gt2416** [comment]
Ever since iOS 13 I’m really looking forward to this release. Steam link has to many problems it’s frustrating. C’mon Apple approve it already.

**Comment by Kung-Foo-Kamel** [comment]
I don't know how Steam Link made it past anyone with half a brain and a pulse!

> Download it, build it, install it on your Apple TV. You’ll need a Mac with the latest Xcode and a developer account.

I did this when the ATV4 came out, everytime they update the OS you need to build it again, I dont have enough time in the day to waste on this anymore, just want to have a bash at my games once in a while when one has some spare time, I'm more than happy to pay for a working solution, there just isn't one, I alomost regret selling my Shield TV, as game streaming just worked.

**Comment by Batblib** [comment]
Yeah, also eagerly awaiting this release and would welcome any updates if there are any

**Comment by cgutman** [comment]
It's out! https://apps.apple.com/us/app/moonlight-game-streaming/id1000551566?ls=1

**Comment by gingerr** [comment]
Awesome! Living room, brace for impact.

Thank you!!! 🥇

**Comment by Batblib** [comment]
Thank you, this is amazing! Ive been using Steam Link the past hour and was on the verge of pulling my hairs out because of how HORRIBLE the performance was. So then I didnt really have any hope left when this post came, but installed it and WOW. PERFECT picture instantly

Two things also unfortunatly stand out. First is a minor issue: No support for 120hz or 1440p which is what I normally use. 

Second, and the big one: No surround audio. I have a Sonos setup, and the appletv can output DD from Netflix without any issues, but neither Steam Link or Moonlight sends anything but Stereo :(

**Comment by gt2416** [comment]
Thank you! Finally can play games on my tv without pulling my hair out.

**Comment by Kung-Foo-Kamel** [comment]
Yessss!!

**Comment by cgutman** [comment]
@Batblib You can file a ticket for the additional resolution and FPS options, so we don't spam the people on this ticket.

The surround audio issue is already filed as #371. You can get additional updates there.
