### ISSUE TITLE
Proper hardware keyboard support with key up/down events

### ISSUE THREAD

**Issue by AndrewMSHowe** [moonlight-stream/moonlight-ios#381]
Hi, proper support for our Smart Folio Keyboards would be awesome, and would take a bit of the sting out of the gigantic ripoff Apple charge for it :)

This guy has it working in his fork:

https://twitter.com/michaelmkenny/status/1098829195377954816?lang=en

https://github.com/MichaelMKenny/moonlight-ios/commits/hardware-keyboard

Is there any chance of getting something like this merged?

**Comment by cgutman** [comment]
Unfortunately, not as long as it requires private APIs. Apple will not allow apps to the App Store to use private APIs.

**Comment by cgutman** [comment]
Public APIs were added in iOS 13.4. This is now implemented in https://github.com/moonlight-stream/moonlight-ios/commit/75ab28a2c3634fe1975ab5f96559da6097f34c09
