### ISSUE TITLE
2 issues/requests to the ios version

### ISSUE THREAD

**Issue by Silithas** [moonlight-stream/moonlight-ios#382]
I got an ipad pro 12.9 2018 which has up to 120hz, but in the app, the ipad as we know has dynamic hz which apparently doesn´t recognize the 120 fps moonlight is set to. CAn you see if you can get it to have the ipad scale itself properly to 120hz?

And the request: Please add 1600x1200 res And similar lower and higher res support which is closer to the ipad´s native res to not have a 16:9 on ipad´s more square aspect ratio.

**Comment by cgutman** [comment]
First issue is a duplicate of https://github.com/moonlight-stream/moonlight-ios/issues/372

Second issue is a duplicate of https://github.com/moonlight-stream/moonlight-ios/issues/376
