### ISSUE TITLE
Display out

### ISSUE THREAD

**Issue by dragonpiper** [moonlight-stream/moonlight-ios#383]
If possible, can you implement External display. Tried with a basic app and it seemed simple enough.
https://developer.apple.com/library/archive/documentation/WindowsViews/Conceptual/WindowAndScreenGuide/UsingExternalDisplay/UsingExternalDisplay.html

This would allow hdmi to full the screen on ios devices that aren't 16:9 otherwise the moonlight is in a centered box that doesn't take up the whole screen on the iphone X series.

**Comment by gt2416** [comment]
You can add a custom display resolution in nvidia control panel then change to that resolution before gaming. Since I have a 21:9 ultra wide monitor It’s already full screen on my iPhone X. Same for the iPad, add a custom resolution and it works.

**Comment by dragonpiper** [comment]
I"m referring to it filling the screen when using a display out cable from the iphone. By default, it mirrors the iphone's resoluton, not the application.

**Comment by tristan-k** [comment]
Seems related to https://github.com/moonlight-stream/moonlight-ios/pull/411
