### ISSUE TITLE
Add Native iPad Screen Resolution Support w/ the 4:3 Aspect Ratio.

### ISSUE THREAD

**Issue by sachangregory** [moonlight-stream/moonlight-ios#385]

**Comment by bobbybean** [comment]
I believe this is already supported. Just ensure you have changed the resolution in nvidia properties to the native ipad resolution.

**Comment by sachangregory** [comment]
Then it changes when you connect

**Comment by cgutman** [comment]
Duplicate of https://github.com/moonlight-stream/moonlight-ios/issues/376
