### ISSUE TITLE
Thank you very much for your work. It's a miracle, but there are still some questions.

### ISSUE THREAD

**Issue by qqjp** [moonlight-stream/moonlight-ios#387]
Thank you very much for your work. It's a miracle, but there are still some questions.
The IOS version of moonlight does not have the option of "Never drop frames". Even if the network is perfect, there are still some frame dropouts, while the Android version is better. Is it because of the limitation of IOS that it is impossible to have options?

**Comment by lankatty** [comment]
yes
Dithering phenomenon in IOS device
And on the Android device is smooth, hope that developers can add this option in the ios device, hope is not the reason why ios limit
