### ISSUE TITLE
tvOS - Trigger HDR mode when Match Dynamic Range is on

### ISSUE THREAD

**Issue by ersan** [moonlight-stream/moonlight-ios#395]
It seems as though you have to manually enable HDR in tvOS settings to get HDR working in Moonlight.

It would be much better - if possible - to trigger the switch to HDR when HDR content is streaming, as most people use "Match Dynamic Range" and leave tvOS in SDR mode.

**Comment by ersan** [comment]
Actually, can I get a confirmation that HDR is supported at all?  I get games to run in HDR with workarounds but they look the same in SDR and HDR mode on the Apple TV

**Comment by cgutman** [comment]
Are you using a game that actually supports HDR on GameStream? Only a few games do, and you need an HDR monitor on the PC for it to work on Win10.

**Comment by ersan** [comment]
> Are you using a game that actually supports HDR on GameStream? Only a few games do, and you need an HDR monitor on the PC for it to work on Win10.
Yes, I’m using the Mass Effect Andromeda trick and the games I’m playing are definitely in HDR - I’ve used it with Resident Evil 2 remake, Devil may cry 5, and resident evil 3 demo.  The game has the HDR option enabled, and I put them in HDR.  They look totally different (as does the steam overlay) - the colors are completely different in HDR vs non HDR.  However those colors look the same whether or not the Apple TV is in HDR or SDR so that leads me to believe that HDR isn’t actually working in moonlight.

**Comment by ylor** [comment]
Can this be reopened? I'm seeing a similar/same issue on Apple TV. Using the same host PC and configuration and testing on both an Apple TV 4K and Nvidia Shield 2017. the SHIELD correctly adapts and sends an HDR signal to the display whereas the Apple TV stays in SDR but colors are off.
