### ISSUE TITLE
iPad OS 13.4 supports key events - full kb/mouse support now possible?

### ISSUE THREAD

**Issue by AndrewMorsillo** [moonlight-stream/moonlight-ios#400]
For a long time iOS didn't provide key events to app developers. That meant that it was impossible to make a keyboard behave properly in games (ex: holding 'w' did not move character). This seems to have changed with iPadOS 13.4 finally!

It should now be possible to have full keyboard support. Depending on how 13.4's mouse support works full remote kb/m gaming might finally be within reach (edit: it looks like the native mouse support still can't capture the pointer, but it could be done with citrix or swiftpoint).

https://developer.apple.com/documentation/uikit/mac_catalyst/handling_key_presses_made_on_a_physical_keyboard?changes=latest_minor&language=objc

**Comment by cgutman** [comment]
This is already done, just not released yet. https://github.com/moonlight-stream/moonlight-ios/commit/75ab28a2c3634fe1975ab5f96559da6097f34c09
