### ISSUE TITLE
iPad OS 13.4 Mouse Support for Remote Desktop

### ISSUE THREAD

**Issue by metherul** [moonlight-stream/moonlight-ios#402]
Moonlight is consistently the fastest remote desktop application that I have found on iPad OS, but it lacks cursor support. While I know it's impossible to use the mouse in games (#399), it would be nice to offer the feature anyways for point+click games and remote desktop.

**Comment by Sheidy007** [comment]
On ipad there is an application for connecting via rdp. It is called 'Jump'. When mouse support was released on ipadOS 13.4, support for the right-left mouse button and scrolling was immediately added there. So this is possible. I will be very happy if this feature will be a priority for ipad os. And if its possible add F1-F12 button support from physical keyboard.

**Comment by metherul** [comment]
I've been using Jump Desktop for a while. It works quite well, but it doesn't handle bandwidth changes as well as Moonlight. The latency is much higher as well.

**Comment by cgutman** [comment]
Released in Moonlight iOS v5.0.0.
