### ISSUE TITLE
Some key combinations don't work in remote desktop environments.

### ISSUE THREAD

**Issue by metherul** [moonlight-stream/moonlight-ios#406]
From my testing, Windows and Alt key combos don't seem to do anything. 

Also, thanks for the remote desktop support. Hot damn Moonlight is so much faster than anything else out there.

**Comment by cgutman** [comment]
Which key combinations did you test?

Many common ones like Win+Tab, Alt+Tab, Alt+F4, etc. are blocked by GeForce Experience itself, presumably to avoid accidentally exiting your game. There's no known way to override the blocks, but you can use a program on your host like AutoHotkey to map another key combo to the ones you're trying to use. There are instructions for that on our Discord server.

**Comment by metherul** [comment]
Ah, I was assuming that was the case. Thank you!
