### ISSUE TITLE
Ipad mouse movements

### ISSUE THREAD

**Issue by PipSpinell** [moonlight-stream/moonlight-ios#407]
Is the new 13.4 mouse implementation works ingame?
I tested Ti with no success.

Thanks

**Comment by cgutman** [comment]
Mouse support for iOS 13.4 is limited to apps and games that don't capture the mouse. Games that commonly capture the mouse are first-person shooters, some RPGs, and other games where the mouse operates the camera and where no mouse cursor is shown on screen.

There is no way to capture the mouse on iOS 13.4, which makes it impossible to support games which capture the mouse on the host PC. Moonlight has special support for the iOS-compatible Citrix X1 mouse which can support these games, but it's not possible to do generally for all Bluetooth mice.

This same limitation applies to all game streaming and remote desktop apps on iOS 13.4, including [Steam Link](https://steamcommunity.com/app/353380/discussions/7/4540134287676567679/)

**Comment by birdman2131** [comment]
https://developer.apple.com/videos/play/wwdc2020/10617/

Looks like ios14 may solve this issue.

**Comment by koseduhemak** [comment]
This changes with the new IPadOS:
https://developer.apple.com/videos/play/wwdc2020/10617/

Pointer locking will be possible!

**Comment by ovnx** [comment]
It seems the pointer works for me on the iPad, but when clicking with a trackpad it doesn’t work.

**Comment by intdel** [comment]
So did anyone look at the new iOS 14 API? How hard is it going to be to implement it? Also it seems in iOS 14 we will have rumble support as well.
