### ISSUE TITLE
ipados 13.4 mouse support conflicts with Citrix X1 mouse

### ISSUE THREAD

**Issue by atang3140** [moonlight-stream/moonlight-ios#409]
I'm very glad to use citrix x1 mouse on moonlight app. Thank you.
but in ipadOS 13.4, the default mouse support of ipadOS forces the cursor to move its first position when I press shift, alt or ctrl key.
Same issue was on jump-desktop App, and they solved this problem by disabling physical mouse while using remote app.
https://support.jumpdesktop.com/hc/en-us/community/posts/360060871292-iPadOS-Mouse-support-conflicts-with-Citrix-X1-Mouse-cursor-jumps
Please add the same disabling function when I toggle the 'Citrix X1 Mouse Support' menu to 'YES'.
Thanks very much.

**Comment by cgutman** [comment]
@Lorold @samwelnella are either of you able to confirm this bug? I have a possible fix I would like you to test.

**Comment by Lorold** [comment]
@cgutman I will be home on Sunday. Then I can test your fix.

**Comment by cgutman** [comment]
Fixed by d9cb55a17f2c5155fac2d86c4a1a5903ae262b14
