### ISSUE TITLE
How to enable statistics overlay on iOS?

### ISSUE THREAD

**Issue by sofakng** [moonlight-stream/moonlight-ios#412]
Is it possible to enable the statistics overlay on iOS?

I'd like to see the decoding time, etc.

**Comment by cgutman** [comment]
It is not possible. In particular, the decoding API we use on iOS doesn't provide those metrics.

It is possible to provide a very simple overlay for packet loss and frame rate, but not more than that.

**Comment by sofakng** [comment]
Ahh, OK.  Thanks for the information.

**Comment by nauxliu** [comment]
@sofakng Any plans to add the overlay that displays packet loss, frame rate, and decoder?  That would be very helpful, for example, I recently discovered with the mac version that the [3090 doesn't work with HEVC right now](https://github.com/moonlight-stream/moonlight-qt/issues/447), if this iOS version support displaying statistics we would be able to find these problems.
