### ISSUE TITLE
iOS 13 - Moonlight

### ISSUE THREAD

**Issue by Scot-Survivor** [moonlight-stream/moonlight-ios#413]
So I am not sure what information you need so here are my specs (this is all over local wifi)
Ryzen 2700 @ 3.4Ghz
16 GB 2400mhz Cosiar LPX
RTX 2060 6Gb 

My iPhone is iOS 13,6 iPhone XR 64GB

Whenever I try to stream Minecraft Win 10/Minecraft java and TF2 I get "moonlight RTSP handshake failed: 35" Error.
Is there a fix for this? This all-over Local Wifi Again.

**Comment by intdel** [comment]
Did you check your firewall to allow nvstreamer.exe and nvcontainer.exe?
