### ISSUE TITLE
IOS14 Mouse-Up Event does not work

### ISSUE THREAD

**Issue by hblockx** [moonlight-stream/moonlight-ios#419]
Hey, while it was working in IOS13 in IOS14 you cannot use a mouse / trackpad anymore. I do have the MagicKeyboard with the trackpad and there you can click but it will "hold" the click forever. It will never release the click in moonlight...

**Comment by cgutman** [comment]
This is already fixed by 2d24b0ec7b7c8ad01cc601bd6d43effc1fb72a56.

We are waiting for Apple to approve the new build.
