### ISSUE TITLE
ios 14 broke moonlight for gtx 1080?

### ISSUE THREAD

**Issue by knovs** [moonlight-stream/moonlight-ios#420]
Not 100% sure because of ios14, but moonlight worked perfectly few weeks ago, but now it just stutters immensely, and games are honestly not playable. Anyone else?

**Comment by knovs** [comment]
Somehow games are again running ok now, maybe temporary network issue.
Only thing that is still not working is my ipad keyboard’s mouse. As soon as I click somewhere, it sort of hangs..

**Comment by cgutman** [comment]
Make sure you've updated Moonlight to v6.1.0, which includes a fix for that bug on iOS 14.
