### ISSUE TITLE
TvOS mouse support

### ISSUE THREAD

**Issue by cooldna2** [moonlight-stream/moonlight-ios#424]
Apple tv can connect to a bluetooth mouse, but that's it. No movement is recognized and can’t use in a game or so.
I think it should be easy task to add mouse functionality, so I am waiting and waiting... anyway, you guys are great! I use moonlight game stream everyday and that’s very nice!

**Comment by cgutman** [comment]
Is your Apple TV running tvOS 14? I believe mouse support should work as long as you're using an Apple bluetooth mouse.

**Comment by cooldna2** [comment]
Yes it is running tvos 14. I am using microsoft bluetooth mouse 3600, maybe that is the cause...

**Comment by cooldna2** [comment]
Does it have to be apple mouse? I tried old version of magic mouse, but my apple tv cannot recognize the mouse at all...

**Comment by cgutman** [comment]
I don't know. What Apple supports is up to them. I believe Apple mice is all they officially support.

**Comment by cooldna2** [comment]
iPadOS supports the microsoft mouse. is apple tv different?

**Comment by cgutman** [comment]
Yes, tvOS doesn't have the UIKit mouse support which has broader hardware support. It only has GCMouse which doesn't seem to support many (or any) BT mice from other vendors.

**Comment by cooldna2** [comment]
https://cloudywithachanceofgames.com/shadow-updates-ios-and-tvos-apps-to-allow-mouse-and-keyboard-support
It seems that tvos DOES support mice... Am I wrong?

**Comment by cgutman** [comment]
No, it _does_ support mice, just not _your_ mice.

**Comment by cooldna2** [comment]
What I don’t understand is that I have magic trackpad 2 and there is no way my apple tv recognizes the trackpad or my magic mouse 1. Apple said they now support mouse for gaming, and it is not like what you said, apple branded mouse and trackpad also won’t be recognized by apple tv at all.

**Comment by cgutman** [comment]
That's strange. Does it work in any other app?

**Comment by cooldna2** [comment]
It does work when it is paired with my iPad. Apple tv, not at all.

**Comment by cooldna2** [comment]
I’ve tried other mice with iPadOS and apple tv, ms bluetooth 5.0 mouse doesn’t work with magic keyboard attached and while apple tv can connect to the ms mouse, only middle wheel works. and iriver mouse (bt 5.0) DOES work even with magic mouse attached, but no luck with apple tv, the iriver mouse doesn’t work while it does connect to the apple tv.

**Comment by cooldna2** [comment]
for your information, ms bluetooth 5.0 mouse does work in other app.

**Comment by cooldna2** [comment]
iPadOS 14.2 beta solved problem for ms bt 5.0 mouse! but yet apple tv tvOS 14.2 beta doesn’t support this ms mouse.

**Comment by don17sch** [comment]
@cgutman are you sure that apple tv supports mice? I cannot get it to recognize my magic mouse 2. It does not show in the bluetooth menu at all

**Comment by don17sch** [comment]
also while I am able to pair a razor bluetooth mouse it does not register any movement of the mouse within moonlight. 

I am not sure that any mouse feature is supported by tvOS

**Comment by tristan-k** [comment]
I can confirm that neither bluetooth mice nor bluetooth keyboards are recognized. Latest Moonlight on tvOS 16.2 with Apple TV 4K (A15).

**Comment by rdamron** [comment]
Even the apple mouse or just other bluetooth mice?

**Comment by tristan-k** [comment]
I only tested non-apple mice.

**Comment by StErMi** [comment]
Hi there, I tried with my current Apple TV 4K and while I can add the mouse as a BT device, it won't work at all with the current version of moonlight. 

As far as I get from this discussion is up to the developer of the app to add support to the mouse?

https://discussions.apple.com/thread/255092574?sortBy=best

My mouse is a Logitech MX master 2
