### ISSUE TITLE
Pairing Failed problem -Plz help me

### ISSUE THREAD

**Issue by Xchkoo** [moonlight-stream/moonlight-ios#425]
after updating my gfe,i can't connect to my PC with my ipad.
"Pairing Failed
An SSL error has occurred and a secure connection to the server cannot be made."
how can i slove it?I will be grateful to you if you can help me.

**Comment by cgutman** [comment]
What version of iOS is your iPad running?

**Comment by Xchkoo** [comment]
thank you. it's 13.5.1

**Comment by cgutman** [comment]
Does the error happen if you try from another device like a PC, Mac, or other iOS or Android phone?

Do you have any antivirus/anti-malware or firewall software on your host PC?
