### ISSUE TITLE
Occasional micro stuttering

### ISSUE THREAD

**Issue by cooldna2** [moonlight-stream/moonlight-ios#427]
iOS, iPadOS, TVOS while moonlight is running there are micro stuttering, maybe there should be one more frame buffer when streaming...

**Comment by bverkron** [comment]
I think I removed most of the stutter I observed by dropping the bitrate (gigabit LAN). Would be curious to see if there is another solution as it's always nice to keep the bitrate higher for better quality.

**Comment by bverkron** [comment]
Actually I don't think that's the case. I did some further subjective testing by playing back this video over Moonlight on my Apple TV.
https://www.youtube.com/watch?v=wmNU1c9Sd00

It has similar stuttering with various combinations of settings. 1080p vs 4K, HVEC on / off, went all the way down to the lowest bitrate (.5Mbps I think?) and it will still there.

Steam Link exhibits similar stuttering but seems much less frequent in most cases. Tried Steam with most optimal settings (Fast, etc) and it was still there just to a lesser degree than Moonlight

**Comment by angrycrab** [comment]
Can confirm the same issue on Apple TV 4K Im using Ethernet cable and it still stutters on all bitrates and resolutions.

FPS is capped at 60 with no frame drops but the stream will still stutter.

**Comment by bverkron** [comment]
Forgot to mention I'm also on Ethernet. I tried the macOS moonlight client and it had similar issues. Maybe not quite as many stutters but it was pretty limited anecdotal testing so I'd assume it's probably roughly the same and the underlying issue itself is the same. Parsec on macOS did noticeably better.

**Comment by jarronimo** [comment]
I’m having the same issue.

**Comment by rettgerst** [comment]
I'm also having this issue. stuttering on my ATV over gigabit ethernet lan. I also have a shield tv, and the nvidia games app is smooth, the moonlight app on the shield stutters unless I turn "never drop frames" on. might be related to #459?

**Comment by Matthew1231A** [comment]
Seconding everything above. I have a gigabit connection on LAN and my Apple TV 4K is stuttering despite receiving a solid 60 frames per second over the wire with <5ms latency. Possibly unrelated, but the turning off HEVC in the Apple TV settings does not turn it off according to the statistics overlay.

**Comment by Koopa777** [comment]
Same as all above. 2021 ATV 4K, everything in the chain hardwired with Cat6a Ethernet, GPU is Ampere (so supports the NVENC encoder), stutters all over the place. Gamestream works fine on a 2019 Shield TV Pro.

**Comment by ersan** [comment]
I have had this issue since forever through a half dozen different hardware and network configurations.  I eventually gave up on Moonlight.  I don’t think most people notice the microstutter for some reason or this issue would get more attention.

**Comment by fidelix** [comment]
@ersan what do you use instead of Moonlight?

**Comment by ersan** [comment]
@fidelix I ran a 100ft fiber HDMI cable into my living room, split that to my bedrooms and use VirtualHere to connect controllers in each room.  Remote I’ll usually use Steam Link (which has its own set of annoyances, but not usually stutter).

**Comment by ilderaj** [comment]
Same issue here.

**Comment by felipejfc** [comment]
if anyone wants to try it, I have a fork where I put a vsync option that I think helped a lot with the stutter on ios devices, see [here](https://github.com/felipejfc/moonlight-ios)

**Comment by fabiosersante** [comment]
> if anyone wants to try it, I have a fork where I put a vsync option that I think helped a lot with the stutter on ios devices, see [here](https://github.com/felipejfc/moonlight-ios)

DO you think messing with v-sync on the server side could help somehow? I've tried everything to no avail.

**Comment by bverkron** [comment]
> if anyone wants to try it, I have a fork where I put a vsync option that I think helped a lot with the stutter on ios devices, see [here](https://github.com/felipejfc/moonlight-ios)

Your `here` link just points to the root of the GitHub project, but I tried 8.0.0 that just release with your feature on my AppleTV 4K and it's butter smooth now!

I read some comments in about it adding latency for some people and it calls it out in the setting as a compromise but I personally did not notice any latency. I tried Rocket League, The Messenger, and TowerFall Ascension and did have any issues with latency. I'm only a very casual player for those games though so I'm hardly the best test case. I also turned on the stats overlay and it consistently said between 0 and 1 ms latency, so there's that as well. Even if there is some level of latency the overall experience is lightyears better than before with the stutter.

Thank you so much, I was getting annoyed with having to run my living room PC just to stream games smoothly from my main gaming PC in another room. Back to a much less power hungry and simpler couch gaming setup with the Apple TV. Great work!

**Comment by felipejfc** [comment]
> > if anyone wants to try it, I have a fork where I put a vsync option that I think helped a lot with the stutter on ios devices, see [here](https://github.com/felipejfc/moonlight-ios)
> 
> Your `here` link just points to the root of the GitHub project, but I tried 8.0.0 that just release with your feature on my AppleTV 4K and it's butter smooth now!
> 
> I read some comments in about it adding latency for some people and it calls it out in the setting as a compromise but I personally did not notice any latency. I tried Rocket League, The Messenger, and TowerFall Ascension and did have any issues with latency. I'm only a very casual player for those games though so I'm hardly the best test case. I also turned on the stats overlay and it consistently said between 0 and 1 ms latency, so there's that as well. Even if there is some level of latency the overall experience is lightyears better than before with the stutter.
> 
> Thank you so much, I was getting annoyed with having to run my living room PC just to stream games smoothly from my main gaming PC in another room. Back to a much less power hungry and simpler couch gaming setup with the Apple TV. Great work!

thanks for the feedback! happy to see community engagement :)

**Comment by brunosmarques** [comment]
Hi everyone, I'm really looking forward to use this fix on my phone. Do we already have a date for it to be published at Apple App Store? If I got it right, it's going to be released with Moonlight v8.0.0, is that right? Thanks for everything!

**Comment by bverkron** [comment]
This was posted in their discord yesterday morning

> the Apple TV version should be live, but the iOS version is still in Apple review

https://discord.com/channels/352065098472488960/465368786023874562/942820885805539339
