### ISSUE TITLE
iPhone/iPad as control for AppleTV not fully functional

### ISSUE THREAD

**Issue by Merkapt** [moonlight-stream/moonlight-ios#435]
It appears that using an iPhone or an iPad as a remote (control center version) to the Moonlight app on AppleTV is now a bit broken. You can move the cursor just fine, but it wont register taps or long taps as mouse clicks. Using the actual remote works, but it varies between programs if it wants a tap or a full press to register a mouse click.
The tested models of iPhone and Ipad were the SE 2020 (14.2) and the Air 2 (14.2). Tested PC's were two windows 10 machines on 20H2, GE 3.20.5.70. The AppleTV 4k is on 14.2

Until a few weeks ago (before the recent update to Moonlight) it worked flawlessly where a "tap" always registered as a mouse click.

**Comment by cgutman** [comment]
This is fixed by https://github.com/moonlight-stream/moonlight-ios/commit/03f330ccff6de20ec30ba2c73037b91d55289707 in v7.0.1. It is just waiting on Apple's approval to be released.
