### ISSUE TITLE
HEVC doesn’t work even when my host graphic card is RTX 3070 and the client is iPad pro 3

### ISSUE THREAD

**Issue by cooldna2** [moonlight-stream/moonlight-ios#436]
Even when I set HEVC on, the statistic says H.264.
Is something wrong with my setup, or is it the bug of moonlight client?

**Comment by cgutman** [comment]
https://github.com/moonlight-stream/moonlight-docs/wiki/Frequently-Asked-Questions#why-doesnt-hevc-or-hdr-streaming-work-on-my-rtx-3000-series-gpu
