### ISSUE TITLE
Bug: Cannot hear game audio while in a Discord call via the same iOS device

### ISSUE THREAD

**Issue by suchipi** [moonlight-stream/moonlight-ios#437]
If you join a voice chat or call using the Discord iOS app and attempt to use the Moonlight iOS app while in that call, audio from the game/stream won’t be audible.

For most iPad apps, audio plays at a quieter volume while in a call if you are using the builtin speakers, but when you are using headphones, it plays at full volume. I would expect Moonlight to behave the same way and was surprised to find it didn’t.

I ran into this bug with an iPad Pro 11 inch (Model number MTXQ2LL/A) running Moonlight iOS 7.0.1 from the App Store.

If I disconnect from the Discord call, audio works properly and as expected.

**Comment by geoffp** [comment]
Just had the same experience!

**Comment by Albert1603** [comment]
Same issue here.

**Comment by cruentus** [comment]
Same issue here as well. It worked once, it is no longer working

**Comment by MBR05E** [comment]
I have been troubleshooting this with no luck, has anyone found a solution?

**Comment by suchipi** [comment]
This issue is still present; commenting to unmark as stale.

**Comment by Terane86** [comment]
Issue still present, posting for traction.

**Comment by cgutman** [comment]
There is a possible fix in master. You are welcome to build it to confirm.

**Comment by viseniv** [comment]
> There is a possible fix in master. You are welcome to build it to confirm.

Hi. I am testing the build on the github repository, so far so good. Discord and Moonlight sound are working fine at the same time. Also i noticed the custom resolution option in settings, this is also working fine with my iphone xs on the latest ios version. 
If someone can compile a .ipa o make a testflight for beta testing it would be great, i don't have an Apple developer account

**Comment by cgutman** [comment]
This was fixed in v8.1.0.

**Comment by suchipi** [comment]
Thank you!
