### ISSUE TITLE
Last two updates broke hardware mouse support

### ISSUE THREAD

**Issue by nonamebran** [moonlight-stream/moonlight-ios#440]
Last two ios updates for ipad moonlight seems to have broken hardware mouse support. I can no longer drag my mouse to copy or highlight words or drag scroll bars without the mouse freezing for a few seconds. Version 6.1.1 did not have this issue.

**Comment by cgutman** [comment]
I'll need more information to investigate. I just tested on iOS 14.3 today and mouse dragging works fine for me with my Bluetooth mouse.

What version of iOS? What type of mouse? How is it connected?

**Comment by uvdpqfa** [comment]
same issue!!
6.1.1 work fine for me
after update to 7.0.1, cursor will freez when mouse dragging with my bluetooth mouse
but touchscreen work fine again

ipadOS 13.6

**Comment by cgutman** [comment]
Either update to iOS 14 (recommended) or wait for the latest update to be approved by Apple.

This issue only affects iOS 13.

**Comment by cgutman** [comment]
v7.0.2 is live on the App Store with the fix.
