### ISSUE TITLE
Requesting more relevant iOS resolutions

### ISSUE THREAD

**Issue by brianbauer42** [moonlight-stream/moonlight-ios#442]
I would really appreciate the addition of different resolutions. Either a custom resolution, or perhaps the ability to detect the resolution of the device the app is running on. The jump from 1080p to 4k is pretty large, and while they are common resolutions on televisions, they are not used on any iPads or iPhones. 16:9 is also not the correct aspect ratio for any iPad or iPhone.

I was thrilled to see how well Disco Elysium played with touch on a 2018 iPad Pro 11", but the 16:9 aspect ratio feels very restricted and there's a lot of wasted screen. On a handheld size device, it's important to use every pixel you've got, so I set a custom resolution in nvidia control panel to the native resolution of my iPad, launched Disco Elysium and was able to set it to the same - 2388 x 1668. 

Awesome!

But wait... Moonlight will only stream 1080p or 4k :( Sad times.

Otherwise, this project is awesome! I find the streaming to be much smoother than with Steam Link.

**Comment by bakedChicken** [comment]
Hello. I was able to make Moonlight for iOS app run stream in iPad 11" 2020 native (2388x1668) resolution.
As you mentioned I also have to change my monitor resolution to 2388x1668.
You can see how GTA IV is running with these settings:

![C2EC868F-9B84-4938-9291-0A3AEC750CB2_1_105_c](https://user-images.githubusercontent.com/22817721/107450137-88269c00-6b66-11eb-8117-3c4b34313430.jpeg)
![98C97644-455D-4920-94B0-E1A5480A5ED7_1_105_c](https://user-images.githubusercontent.com/22817721/107450153-8fe64080-6b66-11eb-9a31-1f4d994f98b2.jpeg)

Clearly there is issue, I believe no game is designed to be run in 199/139 aspect ratio.
Do you think is it worth to play game like this?
Thanks.

**Comment by cgutman** [comment]
Custom resolutions are supported in v8.0.0
