### ISSUE TITLE
Double Tap Menu Button on Apple TV Remote No Longer Works (tvOS 14.5)

### ISSUE THREAD

**Issue by jetbootjack** [moonlight-stream/moonlight-ios#456]
The double tap menu button functionality to flip back to the Moonlight UI on Apple TV no longer works for me on tvOS 14.5 - using a Siri Remote, old style remote to Harmony in BT mode - on both current Apple TV 4K or Apple TV HD.

sTeVE

**Comment by cgutman** [comment]
It appears impossible to intercept the Menu button now, so I have switched the exit button to be the Play/Pause button.

**Comment by jetbootjack** [comment]
Fantastic - thanks for the update!

sTeVE
