### ISSUE TITLE
ios version Never drop frames please add mod!!! 

### ISSUE THREAD

**Issue by jjangse777** [moonlight-stream/moonlight-ios#459]
Thank you very much for your work. It's a miracle, but there are still some questions.
The IOS version of moonlight does not have the option of "Never drop frames".

 Even if the network is perfect, there are still some frame dropouts, while the Android version is better. Is it because of the limitation of IOS that it is impossible to have options?

 

Never drop frames please add mod!!!

**Comment by rettgerst** [comment]
seconding this issue. I'm new to game streaming and I've spent some time trying to debug the stuttering in the moonlight client on my ATV. I also own a shield tv - the "nvidia games" client is smooth, the moonlight for android on the same device stutters unless I turn "never drop frames" on, which only adds a very small bit of latency. it seems that stuttering is a common issue with moonlight on ios/tvos and I wonder if adding the "never drop frames" option would be an acceptable solution.

**Comment by cgutman** [comment]
Fixed by #482
