### ISSUE TITLE
fn-keys on iPad

### ISSUE THREAD

**Issue by fritzchentastig** [moonlight-stream/moonlight-ios#462]
**Is your feature request related to a problem? Please describe.**
I am using an iPad7 with an Logitech KeyboardCase and i can‘t use the fn-keys. This is very annoying because i can‘t even use the esc-key. 

**Describe the solution you'd like**
A good solution would be a small row withe the fn-keys in it. 

**Describe alternatives you've considered**
An alternative solution would be keycombinations. 

**Additional context**
I saw 2015 was a similar feature request but there was never an answer to it.

**Comment by don17sch** [comment]
I was just looking to make this feature request. If we could have some form of function keys it would really help with control over our pc from an iPad

**Comment by EhsanWaheed** [comment]
Agreed it would be a good addition to have some sort of hotkey access for the function keys. Maybe something like ctrl shift one for f1
