### ISSUE TITLE
Touch Input Bug with Custom Resolution

### ISSUE THREAD

**Issue by ElijahDev** [moonlight-stream/moonlight-ios#465]
**Describe the bug**
The Moonlight client only supports streaming in 16:9 resolutions, but read that custom resolutions are supported by simply adding a custom resolution to Nvidia Control Panel. This way you're able to get full screen support. I believe this works fine for games you'd use a controller for, but causes a problem for touch input. The touch input seems to follow the streaming resolution, so most touch inputs are not aligned correctly. (Unless, you're clicking at top or bottom, they're aligned just by the fact they're at top and bottom, and can't be aligned any worse because of it they're already at the limits)

**Steps to reproduce**
Start a stream and use touch input, set PC to custom resolution that isn't 16:9 (I've used a few to test, but specifically the native resolution of the iPad Pro 12.9 (2732x2048)) Then try and click, you'll notice the cursor presses in the wrong position.

**Screenshots**
Don't think a screenshot would be of benefit here.

**Affected games**
Affects every game, as it's tied to the touch input location. I'm guessing the touch input is based on the streaming aspect ratio, thus causing the misalignment.

**Other Moonlight clients**
- Doesn't seem to be a problem when streaming to Android, I have a Galaxy Tab S7. That client has the option to start the stream in native resolution though, so that probably fixes that?

**Moonlight settings (please complete the following information)**
- Touch input enabled
- Changed Windows Resolution away from streaming resolution Aspect Ratio
- Still happens with a fresh install.

**Device details (please complete the following information)**
 - iOS 14.7.1
 - iPad Pro 12.9 4th Gen (2020)

**Server PC details (please complete the following information)**
 - Windows 10 21H1
 - GeForce Experience version: 3.23.0.74
 - Nvidia GPU driver: 461.40
 - Windows Defender and Windows Firewall

Thank you in advance for any help. I hope there's enough information to go on.

If it helps, Rainway (Streaming client also) manages to stream in a 4:3 aspect ratio, but won't go up to 2732x2048 as it doesn't support anything above 1080p. That client therefore gives you a 1280x960 resolution, which isn't the best!

**Comment by J1aDong** [comment]
+1

**Comment by ElijahDev** [comment]
Went through the tiresome task of getting MacOS Big Sur installed in Virtual Box and getting Moonlight to build, and installing it to device with AltStore. I managed to use the code from the open pull request to add native resolution streaming.

The native resolution streaming code fixes the touch input bug. I think it would have already been accepted if the labels in the settings was tidied up. I might look into tidying up the label and open a pull request.

This might have already been known, and I suggested it as a possible fix initially, but wanted to confirm it. Also means I can start using the full screen of my device with touch, without waiting for an official update.

**Comment by cgutman** [comment]
This bug happens because AVSampleBufferDisplayLayer is actually parsing the original dimensions out of the video bitstream and stretching the video content back to the original aspect ratio. No other platform's video APIs seem to do this, and I don't think there's a way to opt out.

It's actually a fancy feature for AVSampleBufferDisplayLayer, but it breaks Moonlight's mapping between video position and touch position as a side-effect. As @ElijahDev mentioned, the way to fix this is to get native resolution support in.

**Comment by ElijahDev** [comment]
> This bug happens because AVSampleBufferDisplayLayer is actually parsing the original dimensions out of the video bitstream and stretching the video content back to the original aspect ratio. No other platform's video APIs seem to do this, and I don't think there's a way to opt out.
> 
> It's actually a fancy feature for AVSampleBufferDisplayLayer, but it breaks Moonlight's mapping between video position and touch position as a side-effect. As @ElijahDev mentioned, the way to fix this is to get native resolution support in.

With regards to the open pull request for this, are you just wanting the actual selection of the resolution cleaning up? As the actual streaming seems fine.

If you're wanting it more tidy, which of the following were you thinking;

- The labels don't fit too well for the resolutions, we could make the pull out section wider?
- Change it to a different style selector which would fit multiple options better?
- What about an X and Y resolution input boxes, that can be pre filled with buttons for 4K, Native, 720P, 1080P etc? This would allow the user to select any resolution they wanted with typing it in to the box in addition for people wanting one of the defaults, can click a button to auto fill with correct dimensions?

If I know what you'd like to accept the request, I'll see what I can do.

**Comment by cgutman** [comment]
All of those options sound great. If you want, you could do a mockup in Xcode of a couple of the designs just to make sure it all looks good before wiring it up.

One thing I will need to add is a warning dialog similar to the one that Android and Qt clients have (basically just noting that native resolutions aren't officially supported, setting resolutions that aren't supported by your host display may cause problems, you'll need to set your resolution manually in-game, etc.) If you can leave me a spot to hook that up, I can do that once your PR is merged.

**Comment by HariboApfel** [comment]
its kinda frustrating to see an working open pull request left in the dust (with important functionallity) just for whatever? the easy solution is to make the settings area wider. if you then want to add some bells and whistles thats ok. but get out the functionallity a contributer used their valuable time on. its not like there are any costs associated with pushing this update. 

hope there will be a merge soon.

BR

**Comment by lightsabata** [comment]
+1

**Comment by lightsabata** [comment]
> Went through the tiresome task of getting MacOS Big Sur installed in Virtual Box and getting Moonlight to build, and installing it to device with AltStore. I managed to use the code from the open pull request to add native resolution streaming.
> 
> The native resolution streaming code fixes the touch input bug. I think it would have already been accepted if the labels in the settings was tidied up. I might look into tidying up the label and open a pull request.
> 
> This might have already been known, and I suggested it as a possible fix initially, but wanted to confirm it. Also means I can start using the full screen of my device with touch, without waiting for an official update.

I follow your advice et build a version from branch 473, it work like a charm on ipad pro M1 12.9, thanks !
hope to see it on official release

**Comment by cgutman** [comment]
Fixed by f21c58306ed73ffdffe79f1d7ee5f9144f1ed646
