### ISSUE TITLE
Xcode 13 Support

### ISSUE THREAD

**Issue by astromonkee** [moonlight-stream/moonlight-ios#468]
There's currently an issue with building the project using Xcode 13 due to one of the changes introduced in Swift 5.5. 
The issue occurs on the X1Kit submodule. 
I've sent a [PR](https://github.com/fizzyade/X1Kit/pull/3) to fix it and hopefully we can just update the submodule reference if it's merged.

**Comment by redlinejoes** [comment]
I ran into a build issue with X1Kit and Swift on Xcode 13 as well. I was also able to resolve it too.

**Comment by don17sch** [comment]
@astromonkee it may be better to fork X1kit. it has not had an update in several years.

**Comment by cgutman** [comment]
Fixed in c930a4656a55841ea2304e1f85a0c98ae17d368c by switching to my fork of X1Kit with @astromonkee's patches.
