### ISSUE TITLE
Scrolling doesnt work in iPadOS 15

### ISSUE THREAD

**Issue by JasonS7notG5** [moonlight-stream/moonlight-ios#471]
I am using the latest Windows 10 version, the newest GeForce Experience version and NVIDIA driver, and the newest Moonlight build on the Apple App Store. My iPad is on iPadOS 15.0. Scrolling works inside iPadOS (native) apps like Safari. I have two mice which I tried, the M590 - in Bluetooth and in Unifying mode (USB-C to USB-A adapter) - and the G305. Scrolling used to work before. It could be possible that iPadOS 15 changed something, maybe API related? But even before, it didnt worked as smoothly as directly connected to the PC, it was like half the speed on iPad for the same amount of scrolling. Scrolling with the Magic Keyboards touchpad works inside Moonlight.

Not scrolling but mouse related:
-Mouse cursor is on point when clicking on UI elements but not when trying to highlight or edit text (Firefox, Chrome, Word, etc.), maybe it has something to do with the cursor design changing to the "I" symbol. I also noticed this when the cursor changes to the hand symbol with the index finger pointing where to click. But I guess this is something NVIDIA needs to fix (as I read it here and on the NVIDIA forums).

**Comment by Alban42** [comment]
> Scrolling with the Magic Keyboards touchpad works inside Moonlight.

The vertical scrolling works or is it the horizontal scrolling ?

**Comment by JasonS7notG5** [comment]
The regular, vertical scrolling with two fingers on the Magic Keyboard works just as intended and same in iPadOS, Safari etc. and in Moonlight. I turned of natural scrolling in the iPadOS mouse settings.

**Comment by cgutman** [comment]
Fixed in d7cf8ced2505ad56c8e90ad5f35564b71398ad30

It looks like iPadOS 15 broke discrete scroll events in GCMouse. They will probably fix it eventually, but we can just use the old UIPanGestureRecognizer for that to workaround the issue. That's what SDL (and Steam Link) does.
