### ISSUE TITLE
ATV4K  - tvOS 15 - Moonlight settings reset to default

### ISSUE THREAD

**Issue by HakanFly** [moonlight-stream/moonlight-ios#472]
Hello

**Describe the bug**
- Moonlight settings reset to default when I restart app. (1080p, 20 mbps bitrates etc)

**Steps to reproduce**
1) For example, I set 4K resolution, 150 mbps bitrates. (The application works as expected)
2) I close the app in the background or restart my Apple TV 4K.
3) I launch Moonlight app and go to settings menu.

**Moonlight settings (please complete the following information)**
- Focusing only to change resolution and bitrates

**Device details (please complete the following information)**
 - tvOS 15
 - ATV4K (1st Gen)

**Server PC details (please complete the following information)**
 - Windows 10 1809
 - GeForce Experience version: 3.23.0.74
 - Nvidia GPU driver: 472.12
 - Antivirus and firewall software: Windows Defender and simplewall

**Additional context**
- I think it's been doing that to me since the tvOS 15 update. 
- No recent app update or reinstallation.

**Comment by RaunoT** [comment]
Can also reproduce, like @felipejfc said, it appears that they only visibly "reset" to default values, but don't actually take effect.
