### ISSUE TITLE
(iPadOS 14.7.1) Audio and video stutter every second

### ISSUE THREAD

**Issue by DJLevel3** [moonlight-stream/moonlight-ios#475]
I'm on a network other than the network my computer is on, using ZeroTier to remote in, and I'm getting a very strange issue. Every second almost exactly, the video and audio stutter momentarily. How much they stutter depends on what's on-screen, but it always happens on a rhythm every second.

I haven't tested anything other than mstsc.exe, as that's what I was using before I screwed up my PC's internet settings and disconnected the remote from the internet.

Here are my findings and my theory as to what the problem is:

- The stutters seemed to be worst when I was using a software with an image of lots of tiny stars on a blue background, and best when viewing about:blank in full screen (I used audio to tell how long the stutters were) so I think that the issue is with the iPad's video decoder.
- It happened on both the default decoder and HEVC, on every bitrate I tested that worked at all (I was getting slow connection issues over about 50 Mbps, probably due to ZeroTier) and at 1080p, 720p, and 360p resolutions. I didn't test 4K since I don't have a 4K monitor on either end.
- If the problem is the iPad's decoder, than it's not easy to entirely eliminate the issue, but if I understand compressed video streams correctly than it should be possible to add an option to buffer the video for like .1 to .25 seconds so that the stutters are resolved by the time they get displayed.

I'm able to live with it for now, I'm just putting in on your radar.

**Comment by Lucke0051** [comment]
I'm having this exact issue on my Apple TV 4K. I have no stutter or lag when I try it on my laptop conntected to the same access point.
