### ISSUE TITLE
iPhone: Audio only works with airpods (bluetooth), not internal speakers or wired headphone

### ISSUE THREAD

**Issue by heronemis** [moonlight-stream/moonlight-ios#479]
On iPhone specifically, audio only works when using Airpods (over bluetooth). I can not get sound to play from the iphones built in speakers or through wired headphones. Audio works fine when using Moonlight on both an iPad and Apple tv. This issues occurs both on iPhone 11 pro max as well as iPhone 13 pro max on Moonlight version 7.2.0, running iOS 15.1.1. I have tested starting Moonlight with the silent switch both on and off.

**Comment by cgutman** [comment]
Should be fixed in v8.0.0. Let me know if it's not.
