### ISSUE TITLE
Native resolutions.

### ISSUE THREAD

**Issue by lateforwork1000** [moonlight-stream/moonlight-ios#480]
Will there be an option for iOS devices for native resolution? Just like with android.

**Comment by TizianoMattei** [comment]
you're better off using workarounds like CRU to force a different resolution on you host machine, rather than waiting an update, there are a lot of issues open with this request and it doesnt look like its gonna be a thing

**Comment by lateforwork1000** [comment]
Thanks for the response 
I did fine this

https://github.com/pierguil/moonlight-ios/tree/1440p

This is a fork from this post

https://github.com/moonlight-stream/moonlight-ios/issues/393

in the pass I have build custom versions for android and I was thinking of trying to build a custom version to support native resolution but I don’t know much about Xcode so I was thinking of using the fork as a reference as where i should make changes. 
 But I was really hoping the developer would add it in soon.

**Comment by thomasaull** [comment]
There is an open PR which provides this functionality, but it does not look like it'll get merged anytime soon unfortunately :/

https://github.com/moonlight-stream/moonlight-ios/pull/476

**Comment by AlexKuai** [comment]
I think it is necessary to support native resolution. After all, IOS devices are not in the conventional 16:9 ratio.

I really hope to provide native resolution options!

**Comment by hbouhadji** [comment]
the pr has been merged, you can use custom resolution (and custom aspect ratio also). you can try by building the app yourself, hopefully we get the release on the store soon

**Comment by AlexKuai** [comment]
When will it be released to the Appstore?

**Comment by cgutman** [comment]
v8.0.0 has passed Apple review and is now live on the store.
