### ISSUE TITLE
No audio after switching to SDL on AppleTV 4K (tvOS 15.2)

### ISSUE THREAD

**Issue by Aljutor** [moonlight-stream/moonlight-ios#484]
Tested current master [bd582aa](https://github.com/moonlight-stream/moonlight-ios/commit/bd582aa6c0c0e4db283c166395ef3d362201fcc6) on Apple TV 4K (2 gen) with tvOS 15.2 and found out that there no audio. Version from AppStore works fine. To additionally clarify issue I branched before SDL2 commits [8391c76](https://github.com/moonlight-stream/moonlight-ios/commit/8391c766c7545f6d041528dfbbaa4a9c9ecd34b6) cherry picked bd582aa onto it and tested this version, audio works fine.

**Comment by cgutman** [comment]
Yep, this is a known issue related to #371. We won't release a new build on the App Store until it's fixed.

**Comment by cgutman** [comment]
Fixed by 701c83d79c828cdff2191ba77e89fa5132c5bb83
