### ISSUE TITLE
Improved Wake on Lan

### ISSUE THREAD

**Issue by cbrenberg** [moonlight-stream/moonlight-ios#488]
**Is your feature request related to a problem? Please describe.**
Moonlight on iOS is unable to wake my PC over LAN, presumably because it isn't set up to use the correct combination of port and IP for my setup. Other dedicated wake on LAN software does reliably wake the PC when set to use port 7 on the subnet's broadcast IP (192.168.0.255 in my case), but I find that sending the magic packet to the host PC's IP address (192.168.0.1xx in my case) directly doesn't always work, nor does 255.255.255.255, regardless of which port is used.

**Describe the solution you'd like**
To more universally handle wake on LAN for more users, I propose adding port 7 (a common WoL port) to the list of ports and also broadcasting the packet to the host PC's subnet broadcast address (192.168.0.255 in my case) in Limelight/Network/WakeOnLanManager.m

**Describe alternatives you've considered**
Alternatively (or in addition), it would be nice to be able to customize the wake on LAN behavior through the app's settings to choose a custom IP and port for individual use cases.

**Comment by cgutman** [comment]
Apple requires a special entitlement to send broadcast traffic (as of iOS 13 IIRC). We don't have it, so that's probably the issue here.

**Comment by brunosmarques** [comment]
I can't use this function as well. Works great with iOS on my iPhone 11, but not on my Apple TV 4k 2021.

**Comment by cbrenberg** [comment]
Unless there's a path forward for sending broadcast traffic in more recent versions of iOS, I'll close this issue due to inactivity
