### ISSUE TITLE
add 1440p streaming; add native resolution option for streaming

### ISSUE THREAD

**Issue by rayvearn** [moonlight-stream/moonlight-ios#490]
**Is your feature request related to a problem? Please describe.**
1080p is too soft at times, and doesn’t take up the iPad Pro’s whole screen, and 4K is too bandwith heavy.

**Describe the solution you'd like**
1440p option for quality, or at least a native resolution option for your device (or custom resolutions).

**Describe alternatives you've considered**
Native device resolution (virtual display) or just different resolution options.

**Additional context**
Heavy bandwith use with 4K which can flood the VRAM. 1440p seems to be the sweet spot.

**Comment by rayvearn** [comment]
ik there’s already an issue for native res, i just added that as an alternative

**Comment by hbouhadji** [comment]
custom resolution is available now on master, you can try or wait for the next release

**Comment by AlexKuai** [comment]
That's great

**Comment by cgutman** [comment]
This is supported in v8.0.0.

**Comment by ddulic** [comment]
I am running v8.0.0. on tvOS, but don't see this option. Has this been released for tvOS?

**Comment by cgutman** [comment]
This is released in v8.2.0.
