### ISSUE TITLE
Problem uploading to AppStore

### ISSUE THREAD

**Issue by quandd95** [moonlight-stream/moonlight-ios#500]
Hello,
I'm having trouble uploading to the AppStore.
App rejected on VPN Services issue. Apple requires the use of the NEVPNManager API. I can't find what vpn service moonlight is using

**Comment by don17sch** [comment]
why are you trying to upload to the app store? I thought that @cgutman was the one who uploads builds to the app store?

**Comment by cgutman** [comment]
>  why are you trying to upload to the app store? I thought that @cgutman was the one who uploads builds to the app store?

Indeed

> App rejected on VPN Services issue. Apple requires the use of the NEVPNManager API. I can't find what vpn service moonlight is using

Moonlight doesn't use any VPN services.
