### ISSUE TITLE
iOS 4.1 Custom Resolution bug

### ISSUE THREAD

**Issue by AlexAnorak** [moonlight-stream/moonlight-ios#505]
Hello,

i'm using an iPad Pro 2020 11inch
+ PadOS 15.4
+ native resolusion 2388*1668

i'm using a HDMI dummy,so i change the resolution in NVIDIA controller into 2388*1668, thus the screen displays the full area in iPad

After updating to v4.1,no resolution could display fully,so i turn to custom resolution,and it works well till yesterday,with no reason it crushed.

now the situation is

|NVIDIA resolution|Moonlight resolution|result|
|:--:|:--:|:--:|
|4k|custom`2388*1668`|fine|
|custom`2388*1668`|4k|fine|
|custom`2388*1668`|custom`2388*1668`|terminated|
|custom`2388*1667`|custom`2388*1668`|fine|

**Comment by cgutman** [comment]
These custom resolutions are not supported by Nvidia so it's possible that some combinations of resolutions just won't work, but I can try to see if there's anything obvious in your Nvidia streamer logs.

After triggering the bug, please attach the log files from `C:\ProgramData\NVIDIA Corporation\NvStream`.

**Comment by felipejfc** [comment]
@cgutman I bet that this is actually due to him using HDR o'n. There is some report here in some issue already and I'm also suffering from it. When you use custom stream resolution = windows resolution and HDR=on then the connection is terminated.
@op can you confirm this? Do you have HDR on?

**Comment by AlexAnorak** [comment]
@felipejfc oh,yes.i turn off HDR then the connection is NOT terminated anymore.

**Comment by AlexAnorak** [comment]
oh, i have checked that closed issue, it’s the same problem, i will close the issue but i still think it’s a bug of something, maybe geforce or gpu driver.

Thanks to the developers and all contributors, Moonlight is going better and better.
