### ISSUE TITLE
Custom Steam Input Controller Profile Not Working

### ISSUE THREAD

**Issue by MrProphet** [moonlight-stream/moonlight-ios#506]
**Describe the bug**
Not able to apply custom steam input layout profiles for controller. Only default controller layout for games.

**Steps to reproduce**
For any game, create a steam controller input profile. Run the game using moonlight for ios/Android (Tested both).

**Affected games**
Fallout 4, Apex Legends

**Other Moonlight clients**
- Does the issue occur when using Moonlight on PC or Android?
Android and iOS versions are tested

**Moonlight settings**
- Have any settings been adjusted from defaults?  no

**Gamepad-related issues (please complete if problem is gamepad-related)**
- Do you have any gamepads connected to your host PC directly? no
- If gamepad input is not working, does it work if you use Moonlight's on-screen controls? input is working, layout is wrong.
- Does the problem still remain if you stream the desktop and use https://html5gamepad.com to test your gamepad? A website is not applicable with steam input to my knowlege.

**Device details (please complete the following information)**
 - iOS/tvOS version: iPadOS 15.4.1
 - Device model: iPad Pro 2018(11 inch)

**Server PC details (please complete the following information)**
 - OS: Windows 10 21H1
 - GeForce Experience version: 3.25.1.27
 - Nvidia GPU driver: 511.79
 - Antivirus and firewall software: Windows Defender and Windows Firewall

**Comment by cgutman** [comment]
This sounds like a Steam issue, no?

**Comment by MrProphet** [comment]
> This sounds like a Steam issue, no?

Err, no because when not streaming, custom layout works just fine.

**Comment by MrProphet** [comment]
@cgutman  I think the issue here might be the emulation layer not being identified by steam.

> > This sounds like a Steam issue, no?
> 
> Err, no because when not streaming, custom layout works just fine.

**Comment by cgutman** [comment]
Yeah that’s what I was thinking, though it appears to work fine for me with the latest Steam Beta client.

I get the little steam controller profile notification when I start a game or connect a controller.

**Comment by MrProphet** [comment]
> I get the little steam controller profile notification when I start a game or connect a controller.

The profile notification works for me too, but it's not actually applying the profile. I'll try using steam beta version.

**Comment by cgutman** [comment]
The profile was working for me when I played Witcher Enhanced Edition through Steam.

**Comment by cgutman** [comment]
Any luck?

**Comment by MrProphet** [comment]
Negative cgutman, Using steam Beta version doesn't seem to be fixing this issue.

**Comment by cgutman** [comment]
OK, I recommend asking on the Steam forum then. They have had interoperability bugs with GameStream before (particularly with the Xbox Configuration Support and Xbox Extended Feature support).

This is how my setup is configured:
![image](https://user-images.githubusercontent.com/2695644/171071148-dc31ff5c-bae1-496d-84de-45840b85d3f3.png)

You may try toggling some of those options, but the options as shown worked fine for Witcher Enhanced Edition.

**Comment by MrProphet** [comment]
Update: The issue resolved for fallout 4 after a bit of tinkering. The fix could be one or several methods listed below.

What I did:
- reinstalling windows 10 & GFE
- reinstalling steam and add previous game library to fresh install (save the time redownloading the game)
- if you mod games like Fallout 4/Skyrim with mod organizer, add mod organizer into your steam library, and tweak the gamepad profile from there (instead of base Fallout4.exe)
- deselect this option in steam big screen mode (Translates as "Allow desktop configuration in launcher")
![image](https://user-images.githubusercontent.com/72962885/177037894-5209cde8-5e03-4aa0-86ec-ebfeccb1fad3.png)
