### ISSUE TITLE
Screen frozen with version 8.4.0 when streaming from Sunshine

### ISSUE THREAD

**Issue by mmm-mb** [moonlight-stream/moonlight-ios#538]
With the latest version the screen doesn’t update anymore, it shows a still image of my desktop but I can see that input still works fine when I look at the host’s display.
I’m using an iPad Air 5 with iPadOS 16 to connect to a Linux host running Sunshine.
I built version 8.3.1 using a virtual machine and it works fine.

**Comment by neatnoise** [comment]
I confirm, the latest [subshine ](https://github.com/LizardByte/Sunshine/releases) , arch Linux with kde. After the update of the recent version of iOS moonlight client, it renders only the first frame and then got stuck. It seems to send input signals but the screen is not updated.

I will mention also a long term minor issue (with also previous versions) with the signal sending when I want to move a window with one tap and move. It works well on windows with sunshine, but on Linux it doesn’t move a window. I use a workaround which is right click on the window and choose option move the window

**Comment by Teonyr** [comment]
Yes, I'm running sunshine (rpm) on Nobara Linux host with an iPhone and AppleTV as clients.

**Comment by xiaohaoxiang** [comment]
I meet this problem after update iPhone app too. Any way to solve this?

**Comment by tylerstalder** [comment]
> Can any of you with sunshine host try to compile and run from my Fork's main repo and see if it fixes the problem? [here](https://github.com/felipejfc/moonlight-ios/)
> 
> EDIT: If it doesn't please Log the "pts" value received in the function I changed and report the values here

@felipejfc I'm getting the same behavior running your fork on iOS as I am with the current app store build. I can connect to the sunshine host but only the first frame is displayed and it does not update. I did confirm that my inputs are being sent to the host by checking the host's display (mouse cursor moves with touch screen input from the phone).

From the logs it looks like the value of `pts` is zero.

```
2022-12-06 12:48:58.265769-0800 Moonlight[19261:6462513] <INFO> Logging pts from sunshine: 0
2022-12-06 12:48:58.266008-0800 Moonlight[19261:6462513] <INFO> Logging sample timing from sunshine: 1807212136
```

I'm not an iOS developer so worth checking that my logging is correct:
```objc
    Log(LOG_I, @"Logging pts from sunshine: %d", pts);

    if(pts <= 0){
        sampleTiming = (CMSampleTimingInfo){kCMTimeInvalid, CMTimeMake(pts, 1000), kCMTimeInvalid};
    } else {
        sampleTiming = (CMSampleTimingInfo){kCMTimeInvalid, CMClockMakeHostTimeFromSystemUnits(mach_absolute_time()), kCMTimeInvalid};
    }
    
    Log(LOG_I, @"Logging sample timing from sunshine: %d", sampleTiming);
```

This is from an iOS client connecting to a Windows Sunshine host.

**Comment by felipejfc** [comment]
f***, I'm dumb, the if was with inverted logic, should be if pts>0 use pts :p 
can you retry it? be aware I force pushed, so you may run intro trouble only pulling from my repo, do a new clone instead

**Comment by cgutman** [comment]
I fixed this in https://github.com/moonlight-stream/moonlight-common-c/commit/bc00d957d34cb6d66b7638fdf63282b7d0210f80.

v8.4.1 is now submitted to Apple for review with this bugfix.
