### ISSUE TITLE
Start+Select+L1+R1 for quitting

### ISSUE THREAD

**Issue by midpl0x** [moonlight-stream/moonlight-ios#548]
Would it be possible to add this functionality to the tvOS app? It's working absolutely perfect on the PC-client, and the input is not used for anything else in the tvOS version of the app. 

It's mainly just a quality of life thing, but it would be greatly appreciated.

**Comment by midpl0x** [comment]
Thank you @cgutman. This change will be greatly appreciated at my house, and probably a lot of places. 

When are updates expected to be rolled out? I can see that the last update to the app-store was dec 7. (not saying its overdue, I'm just curious!) 

Again, thank you!

**Comment by cgutman** [comment]
It's live on the App Store now.
