### ISSUE TITLE
Why isn’t there deciding time in stats?

### ISSUE THREAD

**Issue by maxiedaniels** [moonlight-stream/moonlight-ios#551]
I’m desperately trying to figure out if my latency issue is due to using an Apple TV 4K 2017 (1st gen of the 4k), but I can’t see decoding time. Is there no way to enable it??

**Comment by cgutman** [comment]
No, the `AVSampleBufferDisplayLayer` API that we use for decoding doesn't provide decode latency information.

We may move to using `VTDecompressionSession` which does allow us to get this info, but for now it is not available.
