### ISSUE TITLE
Moonlight on WebOS TV 4.5 crash on every single instance

### ISSUE THREAD

**Issue by ozankaruk** [moonlight-stream/moonlight-ios#555]
I've recently finished setting up Moonlight for a Led 4K TV which runs on LG WebOStv 4.5.

I have an RTX 2060 PC which runs on windows 11. Both are connected through a 5Ghz wi-fi network in the same house.

However, I couldn't get even a single second of a stream. I don't know what the problem might be. I've made the additions to GFE Shield games .exe list. My TV recognize the game, my pc runs the game, but when I try to play it from the TV, Moonlight crashes and TV returns back to its standart TV mode.

I use another third party WebOS app to connect my Xbox one gamepads through bluetooth to the TV -which seem to be working fine. I don't know if those could be the reason behind this issue.

Another thing that I noticed is the streaming protocols of my TV looks like not supporting h265 streaming standart. However, I can't change h265 streaming option, it's unclickable. This would be my guess, but what do I know anyways...

BTW: Yes, I disabled HAGS.

Is there anybody who can help? I'm pretty new in moonlight and I don't know a single bit of software coding. I'd really appreciate if anyone could provide any assitance.

**Comment by cgutman** [comment]
This is the iOS/tvOS Moonlight project. You probably intended to file the bug on https://github.com/mariotaku/moonlight-tv
