### ISSUE TITLE
Mouse/Keyboard inputs stop during UAC (no dimming)

### ISSUE THREAD

**Issue by gtkashi** [moonlight-stream/moonlight-ios#560]
**Describe the bug**
When a UAC prompt appears, I am unable to interact with it or anything else (mouse, keyboard, touch screen). Current settings on host machine (Windows 11) are to show UAC, but not dim the screen (allowing it to dim the screen causes full disconnects for me).

**Steps to reproduce**
Trigger any UAC prompt in Windows 11.

**Device details (please complete the following information)**
 - iOS 16.2
 - iPad Pro (11 inch 3rd gen)

**Server PC details (please complete the following information)**
 - OS: Windows 11
 - Using Sunshine
 - Antivirus and firewall software: Windows Defender and Windows Firewall

**Comment by cgutman** [comment]
This is a Sunshine issue not a Moonlight bug.

It's likely because you're not using the installed version of Sunshine, which runs at a high enough privilege level to interact with UAC prompts.
