### ISSUE TITLE
Add wireless controller joysticks dead zone setting

### ISSUE THREAD

**Issue by xuan-w** [moonlight-stream/moonlight-ios#573]
Moonlight tvOS by default seems to impose a quite large controller joystick dead zone. When I switch to Android moonlight, l learned that the default is 7%. This dead zone is often too large for games need accurate aiming. 

I can confirm that there is an additional dead zone in tvOS moonlight, though I have no idea the default number. 
Test method: connect the controller to PC and open gamepad tester, there is no dead zone. Connect the controller to Apple TV, open moonlight to connect to PC and open gamepad tester, there is a significant central dead zone. 

**Describe the solution you'd like**
It'd better to have an option for the connected wireless game controllers like moonlight Android. 

**Additional context**
I have tried to set the controller dead zone to 0 everywhere, it is still too large.

**Comment by cgutman** [comment]
We don't actually enforce a deadzone on the iOS/tvOS client, so it must be host-side or in the OS itself.

**Comment by xuan-w** [comment]
Thank you! Eventually I was able to locate the problem: it seems iOS/iPadOS/tvOS themselves impose a quite large dead zone. 
The only work around is to use a user configurable controller and set the controller to report around 20% when it is actually reading 0% or 1%. 
Hope this information can be helpful for others facing the same issue.

**Comment by xuan-w** [comment]
Since this is not a problem that moonlight client can help, I am closing the issue.
