### ISSUE TITLE
After updating to apple tvos17, cannot stream sound.

### ISSUE THREAD

**Issue by ZenderHUANG** [moonlight-stream/moonlight-ios#583]
I tried everything including: reinstalling sunshine and TV version of moonlight, installing the nightly version of sunshine, specifying the sound device id, but none of them worked. It was working fine with the default configuration before the tvos update. The content in the log looks normal too.

**Device details (please complete the following information)**
 - iOS/tvOS version: 17.0

**Server PC details (please complete the following information)**
 - OS: win 11 25951.1010
 -GPU:intel a770

**Comment by linuzel** [comment]
I have the same issue but here are a few findings :
- Sound actually works with AirPods connected to the AppleTV
- When I disconnect the AirPods, audio works on the TV until I close the App
- Even with AirPods it seems to be stereo only

**Comment by ZenderHUANG** [comment]
> I have the same issue but here are a few findings :
> 
> * Sound actually works with AirPods connected to the AppleTV
> * When I disconnect the AirPods, audio works on the TV until I close the App
> * Even with AirPods it seems to be stereo only

Did your issue only occur after upgrading to tvOS 17 too? I don’t have AirPods, but my Android phone runs Moonlight well in streaming to the same PC.

**Comment by cgutman** [comment]
What model of Apple TV do you have? Are you using Stereo or one of the surround modes in Moonlight settings?

I'm testing on an Apple TV 4K (3rd generation, A2843) connected to a Samsung S95B and audio is working fine for me on tvOS 17.0 using both Stereo and 5.1 settings in Moonlight.

**Comment by ZenderHUANG** [comment]
> What model of Apple TV do you have? Are you using Stereo or one of the surround modes in Moonlight settings?
> 
> I'm testing on an Apple TV 4K (3rd generation, A2843) connected to a Samsung S95B and audio is working fine for me on tvOS 17.0 using both Stereo and 5.1 settings in Moonlight.

I'm testing in apple tv 4k 3rd too，it link too ffalcon tv and q600c.
![IMG_20231002_202327](https://github.com/moonlight-stream/moonlight-ios/assets/129350889/5aedee1b-a02d-467c-915a-e6e8d21119a2)
![IMG_20231002_202330](https://github.com/moonlight-stream/moonlight-ios/assets/129350889/22c150de-cd9d-4500-87e5-3780af58ed77)

**Comment by ZenderHUANG** [comment]
> What model of Apple TV do you have? Are you using Stereo or one of the surround modes in Moonlight settings?
> 
> I'm testing on an Apple TV 4K (3rd generation, A2843) connected to a Samsung S95B and audio is working fine for me on tvOS 17.0 using both Stereo and 5.1 settings in Moonlight.

I try Stereo and 5.1 all can't work

**Comment by ZenderHUANG** [comment]
The audio streaming is work well now... I guess it maybe is Tv's problem,not the moonlight.
