### ISSUE TITLE
Is it possible to support paddles in Xbox Elite Controller 2?

### ISSUE THREAD

**Issue by twilightgod** [moonlight-stream/moonlight-ios#588]
**Is your feature request related to a problem? Please describe.**
I connect my Elite Controller 2 to iPad, but Moonlight thinks it's a Xbox 360 controller, so I can't use any paddles

**Describe the solution you'd like**
Moonlight should be able to detect it's a Elite Controller 2 and support the paddles

**Describe alternatives you've considered**
Not sure

**Additional context**

**Comment by cgutman** [comment]
Closing since this feature shipped in v9.0.0. Paddles now need to be implemented on the Sunshine side to work.
