### ISSUE TITLE
about Apple Pencil

### ISSUE THREAD

**Issue by AlexAnorak** [moonlight-stream/moonlight-ios#595]
I have noticed in new Moonlight iPadOS version, Apple Pencil can no longer touch screen
So, is this for pencil support like [pen pressure](https://ideas.moonlight-stream.org/posts/83/support-for-stylus-with-pen-pressure-s-pen-or-apple-pencil)?

**Comment by TheFireRed** [comment]
Following this thread too since I'm having this issue too

**Comment by cgutman** [comment]
The fix is released in v9.0.1, which is live on the App Store.
