### ISSUE TITLE
[Bug] Cannot find the host

### ISSUE THREAD

**Issue by beastybell** [moonlight-stream/moonlight-ios#62]
Hey, I have tried all beta versions with the latest gfe 2.2.2 and I get this error. The PC does not show up in the list automatically. Trying the previous GFE 2.1.1 cause my pc to show up in green, but trying to connect to it gives me error - connection refused by host. I have properly forwarded all ports in my router and also disabled firewalls and antiviruses- no dice. Please help me, because I am out of ideas. I am on ios 8.1.2 ipad air 2.

P.S. I am on GTX 970

**Comment by cgutman** [comment]
Most likely fixed
