### ISSUE TITLE
Mouse support for Apple tv 

### ISSUE THREAD

**Issue by Make31** [moonlight-stream/moonlight-ios#622]
Is it possible to add mouse support for Apple TV? It should be supported by tvOS, but it needs to be implemented in Moonlight. With the touchpad on the remote, it is possible to simulate the mouse in Moonlight, but it is very inconvenient to use. Thank you.

**Comment by cgutman** [comment]
Moonlight already implements the GCMouse API, but Apple doesn't not support mice on Apple TV.
