### ISSUE TITLE
Failed to load Legacy provider

### ISSUE THREAD

**Issue by yiluoe** [moonlight-stream/moonlight-ios#642]
This error interrupted me while I was running.

**Screenshots**
<img width="1728" alt="截屏2024-07-18 05 24 14" src="https://github.com/user-attachments/assets/f0f9714c-7857-4bf4-a9e1-3ed19508fca7">

**Device details**
- iOS/tvOS version: [iOS 17.5/18.0]
- Device model: [iPhone 14 Pro Max/Ipad Pro 2021 12.9]

**Comment by Priultimus** [comment]
Hey! I ran into the same error, wondering how you ended up fixing this / why you closed it?

**Comment by yiluoe** [comment]
> Hey! I ran into the same error, wondering how you ended up fixing this / why you closed it?

最新的提交貌似破坏了OpenSSL在IOS上的运行，所以我是在上一个提交上构建的本仓库。
