### ISSUE TITLE
On iOS 17.6, app fails to launch with OpenSSL error

### ISSUE THREAD

**Issue by suchipi** [moonlight-stream/moonlight-ios#660]
**Describe the bug**
After recursively cloning the repo by following the instructions in [the readme](https://github.com/moonlight-stream/moonlight-ios?tab=readme-ov-file#building), the app compiles successfully, but an OpenSSL error is encountered at app startup time.

The error occurs because [in Crypto/mkcert.c, `PKCS12_create`](https://github.com/moonlight-stream/moonlight-ios/blob/022352c1667788d8626b659d984a290aa5c25e17/Limelight/Crypto/mkcert.c#L85) returns null. This causes the following [`PKCS12_set_mac` call](https://github.com/moonlight-stream/moonlight-ios/blob/022352c1667788d8626b659d984a290aa5c25e17/Limelight/Crypto/mkcert.c#L96) to fail.

If I add `ERR_print_errors_fp(stderr);` to the code after the `PKCS12_create` call (and `#include <openssl/err.h>` to the top), I get:
```
4002750401000000:error:12800067:DSO support routines:dlfcn_load:could not load the shared library:crypto/dso/dso_dlfcn.c:118:
4002750401000000:error:12800067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:152:
4002750401000000:error:07880025:common libcrypto routines:provider_init:reason(524325):crypto/provider_core.c:904:name=legacy
4002750401000000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:354:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()
4002750401000000:error:11800067:PKCS12 routines:PKCS12_item_i2d_encrypt_ex:encrypt error:crypto/pkcs12/p12_decr.c:193:
4002750401000000:error:11800067:PKCS12 routines:PKCS12_pack_p7encdata_ex:encrypt error:crypto/pkcs12/p12_add.c:133:
```

**Steps to reproduce**
- Clone the repo and its submodules
- Build and Run the app it in an iOS 17.5 simulator
- Wait a couple seconds
- The debugger will reveal a `Thread 1: EXC_BAD_ACCESS (code=1, address=0x8)` error on the `PKCS12_set_mac` call in Limelight/Crypto/mkcert.c

I also encountered the same behavior on a physical device running iOS 17.6.

**Target device details (simulator)**
 - iOS/tvOS version: iOS 17.5
 - Device model: iPhone 15 Pro

**Target device details (real)**
 - iOS/tvOS version: iOS 17.6
 - Device model: iPhone 13 Mini

**Compiler machine (Xcode host) details**
 - OS: macOS Sonoma 14.4.1
 - Device model: Macbook Air M1 2020

**Comment by suchipi** [comment]
I was able to work around this by reverting 022352c1667788d8626b659d984a290aa5

**Comment by hua0521** [comment]
I encountered the same issue: In Crypto/mkcert.c, PKCS12_create returns null, causing the subsequent PKCS12_set_mac call to fail. On iOS, this might be because the Legacy provider fails to load successfully. p12 always null. Is it necessary to set environment variables? Any suggestions for a solution?

**Comment by hua0521** [comment]
You can try using a previous version.

**Comment by suchipi** [comment]
Is this gonna be a problem for older devices when they get the app from the app store, after the OpenSSL 3 change is published? iOS doesn't let you get an older version of an app, and has a setting to automatically updates apps in the background.

**Comment by hua0521** [comment]
you. can try last commit [557765f](https://github.com/moonlight-stream/moonlight-ios/commit/557765f2c0b83bcfd722b8965fa87bcb46878f6d)  it works for me.

**Comment by suchipi** [comment]
Thanks for the fix!
