### ISSUE TITLE
[Bug] No host????

### ISSUE THREAD

**Issue by radderboy9** [moonlight-stream/moonlight-ios#82]
ive tried everything to get a host on it i portforwarded i have the latest version of everything and it still doesnt work can someone tell me how i can fix my problem?

**Comment by radderboy9** [comment]
its a **bug**

**Comment by dwaxemberg** [comment]
@radderboy9 Can you provide more details? What is your setup? Did you try to stream both locally and remotely? What version of GFE are you running?

**Comment by radderboy9** [comment]
@dwaxemberg i have a netgear nighthawk router and its running 5g and 2.4g, i have a geforce gtx 750ti 2gb and i7 4770 i also have 16 gigs of ram. im running gfe 2.4.121 and i am running my latest graphics drivers, i do also have my computer hardwired to my router.

**Comment by radderboy9** [comment]
@dwaxemberg i even port forwarded my computers ip, but every time i put my ip to the new host button it gives me this error, "unable to connect to host" and then below it it says my ip adress, i have also tried my gamestream name and my pc's name.

**Comment by mategoncalves** [comment]
The new GFE version uses Google Plus to log in into something, is that related to the problem maybe? I can't find any hosts as well.

**Comment by abattrick** [comment]
No I am using new beta gfe and I find my host just fine but I have connection issues when connecting

**Comment by mategoncalves** [comment]
Why I can't find any hosts? 

Both my computer and iPad are in the same network, tried with ip public address and name, but they don't appear. Tried with limelight 0.9.0 and 0.4.1 and GFE version 2.4.121 using a GTX870M and a apple router.

**Comment by jeaz** [comment]
I'm running with 0.9 and 2.4.121 and have the same problem, I can't find any hosts. But using direct IP and hostname, no luck.

**Comment by mategoncalves** [comment]
Try to reinstall GFE, it worked for me.


2015-04-09 16:36 GMT+02:00 Jeaz <notifications@github.com>:

> I'm running with 0.9 and 2.4.121 and have the same problem, I can't find
> any hosts. But using direct IP and hostname, no luck.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/limelight-stream/limelight-ios/issues/82#issuecomment-91249924>
> .
>



-- 
Att,

Mateus Gonçalves.

**Comment by jeaz** [comment]
Re-installing GFE did not solve it for me.

**Comment by askep3** [comment]
I think the latest GFE doesn't use IP's anymore, so limelight might need to be completely changed to support the new Nvidia account way of connecting.

**Comment by jeaz** [comment]
Any more light on this? 

Re-installing does not solve it. I did a complete re-installation. Even re-installed Windows from scratch, but no luck. Disabled the firewall and everything else I can think of.

**Comment by cgutman** [comment]
Make sure "NVIDIA Streaming Service" (nvstreamsvc.exe) is running in Task Manager. The latest GFE (2.4.1) still allows PIN based pairing via IP, so that's not the problem.

**Comment by jeaz** [comment]
It's running, still says when I try to add Host that it can't connect to host.
I'm running it on a very bare-bone Win 8.1 installation. i've got GFE, Steam and Origin installed, and a few games, that's pretty much it. And I've tried running with firewall disabled with the same result.

**Comment by shusain93** [comment]
Have you tried being connected to the local wifi and manually putting in your PCs local IP as the host? What happens?

**Comment by shusain93** [comment]
I don't believe this is a bug, it should be flag as tech support. I have the same setup and it works correctly

**Comment by jeaz** [comment]
Has this been solved then? Haven't been able test it since the latest build in Testflight has been expired for some time. Connecting directly to the IP was not a solution to the problem.

**Comment by shusain93** [comment]
I nor anyone else can reproduce this issue. It seems that this isn't a bug, more a tech support problem. 0.9.1(2) has been out for a while now, actually so I'm not sure why you haven't gotten it yet. 

My recommendation is to check all of your ports required for forwarding on http://canyouseeme.org and then report back which ones pass and which fali. Some ports aren't testable on canyouseeme because their protocols (*I believe, not exactly sure*) don't respond to the test.

**Comment by jeaz** [comment]
I actually don't see the project in Testflight any longer. Guess I got bumped ;-)

As for it being a bug or not. I'm not the only one in this thread who had the problem, but I'll check the site but I've only been trying with local wifi and direct IP, since the host can't be found.
