### ISSUE TITLE
[Bug] [Large App Library] Hang when starting app

### ISSUE THREAD

**Issue by cgutman** [moonlight-stream/moonlight-ios#85]
If the GFE web server isn't responding or (possibly) if it fails starting the app, Limelight will hang with the "Starting App" spinner. The swipe from the left won't work for going back. After pressing the home button and returning to the app, it's still hung.

I suspect that there are many background app asset loads which are causing the GFE server to be unresponsive.

Limelight should cancel all current and pending asset loads before attempting to start streaming.

**Comment by dwaxemberg** [comment]
Should be fixed in 5296b2eb39930acd58895fd848aeae45a3bfdfa8
Reopen if persists in next beta
