### ISSUE TITLE
[Bug] [Large App Library] App assets don't load

### ISSUE THREAD

**Issue by cgutman** [moonlight-stream/moonlight-ios#86]
When connected to a PC with a large app library, it seems that we may be causing the server to die under the load of us fetching the assets all at once. We should throttle concurrent asset loads to 4, in line with Android's limit.

**Comment by abattrick** [comment]
When trying to connect the dial spins and then it goes back to main menu. Doesn't connect

**Comment by abattrick** [comment]
Yes all I get is the spinner then back to the hosts list. Doesn't load games list anymore. Anyway I can get this working somehow?

**Comment by dwaxemberg** [comment]
Should be fixed as of 2972d40d92fdd044a05f1d08680e1b740f15ff52
Reopen if still exists in next beta
