### ISSUE TITLE
Pairing not working with update.

### ISSUE THREAD

**Issue by Zekisu** [moonlight-stream/moonlight-ios#88]
I just updated via Testflight today on my device. The previous version would show multiples of my computer I was streaming from and require a new pin with each use. But now I can't even pair with the computer even though it shows up. The pairing pin shows on my phone but won't load on the PC I 'am wishing to stream from. Anyone else having a pairing issue with the current release?

**Comment by abattrick** [comment]
I reinstalled my gfe and it's working again. Had to repai but it works

**Comment by dwaxemberg** [comment]
@Zekisu Please comment as to whether this is still an issue.

**Comment by Zekisu** [comment]
I had to reinstall drivers from scratch and restart some services. But it's working again. Thanks for fixing the multiple machines showing up too which would cause the same machine to appear several times but need pairing each time.
