### ISSUE TITLE
App crashes on launch

### ISSUE THREAD

**Issue by TheWispy** [moonlight-stream/moonlight-ios#89]
Hello there,

When I try to open Limelight, after showing the splash screen, it crashes. When I try to open the app in the multi-task bar, it shows my host pc's with a frozen loading circle thing (the apple one you get when you run out of battery). When I open this, it crashes again. I've tried turning off bluetooth, so far and restarting GFE, but this hasn't changed anything.

I am yet to re-install the app itself, but I shall report back once I have. I am running this on a 5th generation iPod touch.

**Comment by TheWispy** [comment]
Ok, re-installing the app worked fine. I'm now paired back up with my pc - false alarm.

**Comment by cgutman** [comment]
Probably a DB or settings migration issue that won't affect anyone outside the early beta users.
