### ISSUE TITLE
New Icon for Moonlight

### ISSUE THREAD

**Issue by phantom-playR** [moonlight-stream/moonlight-ios#93]
Hey there, I make a new icon for the new name, what do you think ?

![moonlight icon](https://cloud.githubusercontent.com/assets/4344835/7296153/44939cda-e9bd-11e4-9e95-52c2f1160f79.png)
![moonlight design](https://cloud.githubusercontent.com/assets/4344835/7296155/45f5fe60-e9bd-11e4-8403-72ff671d5829.png)

**Comment by sigboe** [comment]
I am sure people know about this, but if not it should be taken into
consideration that an opensource project called Moonlight.
http://www.mono-project.com/docs/web/moonlight/

On Thu, Apr 23, 2015 at 1:33 PM, phantom-playR <notifications@github.com>
wrote:

> Hey there, I make a new icon for the new name, what do you think ?
>
> [image: moonlight icon]
> <https://cloud.githubusercontent.com/assets/4344835/7296153/44939cda-e9bd-11e4-9e95-52c2f1160f79.png>
> [image: moonlight design]
> <https://cloud.githubusercontent.com/assets/4344835/7296155/45f5fe60-e9bd-11e4-8403-72ff671d5829.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moonlight-stream/moonlight-ios/issues/93>.
>



--

**Comment by cgutman** [comment]
@phantom-playR Looks really nice. @dwaxemberg thoughts?

@sigboe It looks like that project is end-of-life. I think it's also unlikely that people will confuse this Moonlight project with that project. Thanks for mentioning it though.

**Comment by dwaxemberg** [comment]
@cgutman I think it looks pretty great. I would be happy making it our icon. Just a couple questions:
@phantom-playR What would the iOS version of the icon look like (by that I mean rounded square one)? And do you have any thoughts on how the rest of the app UI should look to match?

**Comment by phantom-playR** [comment]
Maybe something like that ?

iOS : 
![ios icon](https://cloud.githubusercontent.com/assets/4344835/7314867/f7e8a8ce-ea68-11e4-8e58-cc9f8fbb7a08.png)

Android : 
![android icon](https://cloud.githubusercontent.com/assets/4344835/7314870/fde315ac-ea68-11e4-89ef-a1654738e199.png)

**Comment by phantom-playR** [comment]
Maybe something like that ?

![ios icon](https://cloud.githubusercontent.com/assets/4344835/7315047/b5d9182c-ea6a-11e4-9c1d-c15e1676cf9c.png)
![moonlight test](https://cloud.githubusercontent.com/assets/4344835/7315049/b947c814-ea6a-11e4-8b3c-cb680b452f25.png)

**Comment by firestorm185** [comment]
looks cool!

**Comment by khb008** [comment]
Very nice! Great work

**Comment by rollinbro63** [comment]
Hi I'd like to beta test moonlight my real email is andrewcgreen8@gmail.com iPad Air

**Comment by mrb113** [comment]
Ping - Cameron, Diego, etc, we still going in the direction of a new logo to match the new name? 
@cgutman @dwaxemberg

**Comment by dwaxemberg** [comment]
@mrb113 It has been implemented already on iOS not sure about Android et al.
