### ISSUE TITLE
Please add to Beta program

### ISSUE THREAD

**Issue by M0BI0S** [moonlight-stream/moonlight-ios#94]
Hello, I would be very gratefull to be added to your beta program for moonlight ios. 
My PC specs:
Nvidea 780 GTX FTW
i72400
16GB RAM

WLan:
2.4 Ghz & 5 Ghz

iOS Devices (ios 8.3):
Iphone 5
iphone 6
Ipad air 2

My email: olio (at) highfire (dot) de
(I hope writing my email like this will not be an issue, as I have concerns writing my email in clear text, for email crawler bot usage)

**Comment by dwaxemberg** [comment]
added

**Comment by M0BI0S** [comment]
First of all, thank you for adding me to the Beta program.

Is there somewhere a dedicated beta forum section or the like, to leave detailed feedback? 
There is an option through the Testflight app, but I cannot access this via PC I think. 

I have been testing the Limelight / Moonlight Beta app now with a SteelSeries Stratus XL MFI Controller. 
Using different Wifi connections (2.4 ghz and 5ghz). 
Testing the on screen controls, resolutions and different bandwidth options. 
Using a set of different games.

Thank you very much for the good work so far.

Greetz,

MoBIoS
