### ISSUE TITLE
Beta test

### ISSUE THREAD

**Issue by capmalo** [moonlight-stream/moonlight-ios#95]
Hello Limelight devs !

I would like to participate to the beta program of limelight on iOS, I can test on the followed devices:

- iPhone 6
- iPhone 5 & 5C
- iPad 4

And maybe iPhone 5S if my friend is interested.

Here is my Apple  account mail: f14-tomat@neuf.fr

Thx you for your work.

**Comment by dwaxemberg** [comment]
added
