### ISSUE TITLE
[Bug] RTSP Handshake error

### ISSUE THREAD

**Issue by chesterfire** [moonlight-stream/moonlight-ios#98]
Whenever I try to launch an app, I get an error message that says RTSP handshake failed. The game does launch on my machine, and my drivers are up to date. This happens on both my iPod 5, and my iPad air 2. My GFE is up to date, as are my drivers. Any fix?
![img_0289](https://cloud.githubusercontent.com/assets/9505475/7439155/56b265f6-f037-11e4-8e9a-82f557eb0537.PNG)

**Comment by cgutman** [comment]
It's probably caused by port 48010 being blocked by a firewall or something. I'm not sure if nvstreamer.exe opens that socket, but if so it could be being blocked or otherwise prevented from launching.

**Comment by chesterfire** [comment]
I don't think it is blocked by firewall, because when I disable firewall, the error still happens.
